// # 内容扩建 D 类（试卷份数+题量+级别）：后端 + 运维 轨道
// 每轨道新增 初级(免费) / 中级(免费) / 高级VIP(进阶) 三套，每套 ~12 选择 + 3 笔试。
// 幂等：set id 已存在则跳过；零 schema 漂移。写入 data/seed-content.json 后需跑 _reseed.mjs 落库。
import fs from 'fs'
const SEED = './data/seed-content.json'
const s = JSON.parse(fs.readFileSync(SEED, 'utf-8'))

const newSets = [
  /* ===================== 后端 初级 ===================== */
  {
    id: 'exam-be-basic', name: '后端入门基础卷 · 初级', track: 'backend', level: '初级', duration: 25, vipOnly: false,
    choices: [
      { id: 'beb-c1', tag: 'HTTP', q: 'HTTP 状态码 500 表示？',
        options: ['请求成功', '资源未找到', '服务器内部错误', '需要身份验证'], answer: ['C'],
        explain: '500 Internal Server Error 是服务端未捕获异常；404 未找到、401 未授权、200 成功。' },
      { id: 'beb-c2', tag: '数据库', q: 'SQL 中用于从表中查询数据的语句是？',
        options: ['INSERT', 'UPDATE', 'SELECT', 'DELETE'], answer: ['C'],
        explain: 'SELECT 查询；INSERT 插入、UPDATE 更新、DELETE 删除。' },
      { id: 'beb-c3', tag: '概念', q: 'RESTful API 通常建议使用什么表示资源？',
        options: ['随机字符串', 'URI（统一资源标识符）', '端口号', 'IP 地址'], answer: ['B'],
        explain: 'REST 用 URI 标识资源，配合 HTTP 方法（GET/POST/PUT/DELETE）表达操作，风格统一、利于缓存与网关。' },
      { id: 'beb-c4', tag: '并发', q: '关于进程与线程，正确的是？',
        options: ['进程间不隔离内存', '进程是资源分配单位、线程是执行单位，同进程内线程共享内存', '线程比进程更重', '一个进程只能有一个线程'], answer: ['B'],
        explain: '进程拥有独立内存空间，线程共享进程内存、更轻量；多线程通信方便但需同步，多进程隔离好但开销大。' },
      { id: 'beb-c5', tag: '安全', q: '密码存储的正确做法是？',
        options: ['明文存储', '对称加密存储', '加盐哈希（如 scrypt/bcrypt）存储', '只存前几位'], answer: ['C'],
        explain: '密码应加盐做单向哈希（scrypt/bcrypt/argon2），即使库泄露也无法反推明文；绝不明文或可逆加密存储。' },
      { id: 'beb-c6', tag: 'API', q: 'GET 请求的特点，正确的是？',
        options: ['应有副作用（修改数据）', '应幂等且只用于获取，参数在 URL', '不能带参数', '比 POST 更安全'], answer: ['B'],
        explain: 'GET 语义是获取、应幂等无副作用、参数在 URL（故不宜放密码）；数据修改用 POST/PUT/DELETE。' },
      { id: 'beb-c7', tag: '数据库', q: '主键（Primary Key）的作用是？',
        options: ['加快所有查询', '唯一标识一行、不许空且唯一', '存储大文本', '替代索引'], answer: ['B'],
        explain: '主键唯一且非空，标识每行；它自动建唯一索引，但“加快所有查询”言过其实（需按访问模式建索引）。' },
      { id: 'beb-c8', tag: '网络', q: 'HTTPS 相比 HTTP 多了什么？',
        options: ['更慢的协议版本', 'TLS 加密与身份认证', '不同的端口号必然不同', '无实际作用'], answer: ['B'],
        explain: 'HTTPS = HTTP over TLS，提供传输加密、完整性校验与服务器身份认证，防止窃听与中间人篡改。' },
      { id: 'beb-c9', tag: '概念', q: '什么是幂等（Idempotent）？',
        options: ['执行越快越好', '同一操作执行一次与多次效果相同', '必须有返回值', '只用于查询'], answer: ['B'],
        explain: '幂等指多次执行与一次执行效果一致（如 PUT 更新同一资源）；对支付/下单等关键路径，幂等键防重复提交至关重要。' },
      { id: 'beb-c10', tag: '缓存', q: '缓存的主要目的是？',
        options: ['增加数据库压力', '减少重复计算/查询、降低延迟与负载', '替代数据库', '让数据更慢'], answer: ['B'],
        explain: '缓存把热点数据放更快的存储（内存），减少 DB 压力与延迟；但引入一致性、穿透/击穿/雪崩等问题需治理。' },
      { id: 'beb-c11', tag: 'JSON', q: 'HTTP API 常用的数据交换格式是？',
        options: ['只有 XML', 'JSON 最常用（轻量、易解析）', '只能用二进制', 'CSV 为主'], answer: ['B'],
        explain: 'JSON 因轻量、语言无关、易解析成为 Web API 主流；XML 仍有存量系统，二进制（如 Protobuf）用于内部高性能场景。' },
      { id: 'beb-c12', tag: '日志', q: '关于日志级别，通常不包含？',
        options: ['DEBUG', 'INFO', 'ERROR', 'RAINBOW'], answer: ['D'],
        explain: '常见级别 DEBUG/INFO/WARN/ERROR/FATAL；RAINBOW 不是标准级别。合理分级利于排查与降噪。' }
    ],
    written: [
      { id: 'beb-w1', q: '解释 HTTP 常见方法（GET/POST/PUT/DELETE）的语义，并说明为什么“修改数据的操作不应使用 GET”。',
        points: ['GET 获取/幂等', 'POST 新建', 'PUT 替换/幂等', 'DELETE 删除', 'GET 被缓存/预取有副作用风险'],
        reference: 'GET 语义获取、应幂等且无副作用；POST 新建；PUT 整体替换（幂等）；DELETE 删除。若用 GET 做修改，浏览器/代理的预取、缓存、重试都会触发非预期写操作，且不符合语义、难做安全与缓存控制。' },
      { id: 'beb-w2', q: '什么是 RESTful 风格？请给出一个“用户资源的增删改查”的 URI 与 HTTP 方法设计示例。',
        points: ['资源用名词 URI', '方法表达操作', '状态码表达结果', '无状态'],
        reference: 'REST 用名词 URI 标识资源、HTTP 方法表达操作：GET /users 列表、GET /users/{id} 详情、POST /users 创建、PUT /users/{id} 更新、DELETE /users/{id} 删除；配合状态码（200/201/404）与无状态请求。' },
      { id: 'beb-w3', q: '为什么密码不能明文存储？请描述“加盐哈希”的基本流程，并说明 scrypt/bcrypt 相比 MD5 的优势。',
        points: ['明文泄露即沦陷', '随机 salt + 哈希', '慢哈希抗暴力', 'MD5 过快且易碰撞'],
        reference: '明文存储一旦库泄露所有账号失守。正确做法：为每个用户生成随机 salt，存储 hash(salt+password)（如 scrypt/bcrypt/argon2，自带盐与可调成本）。MD5 过快且无盐，易被彩虹表/暴力破解；scrypt 等“慢哈希”故意增加计算成本，抗暴力破解。' }
    ]
  },
  /* ===================== 后端 中级 ===================== */
  {
    id: 'exam-be-inter', name: '后端进阶能力卷 · 中级', track: 'backend', level: '中级', duration: 35, vipOnly: false,
    choices: [
      { id: 'bei-c1', tag: '数据库', q: '关于数据库索引，正确的是？',
        options: ['索引越多查询越快', '索引加速查询但拖慢写入并占空间，需按查询模式建', '索引对写无影响', '主键不需要索引'], answer: ['B'],
        explain: '索引加速检索但每次写都要维护、且占存储；应按高频 WHERE/JOIN/ORDER BY 建，避免冗余。主键自动唯一索引。' },
      { id: 'bei-c2', tag: '事务', q: 'ACID 中的“I”（隔离性）是指？',
        options: ['原子性', '事务间相互隔离、并发互不干扰', '持久性', '一致性'], answer: ['B'],
        explain: 'I=Isolation 隔离性，保证并发事务互不干扰；A 原子、C 一致、D 持久。 isolation level 控制脏读/不可重复读/幻读。' },
      { id: 'bei-c3', tag: '并发', q: '关于乐观锁与悲观锁，正确的是？',
        options: ['乐观锁先加锁再读', '乐观锁用版本号/时间戳冲突检测，适合冲突少；悲观锁先加锁适合冲突多', '悲观锁永不阻塞', '两者等价'], answer: ['B'],
        explain: '乐观锁不加锁、提交时校验版本，冲突少时性能好；悲观锁（如 SELECT FOR UPDATE）提前加锁，冲突频繁时更安全但吞吐低。' },
      { id: 'bei-c4', tag: '缓存', q: '缓存穿透是指？',
        options: ['缓存集中失效', '查不存在的 key 绕过缓存直击 DB', '缓存与 DB 不一致', '缓存写满'], answer: ['B'],
        explain: '穿透=查询根本不存在的 key，缓存不命中且 DB 也无，请求每次穿透到 DB；可用布隆过滤器或空值缓存拦截。击穿=单热点失效；雪崩=大量同时失效。' },
      { id: 'bei-c5', tag: 'API', q: '关于 API 版本管理，正确的是？',
        options: ['永远不能变更', 'URL 路径或请求头版本都可行，需向后兼容演进', '版本只能存数据库', '无需管理'], answer: ['B'],
        explain: '常见有 /v1/ 路径版本与 Accept 头版本，各有利弊；关键是向后兼容地演进，避免破坏老客户端。' },
      { id: 'bei-c6', tag: '消息', q: '消息队列（MQ）的主要作用不包括？',
        options: ['异步解耦', '流量削峰', '提高响应速度', '广播通知'], answer: ['C'],
        explain: 'MQ 用于异步解耦、削峰填谷、可靠投递与广播；异步本身通常增加（而非提高）单请求响应速度，换来系统弹性。' },
      { id: 'bei-c7', tag: '安全', q: '关于 SQL 注入，正确的是？',
        options: ['用字符串拼接 SQL 安全', '应使用参数化查询/预编译语句防止注入', '转义一次就绝对安全', '只发生在前端'], answer: ['B'],
        explain: 'SQL 注入源于把用户输入拼进 SQL；防御用参数化查询（预编译占位符），让输入只作数据不作代码；仅靠转义易遗漏。' },
      { id: 'bei-c8', tag: '分布式', q: 'CAP 理论在网络分区时要求取舍？',
        options: ['一致性与可用性', '一致性与持久性', '可用性与吞吐', '分区与复制'], answer: ['A'],
        explain: '分布式发生分区（P 必保）时，只能在一致性（C）与可用性（A）间取舍：CP 暂停不可用分区保一致，AP 继续服务但可能读到旧值。' },
      { id: 'bei-c9', tag: '测试', q: '关于单元测试与集成测试，正确的是？',
        options: ['单测测多个模块协作', '单测隔离测最小单元，集成测模块间协作', '集成测最快最多', '单测不需要断言'], answer: ['B'],
        explain: '单测隔离测函数/类、快而多；集成测跨模块/外部依赖协作；端到端测关键路径。金字塔以单测打底。' },
      { id: 'bei-c10', tag: '认证', q: 'JWT 的常见风险是？',
        options: ['永远安全', '签发后难以主动吊销（需短过期+刷新/黑名单）', '不能跨域', '无法携带信息'], answer: ['B'],
        explain: 'JWT 无状态、签发后服务端难主动失效，常用短 access token + 刷新 token，或维护吊销列表；过长过期增大被盗用窗口。' },
      { id: 'bei-c11', tag: '性能', q: '数据库连接池的作用，正确的是？',
        options: ['连接越多越好', '复用连接降开销，但过多会加剧竞争与内存，应基于负载设定上限', '只用于读库', '连接池无用'], answer: ['B'],
        explain: '连接池避免频繁建连开销；但连接数并非越多越好，超过 DB 负载拐点后竞争与切换反而降吞吐，应实测设定上限。' },
      { id: 'bei-c12', tag: '设计', q: '关于限流，令牌桶的特点是？',
        options: ['完全不允许突发', '以固定速率生成令牌、桶满则拒，允许一定突发', '与漏桶完全相同', '只能用于网络层'], answer: ['B'],
        explain: '令牌桶按速率放令牌、桶有容量故可短时放行积累突发；漏桶以恒定速率平滑输出。二者取舍：要削峰用漏桶，要容忍突发用令牌桶。' }
    ],
    written: [
      { id: 'bei-w1', q: '解释数据库事务的 ACID，并以“转账”为例说明为什么需要事务与隔离级别。',
        points: ['A 原子/C 一致/I 隔离/D 持久', '转账需扣款+入账同成功或同失败', '隔离级别防脏读/不可重复读/幻读'],
        reference: 'ACID：原子（全成功或全回滚）、一致（约束不被破坏）、隔离（并发互不干扰）、持久（提交后不丢）。转账=A 扣款且 B 入账必须同生共死（原子），否则钱丢失或翻倍；隔离级别控制并发下的可见性，避免脏读/不可重复读/幻读。' },
      { id: 'bei-w2', q: '设计一个防 SQL 注入的数据库访问层：说明参数化查询原理，并给出一段“按用户名查用户”的安全写法（伪代码）。',
        points: ['不拼接用户输入', '预编译占位符', '输入只作数据', '最小权限账号'],
        reference: '参数化查询把 SQL 结构与数据分离：prepare("SELECT * FROM users WHERE name = ?") 后 bind(name)，数据库把 name 仅当值处理、不解析为 SQL。伪代码：stmt=db.prepare("SELECT id FROM users WHERE username=?"); stmt.bind(1, userInput); rows=stmt.query()。再配合最小权限 DB 账号，即便有误也不至被拖库。' },
      { id: 'bei-w3', q: '比较乐观锁与悲观锁的适用场景，并设计一个“库存扣减”接口如何保证不超卖。',
        points: ['乐观：版本号冲突检测', '悲观：FOR UPDATE 加锁', '库存扣减需原子', '可结合 Redis 原子递减'],
        reference: '冲突少、读多写少用乐观锁（UPDATE ... SET stock=stock-1 WHERE id=? AND stock>0 这种原子条件即乐观思路）；冲突多、强一致用悲观锁（SELECT ... FOR UPDATE 后扣减）。库存扣减关键是“判断+扣减”原子化，可用带条件的 UPDATE 返回影响行数，或 Redis DECR 原子递减 + DB 最终一致，避免超卖。' }
    ]
  },
  /* ===================== 后端 高级 VIP（进阶） ===================== */
  {
    id: 'exam-be-vip-2', name: '后端架构深挖卷 · 高级 VIP', track: 'backend', level: '高级', duration: 40, vipOnly: false,
    choices: [
      { id: 'bev2-c1', tag: '分布式事务', q: '关于 Saga 与 2PC，正确的是？',
        options: ['2PC 无阻塞风险', 'Saga 用本地事务+补偿达成最终一致，避免长事务持锁', 'Saga 不需要补偿', '2PC 必然最终一致'], answer: ['B'],
        explain: '2PC 强一致但持锁久、协调者故障易阻塞；Saga 拆为本地事务序列+补偿操作，失败时反向补偿，最终一致且不长期持锁。' },
      { id: 'bev2-c2', tag: '一致性', q: '关于最终一致性，正确的是？',
        options: ['永远不一致', '停止写入并经过足够时间，各副本收敛一致', '只存在于单库', '比强一致更不安全应杜绝'], answer: ['B'],
        explain: '最终一致保证：若无新写入、经过足够时间，副本将收敛。它在分区/高可用下以短暂不一致换可用性，是大型系统常见取舍。' },
      { id: 'bev2-c3', tag: '幂等', q: '设计幂等下单接口，正确的是？',
        options: ['依赖 MQ 不重复', '客户端带幂等键，服务端唯一约束去重/返回首次结果', '每次直接新增', '只在客户端保证'], answer: ['B'],
        explain: '客户端生成幂等键随请求带；服务端以唯一约束落库，重复提交返回首次结果，从而安全重试（支付/下单关键路径必备）。' },
      { id: 'bev2-c4', tag: 'Kafka', q: 'Kafka 实现精确一次（exactly-once）依赖？（多选）',
        options: ['幂等生产者去重', '事务跨分区原子写', '消费位移与业务落库同事务', '仅 at-most-once'], answer: ['A', 'B', 'C'], multi: true,
        explain: 'EOS 由幂等生产者（去重）+ 事务（跨分区原子写、与位移协调）组合；消费端需“处理+提交位移”原子化才端到端精确一次。' },
      { id: 'bev2-c5', tag: '可观测', q: '分布式链路追踪的上下文传播靠？',
        options: ['只在网关记日志', 'W3C traceparent 等标准跨服务透传 trace/span id', '只在单进程有效', 'span 无需父子'], answer: ['B'],
        explain: '调用方把 trace id 与 parent span id 注入请求头（如 traceparent），下游派生子 span，后端按父子关系还原调用拓扑与耗时。' },
      { id: 'bev2-c6', tag: '限流', q: '分布式限流器（多实例共享状态）通常怎么做？',
        options: ['各实例独立计数即可', '用 Redis 存令牌与时间戳，Lua 脚本原子 refill+扣减', '不需要共享', '只靠 CPU 限流'], answer: ['B'],
        explain: '多实例需共享计数：Redis 存每 key 的令牌数与时间戳，用 Lua 脚本保证“计算+判断+扣减”原子，避免竞态；所有实例指向同一 Redis 即全局限流。' },
      { id: 'bev2-c7', tag: 'ID', q: 'Snowflake 分布式 ID 的核心是？',
        options: ['数据库自增', '时间戳+机器位+序列号的 64 位 ID，避免中心化', '客户端随机数', '单点 Redis'], answer: ['B'],
        explain: 'Snowflake 把 64 位分为时间戳、机器/实例位、序列号，各节点本地生成、不依赖中心且趋势递增，利于 B+Tree 写入；需处理时钟回拨。' },
      { id: 'bev2-c8', tag: 'TLS', q: 'TLS 1.3 相比 1.2 的改进是？',
        options: ['握手更慢', '支持 1-RTT 建连、0-RTT 恢复，移除不安全密钥交换', '仍用静态 RSA', '不再加密握手'], answer: ['B'],
        explain: 'TLS 1.3 精简为 1-RTT（会话恢复 0-RTT），移除弱密钥交换（静态 RSA），默认前向安全，握手消息也加密。' },
      { id: 'bev2-c9', tag: 'API', q: 'gRPC 相比 REST/JSON 通常更快的原因是？',
        options: ['HTTP/1.1 + 文本 JSON', 'HTTP/2 多路复用 + Protobuf 二进制，体积小解析快', '不需要 IDL', '不支持流式'], answer: ['B'],
        explain: 'gRPC 用 Protobuf 强类型二进制（比 JSON 小且省解析），承载于 HTTP/2（多路复用、头部压缩、双向流），内部服务调用延迟与吞吐更优。' },
      { id: 'bev2-c10', tag: '容灾', q: '关于 RPO 与 RTO，正确的是？',
        options: ['RPO 是恢复时长', 'RPO=允许丢失的数据量，RTO=恢复所需时长', 'RTO 是丢数据量', '二者无关'], answer: ['B'],
        explain: 'RPO（Recovery Point Objective）指能容忍丢失多少数据（如 5 分钟）；RTO（Recovery Time Objective）指多久恢复服务。容灾设计围绕二者定目标。' },
      { id: 'bev2-c11', tag: '缓存', q: '缓存雪崩的应对是？（多选）',
        options: ['随机 TTL 错峰', '多级缓存', '热点 key 不过期+互斥重建', '所有 key 同一过期时间'], answer: ['A', 'B', 'C'], multi: true,
        explain: '雪崩=大量 key 同时失效打爆 DB；应对：随机 TTL 错峰、多级缓存、热点 key 不过期或逻辑过期+互斥重建。千万别统一过期时间。' },
      { id: 'bev2-c12', tag: '设计', q: '关于 CQRS（读写分离），正确的是？',
        options: ['读写必须用同一模型', '将写模型与读模型分离，读可走专门优化的视图/投影', '只适用于单体', '增加复杂度毫无收益'], answer: ['B'],
        explain: 'CQRS 把写（命令）与读（查询）模型分开，读侧可用预聚合视图/专门存储优化查询性能；代价是最终一致与系统复杂度，适合读写负载差异大的场景。' }
    ],
    written: [
      { id: 'bev2-w1', q: '设计一个幂等的支付下单接口：说明幂等键生成、服务端去重存储、与第三方支付回调的协同，给出伪代码。',
        points: ['客户端生成幂等键', '服务端唯一约束去重', '回调按单号去重', '状态机防重复记账'],
        reference: 'POST /pay 带 Idempotency-Key 头。服务端 INSERT INTO pay_order(idemp_key,...) ON CONFLICT DO NOTHING，命中冲突则返回既有订单。第三方回调按 order_no 唯一处理，状态机（CREATED→PAID）保证只入账一次，重复回调因状态已 PAID 忽略。' },
      { id: 'bev2-w2', q: '描述如何在 Kafka 上构建端到端精确一次（exactly-once）的“消费-处理-写出”管道，涵盖幂等生产者、事务、位移与业务落库原子化。',
        points: ['生产者幂等+事务', '消费位移与业务写同事务', '业务表唯一键防重', 'enable.idempotence+transactional.id'],
        reference: '生产者设 enable.idempotence=true 与 transaction.id；消费后在事务内“处理业务落库+发送下游+提交位移”，由 broker 保证原子。消费端对业务主键加唯一约束，即使 at-least-once 重放也不重复处理，实现端到端精确一次。' },
      { id: 'bev2-w3', q: '设计一个短链服务：分布式 ID 生成（短码）、302 重定向、点击统计与防刷，并讨论热点短码与存储选型。',
        points: ['短码：发号器/哈希/Base62', '302+缓存，注意 301 被缓存', '统计异步+布隆去重', '防刷限流', 'KV+时序存储'],
        reference: '短码用 Snowflake/号段或长链哈希取前 N 位（冲突重试）。重定向用 302（避免 301 被缓存致长链无法更新）。统计异步写、HyperLogLog 估 UV、布隆去重。防刷单码限频。存储：短码映射用 Redis+DB 双写，统计落时序库；热点短码走缓存。' }
    ]
  },
  /* ===================== 运维 初级 ===================== */
  {
    id: 'exam-op-basic', name: '运维入门基础卷 · 初级', track: 'devops', level: '初级', duration: 25, vipOnly: false,
    choices: [
      { id: 'opb-c1', tag: 'Linux', q: '查看当前目录文件的命令是？',
        options: ['cd', 'ls', 'pwd', 'mkdir'], answer: ['B'],
        explain: 'ls 列出目录内容；cd 切换目录、pwd 显示当前路径、mkdir 建目录。' },
      { id: 'opb-c2', tag: '网络', q: '测试到某主机的网络连通性常用？',
        options: ['ping', 'grep', 'chmod', 'top'], answer: ['A'],
        explain: 'ping 用 ICMP 测连通与往返时延；grep 文本搜索、chmod 改权限、top 看进程。' },
      { id: 'opb-c3', tag: '容器', q: 'Docker 镜像与容器的关系是？',
        options: ['镜像运行起来成为容器', '容器编译出镜像', '二者无关', '镜像就是容器'], answer: ['A'],
        explain: '镜像是静态模板（含代码/依赖），容器是镜像的运行实例；可从一个镜像起多个容器。' },
      { id: 'opb-c4', tag: '权限', q: 'Linux 中 chmod +x 的作用是？',
        options: ['删除文件', '增加可执行权限', '修改所有者', '压缩文件'], answer: ['B'],
        explain: 'chmod 改文件权限，+x 增加可执行；chown 改所有者；权限分 r/w/x 对应所有者/组/其他。' },
      { id: 'opb-c5', tag: 'CI/CD', q: 'CI（持续集成）的核心动作是？',
        options: ['手动部署', '代码提交后自动构建与测试', '只写文档', '关闭监控'], answer: ['B'],
        explain: 'CI 在提交后自动拉取、构建、跑测试，尽早发现集成错误；CD 进一步自动部署到各环境。' },
      { id: 'opb-c6', tag: '监控', q: 'CPU 使用率过高的排查起点是？',
        options: ['直接重启', 'top/htop 看哪个进程吃 CPU，再下钻', '忽略', '只看磁盘'], answer: ['B'],
        explain: '先用 top/htop 定位高 CPU 进程，再结合该进程的火焰图/日志下钻具体热点函数，而非盲目重启。' },
      { id: 'opb-c7', tag: '概念', q: '什么是“基础设施即代码”（IaC）？',
        options: ['手写每台服务器', '用代码声明/管理基础设施，可版本化与复用', '只用图形界面', '不备份'], answer: ['B'],
        explain: 'IaC 用代码（Terraform/Ansible）管理云资源与配置，可版本化、评审、自动重建，避免“雪花服务器”。' },
      { id: 'opb-c8', tag: '日志', q: '集中式日志方案（如 ELK）的价值是？',
        options: ['把日志删掉', '跨多机收集、检索与可视化，便于排障', '只存本地', '增加磁盘负担无意义'], answer: ['B'],
        explain: 'ELK/EFK 把分散在各机器的日志收集、结构化、索引与可视化，跨服务排障时一处检索即可，配合 traceId 串联链路。' },
      { id: 'opb-c9', tag: 'DNS', q: 'DNS 的主要作用是？',
        options: ['分配 IP', '把域名解析为 IP 地址', '加密流量', '管理内存'], answer: ['B'],
        explain: 'DNS 将易记的域名解析为机器用的 IP；TTL 控制解析结果缓存时长，影响切换速度。' },
      { id: 'opb-c10', tag: '安全', q: '关于备份，正确的是？',
        options: ['备份一次就安全', '需定期备份并做恢复演练验证可用', '不需要恢复演练', '只备份配置'], answer: ['B'],
        explain: '备份不等于安全，恢复演练才是关键；需全量+增量+binlog(PITR)，并定期验证可恢复。' },
      { id: 'opb-c11', tag: '进程', q: '查看运行中的进程用？',
        options: ['ls', 'top / ps', 'cat', 'echo'], answer: ['B'],
        explain: 'top（实时）/ps（快照）查看进程与资源；ls 列文件、cat 看内容。' },
      { id: 'opb-c12', tag: '发布', q: '蓝绿部署的特点是？',
        options: ['逐步放量', '两套相同环境，流量一刀切切换，异常秒级回切', '只部署一次', '无法回滚'], answer: ['B'],
        explain: '蓝绿维护蓝/绿两套环境，切换是“全或无”，出问题秒级切回，最稳但需双倍资源；金丝雀才是渐进放量。' }
    ],
    written: [
      { id: 'opb-w1', q: '解释 Docker 镜像与容器的区别，并说明为什么“镜像应最小化”（体积/安全角度）。',
        points: ['镜像=模板，容器=实例', '最小化减体积/加速分发', '减攻击面（无 shell/包管理器）', '非 root 运行'],
        reference: '镜像是静态模板、容器是其运行实例。镜像最小化（distroless/scratch、多阶段构建）既缩小体积、加速拉取启动，又剔除 shell/包管理器与多余库，显著缩小被攻击面；并以非 root 运行提升安全。' },
      { id: 'opb-w2', q: '什么是 CI/CD？请用一个简化的流水线说明“代码提交到生产发布”的关键环节。',
        points: ['提交触发', 'lint/单测', '构建打包', '部署+自动化测试', '灰度/回滚'],
        reference: 'CI/CD 让交付自动化：提交→代码扫描(lint/SAST)→单元测试→构建制品→部署测试环境→自动化集成测试→人工卡点/灰度→生产发布。关键是快速失败、制品不可变、可灰度可回滚。' },
      { id: 'opb-w3', q: '为什么“备份不等于安全”？请描述一个数据库备份与恢复的基本策略（含恢复演练）。',
        points: ['全量+增量+binlog', '定期恢复演练', '异地/加密', 'RPO/RTO 目标'],
        reference: '备份类型：全量（定期）+ 增量/差异（日常）+ binlog（时间点恢复 PITR）。但备份文件不等于能恢复，必须定期做恢复演练验证可用性；并考虑加密、异地与 RPO/RTO 目标。云 RDS 自动快照也需验证可还原。' }
    ]
  },
  /* ===================== 运维 中级 ===================== */
  {
    id: 'exam-op-inter', name: '运维进阶能力卷 · 中级', track: 'devops', level: '中级', duration: 35, vipOnly: false,
    choices: [
      { id: 'opi-c1', tag: 'K8s', q: 'Kubernetes 中 liveness 与 readiness 探针的区别是？',
        options: ['完全相同', 'liveness 失败重启容器，readiness 失败摘流量不重启', '都重启', '都不生效'], answer: ['B'],
        explain: 'liveness 探测存活，失败重启容器（处理死锁）；readiness 探测就绪，失败从 Service 摘流量但不重启（如依赖未就绪）。' },
      { id: 'opi-c2', tag: '可观测', q: '可观测性“三支柱”是？',
        options: ['日志、指标、链路', 'CPU、内存、磁盘', '前端、后端、数据库', '测试、部署、回滚'], answer: ['A'],
        explain: 'Metrics（指标）/Logs（日志）/Traces（链路）三者互补：指标看趋势、日志看细节、链路看跨服务调用，用 traceId 关联。' },
      { id: 'opi-c3', tag: '发布', q: '金丝雀（Canary）发布的核心是？',
        options: ['一次性全量', '先放少量流量到新版本，按指标逐步放量，异常即回滚', '不做监控', '只用于物理机'], answer: ['B'],
        explain: '金丝雀按可控比例（5%→25%→100%）引流，结合监控（错误率/延迟）自动或手动推进，异常即回滚，把故障面降到最低。' },
      { id: 'opi-c4', tag: '网络', q: '关于 TCP 三次握手，正确的是？',
        options: ['两次即可', 'SYN→SYN/ACK→ACK 建立可靠连接', '不需要确认', '只用于 UDP'], answer: ['B'],
        explain: 'TCP 三次握手（SYN、SYN/ACK、ACK）同步序列号、确认双向可达，建立可靠连接；UDP 无连接不需握手。' },
      { id: 'opi-c5', tag: '排查', q: '磁盘有空间却写入失败，最可能的原因是？',
        options: ['CPU 不足', 'inode 耗尽（大量小文件）', '内存不足', '网络问题'], answer: ['B'],
        explain: '文件系统由数据块与 inode 构成，海量小文件会先耗尽 inode，即使数据块有剩余也无法新建文件；df -i 可确认。' },
      { id: 'opi-c6', tag: 'IaC', q: '关于 Terraform state 与漂移（drift），正确的是？',
        options: ['state 可随意删', 'state 记录真实映射，手动改资源会漂移，用 plan/refresh 检测', 'Terraform 不能检测漂移', 'state 必须本地'], answer: ['B'],
        explain: 'state 是 Terraform 对资源的权威记录；绕过 IaC 手动改资源会产生漂移，plan 能显示差异；应远程后端（带锁）共享 state 并用 plan 周期检测。' },
      { id: 'opi-c7', tag: '镜像', q: '容器镜像最小化（distroless/scratch）的收益是？',
        options: ['更大更全', '减攻击面、缩体积、加速拉取启动', '必须含完整 OS', '只影响构建'], answer: ['B'],
        explain: '最小化镜像只含应用与运行时，剔除 shell/包管理器，缩小体积、加速分发，并显著缩小被攻击面。' },
      { id: 'opi-c8', tag: '缓存', q: '关于 DNS TTL，正确的是？',
        options: ['越大越利于切换', 'TTL 小切换快但查询多；大则减负却拖慢切换', 'DNS 不缓存', 'TTL 无意义'], answer: ['B'],
        explain: 'TTL 决定记录缓存时长：小 TTL 利于快速切流但增查询压力；大 TTL 减负却拖慢故障转移。常用“变更前临时调小 TTL”策略。' },
      { id: 'opi-c9', tag: '负载', q: 'L4 与 L7 负载均衡的区别是？',
        options: ['L4 按 URL 路由', 'L4 基于 IP/端口转发；L7 理解 HTTP，按域名/路径/Header 路由', '一致哈希只 L4', 'L7 不能 SSL 卸载'], answer: ['B'],
        explain: 'L4 按 IP/端口转发、性能好；L7 解析 HTTP，可按域名/路径/Header 分流、做健康检查与 SSL 卸载；一致性哈希用于会话亲和。' },
      { id: 'opi-c10', tag: '密钥', q: '关于 Vault 动态密钥，正确的是？',
        options: ['写死的长期密码', '按需生成带 TTL 的临时凭证，到期自动吊销', '只能管静态 KV', '无法过期'], answer: ['B'],
        explain: 'Vault 动态密钥为应用按需生成短期、带租约的凭证（如 DB 账号），到期自动吊销，缩短暴露面，契合最小权限。' },
      { id: 'opi-c11', tag: 'eBPF', q: 'eBPF 的主要价值是？',
        options: ['只能做网络', '无需改内核即可在内核态安全挂载程序，用于可观测/网络/安全', '必须重编内核', '只跑用户态'], answer: ['B'],
        explain: 'eBPF 经校验后挂载到内核钩子，无需改内核或装模块，广泛用于性能剖析、网络加速（Cilium）、安全观测。' },
      { id: 'opi-c12', tag: 'GitOps', q: 'GitOps 的核心是？',
        options: ['直接 kubectl 改集群', 'Git 为唯一事实源，控制器持续比对并自动收敛集群到声明状态', '不支持回滚', '只适用于无状态'], answer: ['B'],
        explain: 'GitOps 以 Git 为唯一事实源，控制器（Argo CD）周期比对并自动/审批同步（pull），变更经 PR 评审、回滚即回退提交，审计清晰。' }
    ],
    written: [
      { id: 'opi-w1', q: '描述 Kubernetes 中 Pod 的三种探针（liveness/readiness/startup）各自的用途与误用后果。',
        points: ['liveness 失败重启', 'readiness 失败摘流量', 'startup 保护慢启动', '勿混用'],
        reference: 'liveness 探测存活，失败重启容器（处理死锁）；readiness 探测就绪，失败从 Service 摘流量不重启（如依赖未就绪）；startup 保护慢启动应用、期间不触发 liveness。误用：把 readiness 当 liveness 会导致未就绪也被杀；把 liveness 设太严会误杀正常实例。' },
      { id: 'opi-w2', q: '设计一个可观测性体系：指标（Prometheus）、日志（Loki/ELK）、链路（OTel/Jaeger）如何采集、关联与告警，给出关键 SLO 指标。',
        points: ['指标：Exporter+Prometheus', '日志：结构化+Loki', '链路：OTel+traceId', '三支柱用 traceId 关联', 'SLO：可用性/延迟 p99/错误率'],
        reference: '指标用 Prometheus 拉取 Exporter、配 rule 告警；日志结构化为 JSON 经 Loki 索引；链路用 OTel SDK 注入 traceId，并在日志/指标带 traceId 实现三支柱关联。SLO 关注可用性（成功比）、延迟 p99、错误率（5xx）、饱和度，超错误预算触发告警。' },
      { id: 'opi-w3', q: '用 Kubernetes 实现蓝绿或金丝雀发布：说明 Ingress/Service 切换、流量比例控制与基于指标的自动回滚。',
        points: ['蓝绿：切 Ingress/Service', '金丝雀：按比例引流', '指标：错误率/延迟', '自动回滚：Argo Rollouts', '保留回退'],
        reference: '蓝绿：green 就绪后切 Ingress/Service 指向，异常切回。金丝雀：Service Mesh 权重或 Ingress 分片按比例引流（5%→100%）。用 Argo Rollouts 绑定 Prometheus 指标（错误率/延迟），超阈值自动 abort 回滚到稳定版。' }
    ]
  },
  /* ===================== 运维 高级 VIP（进阶） ===================== */
  {
    id: 'exam-op-vip-2', name: '运维架构深挖卷 · 高级 VIP', track: 'devops', level: '高级', duration: 40, vipOnly: false,
    choices: [
      { id: 'opv2-c1', tag: 'K8s', q: 'Pod 长期处于 Pending 最常见原因是？（多选）',
        options: ['节点资源不足以满足 requests/亲和性', 'PVC 无法绑定 PV', '镜像仓库完全正常', 'kubelet 太新'], answer: ['A', 'B'], multi: true,
        explain: 'Pending 多因调度失败：节点资源不足、亲和性/污点不匹配、或依赖的 PVC 无法绑定。需 describe pod 看 Events 定位。' },
      { id: 'opv2-c2', tag: 'etcd', q: '关于 etcd 与 Raft，正确的是？',
        options: ['用单点 MySQL 存元数据', 'etcd 用 Raft 在多节点复制日志，保证控制面一致与高可用', '不需要持久化', 'Raft 只选举不复制'], answer: ['B'],
        explain: 'etcd 是 K8s 可靠存储后端，基于 Raft 在奇数节点复制写日志达成多数派一致，健康直接决定控制面可用性；对磁盘延迟敏感。' },
      { id: 'opv2-c3', tag: 'Mesh', q: 'Istio 如何让 Sidecar 拦截流量？',
        options: ['改业务代码', 'Init 容器用 iptables/IPVS 把进出 Pod 流量重定向到 Envoy', '依赖 DNS 劫持', '需手动配代理'], answer: ['B'],
        explain: '服务网格注入 Init 容器，用 iptables/IPVS 把应用入站/出站流量透明重定向到 Envoy sidecar，实现无侵入治理，业务零改动。' },
      { id: 'opv2-c4', tag: '容量', q: '关于容量规划与压测，正确的是？',
        options: ['只在单机压', '基于 SLA（p99/错误率）逐级压测找拐点，留余量与弹性', '一次性即可', '只看均值'], answer: ['B'],
        explain: '容量规划以 SLA 为目标逐级压测定位吞吐拐点，据此定容量并留 headroom、配 HPA；只看均值会掩盖长尾风险，需复测。' },
      { id: 'opv2-c5', tag: '排障', q: '关于网络排障工具，正确的是？',
        options: ['tcpdump 只抓日志', 'tcpdump 抓包、bpftrace/eBPF 内核态追踪，二者互补', 'bpftrace 无法观测网络', '只看应用日志'], answer: ['B'],
        explain: 'tcpdump 抓包看报文/连接；bpftrace 基于 eBPF 在内核态追踪函数耗时与丢包点，定位应用层看不出的瓶颈，二者互补。' },
      { id: 'opv2-c6', tag: '容灾', q: '多活/容灾架构的核心指标是？',
        options: ['RPO/RTO', '仅 CPU', '仅带宽', '仅成本'], answer: ['A'],
        explain: 'RPO（允许丢多少数据）与 RTO（恢复时长）是容灾设计目标；多活需解决跨地域一致性、全局 ID、故障切流与脑裂防护。' },
      { id: 'opv2-c7', tag: 'GitOps', q: 'GitOps 的回滚方式是？',
        options: ['手动 kubectl 改', '回退 Git 提交，控制器自动收敛', '无法回滚', '重装集群'], answer: ['B'],
        explain: 'GitOps 以 Git 为事实源，回滚即回退提交，控制器自动把集群收敛回稳定状态，审计清晰、可重复。' },
      { id: 'opv2-c8', tag: 'MTTR', q: '降低 MTTR 最有效的组合是？（多选）',
        options: ['完善可观测（指标/日志/链路）', '明确告警与 On-call + 预案与自动恢复', '事故后复盘形成改进项', '关闭监控减噪'], answer: ['A', 'B', 'C'], multi: true,
        explain: '降低 MTTR 靠“快速发现（监控/告警）+ 快速定位（三支柱）+ 快速恢复（预案/自动化）+ 复盘防复发”闭环；堆机器或关监控反而延长故障。' },
      { id: 'opv2-c9', tag: 'TLS', q: 'TLS 1.3 的 0-RTT 风险是？',
        options: ['绝对安全', '复用旧会话密钥首请求即带数据、降延迟但有重放风险', '基于 TCP', '需完整握手'], answer: ['B'],
        explain: 'QUIC/TLS1.3 会话恢复可 0-RTT 带数据降延迟，但 0-RTT 数据可被重放，仅适合幂等请求，需服务端防护。' },
      { id: 'opv2-c10', tag: '链路', q: 'W3C traceparent 的作用是？',
        options: ['只在网关记日志', '跨服务透传 trace/span id 以拼接完整调用链', '只在单进程', 'span 无父子'], answer: ['B'],
        explain: 'traceparent 标准在跨服务调用中透传 trace id 与 parent span id，下游派生子 span，后端按父子还原拓扑与耗时。' },
      { id: 'opv2-c11', tag: '镜像', q: '关于镜像构建缓存，正确的是？',
        options: ['每次全量最优', '把不常变指令（依赖安装）放前、源码放后，利用层缓存加速', '缓存永远新鲜无需失效', '缓存只在本地'], answer: ['B'],
        explain: '合理层缓存（依赖先装、源码后拷）能大幅加速构建；关键是按 lockfile 做缓存 key 并设失效，避免脏缓存导致 CI/本地不一致。' },
      { id: 'opv2-c12', tag: '混沌', q: '混沌工程（Chaos Engineering）的核心做法是？',
        options: ['等故障发生', '主动注入故障（杀节点/断网）在受控环境验证系统韧性', '只靠文档', '关闭监控'], answer: ['B'],
        explain: '混沌工程主动向系统注入故障、验证能否自愈，把“以为能扛”变“验证过能扛”；原则：先建稳态假设、小范围、自动化持续演练。' }
    ],
    written: [
      { id: 'opv2-w1', q: '设计一个高可用 Web 服务架构（多可用区）：含接入层、应用层、数据层与故障转移，说明 RTO/RPO 考量。',
        points: ['接入层：多 AZ LB+健康检查', '应用层：无状态跨 AZ 多副本+HPA', '数据层：主从/多副本跨 AZ', '故障转移自动切流', 'RPO≈0/RTO 秒级'],
        reference: '跨至少 2 个 AZ：接入层多 AZ LB 健康探测与切流；应用层无状态跨 AZ 多副本 + HPA；数据层主从复制（MySQL MGR/Redis 哨兵）跨 AZ，故障自动选主。RPO 靠同步/半同步复制逼近 0，RTO 靠健康探测与自动切流控秒级。' },
      { id: 'opv2-w2', q: '排查一个 OOMKilled 的 Pod：给出从 events、request/limit、内存画像到解决（调优/拆分）的完整思路与命令。',
        points: ['describe 看 OOMKilled', '对比 request/limit', 'memory profile 定位大户', '调大 limit/优化/拆分', '设合理 request'],
        reference: '步骤：kubectl describe pod 看 Events 中 OOMKilled 与退出码 137；kubectl top pod 看实时用量；对比 limit（超则杀）。用 pprof/heap 定位内存大户（缓存/大对象/泄漏）。解决：合理调大 limit 与 request、优化数据结构/及时释放、改全量加载为流式、或拆内存密集型子服务。' },
      { id: 'opv2-w3', q: '写一份 Terraform 模块实现自动扩缩容组：含实例模板、伸缩策略、健康检查与状态管理要点。',
        points: ['launch_template + ASG', 'target tracking 策略', 'ELB+实例健康', '远程后端+锁防漂移', '滚动更新+实例保护'],
        reference: '模块输出：launch_template（镜像/规格/user_data）、autoscaling_group（min/max/desired、subnets、mixed_instances_policy）、scaling_policy（target tracking on CPU 或队列深度）。健康检查用 ELB+实例健康，不健康实例被替换。状态存远程后端（S3+DynamoDB 锁）防并发与漂移；启用实例保护避免缩容杀关键实例。' }
    ]
  }
]

let added = 0
for (const set of newSets) {
  if (s.examSets.find(x => x.id === set.id)) { console.log('skip set(exists):', set.id); continue }
  s.examSets.push(set); added++
}
fs.writeFileSync(SEED, JSON.stringify(s, null, 2) + '\n')
console.log(`BE+OP exam sets: +${added} sets. Total examSets=${s.examSets.length}`)
