// # 内容扩建 D 类（试卷份数+题量+级别）：前端 + AI 轨道
// 每轨道新增 初级(免费) / 中级(免费) / 高级VIP(进阶) 三套，每套 ~12 选择 + 3 笔试。
// 幂等：set id 已存在则跳过；零 schema 漂移。写入 data/seed-content.json 后需跑 _reseed.mjs 落库。
import fs from 'fs'
const SEED = './data/seed-content.json'
const s = JSON.parse(fs.readFileSync(SEED, 'utf-8'))

const newSets = [
  /* ===================== 前端 初级 ===================== */
  {
    id: 'exam-fe-basic', name: '前端入门基础卷 · 初级', track: 'frontend', level: '初级', duration: 25, vipOnly: false,
    choices: [
      { id: 'feb-c1', tag: 'HTML', q: 'HTML 中用于定义页面标题（浏览器标签栏文字）的标签是？',
        options: ['<header>', '<title>', '<head>', '<meta>'], answer: ['B'],
        explain: '<title> 位于 <head> 内，定义浏览器标签页与搜索引擎结果中的标题；<header> 是页面内的页眉区块，<meta> 放元数据。' },
      { id: 'feb-c2', tag: 'CSS', q: '以下哪个 CSS 选择器优先级最高？',
        options: ['元素选择器 div', '类选择器 .box', 'ID 选择器 #main', '通配符 *'], answer: ['C'],
        explain: '优先级大致：ID(100) > 类/属性/伪类(10) > 元素(1) > 通配(0)；ID 选择器权重最高。' },
      { id: 'feb-c3', tag: 'JS', q: 'JavaScript 中 `let` 与 `var` 的主要区别是？',
        options: ['let 可以重复声明', 'let 有块级作用域，var 只有函数作用域', 'var 是 ES6 新增', '二者完全一样'], answer: ['B'],
        explain: 'let/const 为块级作用域且不可重复声明、存在暂时性死区；var 是函数作用域且会变量提升。' },
      { id: 'feb-c4', tag: 'JS', q: '下面哪个方法可以把字符串 "1,2,3" 变成数组 ["1","2","3"]？',
        options: ['"1,2,3".join(",")', '"1,2,3".split(",")', 'JSON.parse("1,2,3")', '"1,2,3".map()'], answer: ['B'],
        explain: 'split(",") 按分隔符拆成数组；join 是数组→字符串，方向相反；map 需先有数组。' },
      { id: 'feb-c5', tag: 'CSS', q: '让一个块级元素水平居中的常用方式是？',
        options: ['text-align:center（对块本身）', 'margin: 0 auto（定宽块）', 'float:center', 'position:middle'], answer: ['B'],
        explain: '定宽块元素用 margin:0 auto 水平居中；text-align:center 只居中行内内容；float 无 center 值。' },
      { id: 'feb-c6', tag: 'HTML', q: '语义化标签 <article> 的作用是？',
        options: ['定义导航', '定义可独立分发的内容块（如文章/帖子）', '定义页脚', '加粗文字'], answer: ['B'],
        explain: 'article 表示独立、可复用内容；nav 是导航、footer 是页脚；语义化利于 SEO 与可访问性。' },
      { id: 'feb-c7', tag: 'JS', q: 'typeof null 的结果是？',
        options: ['"null"', '"object"', '"undefined"', '"number"'], answer: ['B'],
        explain: '这是 JS 历史遗留：typeof null 返回 "object"，需以 === null 显式判断空值。' },
      { id: 'feb-c8', tag: 'CSS', q: 'box-sizing: border-box 的含义是？',
        options: ['width 只包含内容，不含 padding/border', 'width 包含 content+padding+border', '只影响边框颜色', '让盒子变成圆形'], answer: ['B'],
        explain: 'border-box 下设置的 width 已含 padding 与 border，布局更直观；现代项目常全局设为 border-box。' },
      { id: 'feb-c9', tag: 'JS', q: '以下哪组都是 falsy 值？',
        options: ['0, "", null, undefined', '"0", [], {}', '1, "false", true', 'NaN, " ", 100'], answer: ['A'],
        explain: 'JS 中 0、""(空串)、null、undefined、NaN、false 为 falsy；"0" 与 [] 是 truthy。' },
      { id: 'feb-c10', tag: 'HTTP', q: 'HTTP 状态码 404 表示？',
        options: ['服务器内部错误', '请求成功', '资源未找到', '需要身份验证'], answer: ['C'],
        explain: '404 Not Found 表示服务器找不到请求的资源；500 是服务端错误，401 是未授权，200 是成功。' },
      { id: 'feb-c11', tag: 'Git', q: '把本地新提交推送到远程仓库用哪个命令？',
        options: ['git push', 'git pull', 'git clone', 'git fetch'], answer: ['A'],
        explain: 'git push 推本地提交到远程；pull = fetch+merge，clone 首次拉全库，fetch 只取不合并。' },
      { id: 'feb-c12', tag: 'JS', q: 'const 声明的变量，以下说法正确的是？',
        options: ['可以重新赋值', '不能重新赋值，但对象属性可改', '完全不可变（包括属性）', '只能在函数内使用'], answer: ['B'],
        explain: 'const 绑定不可重新赋值，但若指向对象/数组，其属性/元素仍可修改；真正不可变需 Object.freeze 或不可变数据结构。' }
    ],
    written: [
      { id: 'feb-w1', q: '简述一个标准 HTML 页面的基本结构（doctype、head、body 及常用子元素），并说明语义化标签对 SEO 与可访问性的好处。',
        points: ['doctype 声明文档类型', 'head 放 meta/title，body 放内容', '语义标签 article/nav/header/footer', '利于搜索引擎与读屏软件'],
        reference: '标准结构：<!doctype html> 后 <html><head>(meta 编码/viewport、title、link)</head><body>(header/nav/main/article/footer 等语义标签 + script)。语义化让机器理解结构，提升 SEO 与无障碍（读屏按 landmark 导航）。' },
      { id: 'feb-w2', q: '解释 CSS 盒模型（content/padding/border/margin），并说明 border-box 与 content-box 的区别及使用建议。',
        points: ['四层含义', 'content-box: width 仅内容', 'border-box: width 含 padding+border', '建议全局 border-box'],
        reference: '盒模型由内到外：content→padding→border→margin。content-box（默认）下 width 只算内容，加 padding/border 会撑大；border-box 下 width 已含二者，布局更可控。现代项目常 *{box-sizing:border-box}。' },
      { id: 'feb-w3', q: '什么是 JavaScript 的事件冒泡与事件委托？请用原生 JS 写一个在 <ul> 上监听所有 <li> 点击的委托示例。',
        points: ['冒泡：事件由内向外传递', '委托：在父元素统一监听子元素事件', '用 e.target 判断来源', '减少监听器数量'],
        reference: '事件冒泡指触发后从目标元素向上传递到 document。事件委托在父容器监听、用 e.target 判断实际点击的子元素，适合动态列表：ul.addEventListener("click", e=>{ if(e.target.tagName==="LI") handle(e.target) })，避免给每个 li 单独绑监听。' }
    ]
  },
  /* ===================== 前端 中级 ===================== */
  {
    id: 'exam-fe-inter', name: '前端进阶能力卷 · 中级', track: 'frontend', level: '中级', duration: 35, vipOnly: false,
    choices: [
      { id: 'fei-c1', tag: 'Vue', q: 'Vue3 中 ref 与 reactive 的区别，正确的是？',
        options: ['ref 只能包基本类型', 'ref 通过 .value 访问，reactive 直接访问属性；ref 包对象时内部仍用 reactive', 'reactive 可用于原始值', '二者无任何关系'], answer: ['B'],
        explain: 'ref 对任意值包装、用 .value 访问；reactive 只对对象/数组做深层代理。ref 包裹对象时内部也是 reactive。' },
      { id: 'fei-c2', tag: 'React', q: '关于 React 的 useEffect 依赖数组，正确的是？',
        options: ['依赖为空 [] 时每次渲染都执行', '依赖为空 [] 时仅在挂载时执行一次', '不传依赖数组则只在卸载时执行', '依赖数组可随意省略'], answer: ['B'],
        explain: 'useEffect(fn, []) 仅在挂载执行一次、卸载清理一次；不传依赖则每次渲染都执行；依赖要包含 effect 内用到的所有响应式值，否则会读到旧值。' },
      { id: 'fei-c3', tag: 'JS', q: '以下代码输出什么？\n```\nconsole.log(1);\nsetTimeout(()=>console.log(2),0);\nPromise.resolve().then(()=>console.log(3));\nconsole.log(4);\n```',
        options: ['1 2 3 4', '1 4 3 2', '1 4 2 3', '4 1 3 2'], answer: ['B'],
        explain: '同步 1、4 先输出；微任务 Promise.then 早于宏任务 setTimeout，故 3 在 2 前；顺序 1 4 3 2。' },
      { id: 'fei-c4', tag: '性能', q: '关于防抖（debounce）与节流（throttle），正确的是？',
        options: ['防抖是固定频率执行', '防抖在停止触发后等待间隔才执行一次；节流保证间隔内最多执行一次', '节流用于搜索联想输入', '两者完全等价'], answer: ['B'],
        explain: '防抖（输入联想）在最后一次触发后延迟执行；节流（滚动/resize）限制单位时间执行次数。用途不同。' },
      { id: 'fei-c5', tag: '网络', q: 'CORS 预检请求（OPTIONS）会在什么情况下触发？',
        options: ['任何跨域 GET', '使用了自定义请求头或非简单方法/Content-Type', '同源请求', '只在 POST 时'], answer: ['B'],
        explain: '非简单请求（自定义头如 Authorization、Content-Type 为 application/json、PUT/DELETE 等）会先发 OPTIONS 预检，通过后才发真实请求。' },
      { id: 'fei-c6', tag: '构建', q: '关于 tree-shaking，正确的是？',
        options: ['依赖 CommonJS 动态分析', '依赖 ESM 静态结构 + sideEffects 字段，剔除未使用导出', '只对 CSS 生效', '需把所有代码写成 IIFE'], answer: ['B'],
        explain: 'tree-shaking 靠 ESM 静态导入构建依赖图并删除未引用导出；sideEffects:false 告诉打包器可安全删除无副作用模块。' },
      { id: 'fei-c7', tag: 'TS', q: 'TypeScript 中 interface 与 type 的主要区别是？',
        options: ['interface 不能描述函数', 'interface 可被合并声明（declaration merging），type 一般不能', 'type 不支持泛型', '二者完全不能互换'], answer: ['B'],
        explain: 'interface 支持同名声明合并，适合定义对象形状与扩展；type 更灵活（联合/交叉类型），但不能合并。多数对象场景二者可互换。' },
      { id: 'fei-c8', tag: 'CSS', q: '实现垂直水平居中的现代方案（不依赖已知宽高）是？',
        options: ['只用 margin:auto', 'Flex: 容器 display:flex; justify-content/align-items:center', 'position:absolute 无 top/left', 'float + clear'], answer: ['B'],
        explain: 'Flex/Grid 的 place-items/justify+align center 是最常用的不确定尺寸居中方案；绝对定位需配合 transform 平移。' },
      { id: 'fei-c9', tag: 'JS', q: '关于浅拷贝与深拷贝，正确的是？',
        options: ['展开运算符 {...obj} 是深拷贝', 'JSON.parse(JSON.stringify()) 对含函数/循环引用的对象会失败', 'Object.assign 是深拷贝', '浅拷贝会复制嵌套对象本身'], answer: ['B'],
        explain: '展开/Object.assign 是浅拷贝，嵌套对象仍共享引用；JSON 序列化能深拷贝但丢失函数、undefined、循环引用、Date 变字符串。' },
      { id: 'fei-c10', tag: '渲染', q: '关于重排（reflow）与重绘（repaint），正确的是？',
        options: ['改 color 会触发重排', '改 transform 通常只走合成层、不触发重排', '重绘比重排更昂贵', 'display:none 不影响布局'], answer: ['B'],
        explain: '改变几何属性（宽高/位置）触发重排（贵）；改变颜色触发重绘；transform/opacity 走合成层、尽量不触发重排重绘，性能最佳。' },
      { id: 'fei-c11', tag: '存储', q: 'localStorage 与 sessionStorage 的区别是？',
        options: ['两者都在会话结束清除', 'localStorage 持久（同源跨标签页共享），sessionStorage 仅当前标签页', 'sessionStorage 容量更大', 'localStorage 不能存字符串'], answer: ['B'],
        explain: 'localStorage 持久化、同源共享、手动清除；sessionStorage 随标签页关闭清除，各标签独立。均约 5MB、仅字符串。' },
      { id: 'fei-c12', tag: '工程', q: '前端路由的 history 模式与 hash 模式区别是？',
        options: ['hash 模式 URL 更干净', 'history 模式 URL 无 #，但需服务端配置 fallback 避免刷新 404', 'hash 模式不需要任何后端配置', '二者都不能被搜索引擎抓取'], answer: ['B'],
        explain: 'history 模式路径美观（/user/1），但刷新时服务端需返回 index.html 否则 404；hash 模式（/#/user/1）靠前端解析、无需服务端特殊配置。' }
    ],
    written: [
      { id: 'fei-w1', q: '比较 Vue3 的 ref 与 reactive 的适用场景，说明在组合式函数中为何常返回 ref，以及 toRefs 的作用。',
        points: ['ref 通用（含基本类型），reactive 仅对象', '组合式函数返回 ref 保持响应性', '解构 reactive 会丢失响应性', 'toRefs 把响应式对象转为 ref 集合以解构'],
        reference: 'ref 适合任意值与组合式 API 返回值（保持响应性、跨函数传递稳定）；reactive 适合固定对象状态。直接解构 reactive 会丢失响应性，toRefs 将其转为 ref 映射以便安全解构。' },
      { id: 'fei-w2', q: '描述浏览器从输入 URL 到页面渲染完成的关键步骤（DNS、TCP、HTTP、解析、渲染、首屏），并指出哪些环节可用缓存优化。',
        points: ['DNS 解析', 'TCP/TLS 建连', 'HTTP 请求响应', 'HTML 解析+构建 DOM/CSSOM+渲染树', '缓存：DNS/HTTP 强缓存/资源缓存'],
        reference: '流程：URL 解析→DNS 解析（缓存）→TCP 三次握手（HTTPS 加 TLS）→发请求→收响应→解析 HTML 建 DOM、CSSOM→渲染树→布局/绘制→首屏。优化点：DNS 缓存、HTTP 强缓存/协商缓存、CDN、资源预载、关键 CSS 内联。' },
      { id: 'fei-w3', q: '什么是前端水合（hydration）？SSR/SSG 场景下为什么要水合，常见的水合不匹配（hydration mismatch）错误如何排查？',
        points: ['水合=客户端给服务端 HTML 绑事件/恢复状态', 'SSR 提升首屏与 SEO', '不匹配常因服务端/客户端渲染结果不同（日期/随机/undefined）', '用 suppressHydrationWarning 或统一渲染'],
        reference: '水合是客户端拿到 SSR 的 HTML 后，将事件与状态“接上”，使其变可交互。不匹配多因两端 DOM 结构不一致（如渲染了 Date.now()、随机数、未定义值），排查时对比服务端输出与客户端首屏，避免非确定性渲染，必要时用框架提供的抑制警告（不可替代正确修复）。' }
    ]
  },
  /* ===================== 前端 高级 VIP（进阶） ===================== */
  {
    id: 'exam-fe-vip-2', name: '前端架构深挖卷 · 高级 VIP', track: 'frontend', level: '高级', duration: 40, vipOnly: false,
    choices: [
      { id: 'fev2-c1', tag: '性能', q: '关于 Core Web Vitals，INP 替代 FID 的原因是？',
        options: ['FID 已废弃', 'FID 只测首次交互，INP 覆盖全会话交互取最差延迟', 'INP 实现更简单', 'INP 只测滚动'], answer: ['B'],
        explain: 'INP 观测所有交互取最差（近似 p98）延迟，更全面反映真实响应性；FID 仅首次交互、易高估体验。' },
      { id: 'fev2-c2', tag: '框架', q: '关于 React 并发特性（Concurrent）与 useTransition，正确的是？',
        options: ['transition 更新阻塞用户输入', 'useTransition 把非紧急更新标记为可中断，紧急输入优先', '并发渲染会破坏现有数据获取', 'Suspense 不能与流式共存'], answer: ['B'],
        explain: 'startTransition 标记可中断的非紧急更新，React 优先处理输入等紧急更新；Suspense 边界配合流式分块到达，二者可共存。' },
      { id: 'fev2-c3', tag: '工程', q: '关于 Monorepo（如 pnpm workspace / Turborepo），主要收益是？',
        options: ['必须部署到单一服务器', '多包/多应用共享依赖与配置、统一构建缓存与命令编排', '无法做按需发布', '只能用于前端'], answer: ['B'],
        explain: 'Monorepo 让多个包共享依赖、复用配置、用远程缓存加速构建（Turborepo 的 task graph + cache），并统一 lint/test/release 流程。' },
      { id: 'fev2-c4', tag: '安全', q: '防范 XSS 的关键措施包括？（多选）',
        options: ['对用户输入做转义后再插入 DOM', '避免把不可信内容用 v-html/innerHTML 直接渲染', '使用 CSP 限制脚本来源', '把 token 明文写在前端全局变量'], answer: ['A', 'B', 'C'], multi: true,
        explain: 'XSS 防护=输入转义/输出编码+避免危险 API（v-html/innerHTML 渲染不可信内容）+CSP 限制脚本源；token 应存 HttpOnly Cookie 而非全局变量。' },
      { id: 'fev2-c5', tag: '渲染', q: '对比 CSR、SSR、SSG、ISR 的适用场景，正确的是？',
        options: ['SSG 适合高频变化的个性化页', 'SSR 适合需实时数据的页；SSG 适合静态内容；ISR 在 SSG 基础上定时增量再生', 'CSR 首屏最快', 'ISR 只存在于前端框架'], answer: ['B'],
        explain: 'CSR 首屏慢但交互轻；SSR 首屏快、适合动态/个性化；SSG 构建期生成、适合静态；ISR 让 SSG 页面按间隔重新生成，兼顾性能与新鲜度。' },
      { id: 'fev2-c6', tag: '工程', q: '关于前端可访问性（a11y），错误的是？',
        options: ['给图标按钮加 aria-label', '用语义标签替代无意义 div 堆砌', '颜色是唯一的信息传达方式', '表单控件关联 label'], answer: ['C'],
        explain: 'a11y 要求信息不只靠颜色（色盲用户无法区分），需文字/形状辅助；语义标签、aria 属性、label 关联都是基本实践。' },
      { id: 'fev2-c7', tag: '状态', q: '大型应用中状态管理的常见分层是？',
        options: ['只用一个全局 store 即可', '服务端状态（查询缓存）与客户端 UI 状态分离，分别用 React Query/Zustand 等', '所有状态都放 URL', '状态越多越好'], answer: ['B'],
        explain: '现代实践把服务端状态（用 React Query/SWR 做缓存/失效）与客户端 UI 状态（Zustand/Pinia）分离，避免把异步数据混进全局 store 导致复杂度爆炸。' },
      { id: 'fev2-c8', tag: '构建', q: 'Vite 生产构建与开发态的主要区别是？',
        options: ['开发态也做 tree-shaking 与生产一致', '生产构建做压缩/代码分割/ tree-shaking，开发态保留源码与 HMR', '生产构建用 webpack', '二者无任何区别'], answer: ['B'],
        explain: 'Vite 开发态用原生 ESM + esbuild 预构建、保留 HMR；生产构建用 Rollup 做 tree-shaking、压缩、代码分割，产出优化后的静态资源。' },
      { id: 'fev2-c9', tag: '网络', q: 'HTTP/2 多路复用解决了什么？',
        options: ['TCP 层队头阻塞', '应用层队头阻塞（单连接并发多流）', 'DNS 解析慢', '证书签发慢'], answer: ['B'],
        explain: 'HTTP/2 在单 TCP 连接上多路复用流，解决 HTTP/1.1 应用层队头阻塞；TCP 层阻塞需 HTTP/3(QUIC) 解决。' },
      { id: 'fev2-c10', tag: '工程', q: '关于设计系统（Design System）与组件库，价值在于？',
        options: ['让每个页面手写样式', '统一视觉与交互规范、提升一致性与复用、降低协作成本', '增加包体积无收益', '只服务设计师'], answer: ['B'],
        explain: '设计系统把颜色/间距/组件/无障碍规范沉淀为可复用资产，保证跨产品一致性、加速开发、降低维护成本；但需治理避免臃肿。' },
      { id: 'fev2-c11', tag: '测试', q: '前端测试金字塔中，比例通常是？',
        options: ['E2E 最多、单测最少', '单测最多、E2E 最少，集成居中', '只写 E2E', '三者一样多'], answer: ['B'],
        explain: '金字塔：大量快速单测打底，适量集成测，少量昂贵的 E2E 测关键路径；倒金字塔（E2E 过多）会变慢且脆弱。' },
      { id: 'fev2-c12', tag: '架构', q: '微前端要解决的核心问题是？',
        options: ['让单页应用更小', '多团队独立开发部署、技术栈异构、增量升级遗留系统', '取消路由', '提高首屏体积'], answer: ['B'],
        explain: '微前端让不同团队用不同技术栈独立开发/部署子应用、通过运行时集成，适合大型组织与渐进式重构；代价是通信/沙箱/样式隔离复杂度。' }
    ],
    written: [
      { id: 'fev2-w1', q: '设计一个前端性能优化清单：从加载（网络/资源）、渲染（关键路径）、运行时（长任务/内存）三个层面各给 3 条以上可落地措施。',
        points: ['加载：HTTP 缓存/CDN/资源压缩/预载', '渲染：关键 CSS 内联、懒加载、减少重排', '运行时：Web Worker、虚拟列表、防抖节流、内存泄漏排查'],
        reference: '加载层：强缓存+CDN、gzip/brotli、Tree-shaking、preload 关键资源、图片懒加载与合理格式。渲染层：内联关键 CSS、避免长关键路径、用 transform 动画、防布局抖动。运行时：把重计算移 Web Worker、长列表虚拟滚动、防抖节流、用 Performance/内存快照排查泄漏。用 Lighthouse/Web Vitals 量化。' },
      { id: 'fev2-w2', q: '比较 CSR / SSR / SSG / ISR 的架构取舍，并给出一个“内容站 + 个性化推荐”混合场景的技术选型与理由。',
        points: ['内容站用 SSG/ISR', '个性化/实时用 SSR 或客户端拉取', 'ISR 平衡新鲜度与性能', '边界：能静态则静态'],
        reference: '内容主体用 SSG+ISR（快、SEO 好、定时再生保证新鲜）；个性化推荐区块用 SSR 注入或客户端按用户拉取，避免整页变动态。原则是“尽量静态、必要动态”，用边缘缓存与流式进一步提升。' },
      { id: 'fev2-w3', q: '大型前端应用的模块化与依赖治理：如何避免“依赖地狱”与“巨石包”？给出 Monorepo、按需引入、以及对第三方库做体积管控的具体做法。',
        points: ['Monorepo 共享依赖与统一构建缓存', '按需引入（如组件库 babel 插件）防全量打包', '体积预算 + 依赖审计', '定期升级与去重'],
        reference: '用 pnpm workspace/Turborepo 统一依赖与远程构建缓存；对组件库用按需引入（如 unplugin-vue-components）避免全量；设 bundle 体积预算（size-limit）在 CI 拦截膨胀；用 npm audit/dependabot 管安全与升级，定期 dedupe 去重。' }
    ]
  },
  /* ===================== AI 初级 ===================== */
  {
    id: 'exam-ai-basic', name: 'AI 工程入门卷 · 初级', track: 'ai', level: '初级', duration: 25, vipOnly: false,
    choices: [
      { id: 'aib-c1', tag: '概念', q: '“大模型”通常指什么？',
        options: ['只有几层的小模型', '参数规模巨大的深度学习模型（如 Transformer 预训练）', '只能做分类的模型', '传统决策树'], answer: ['B'],
        explain: '大模型（LLM）指基于 Transformer、在海量语料上预训练、参数达十亿至千亿级的模型，具备通用语言理解与生成能力。' },
      { id: 'aib-c2', tag: '提示', q: '提示工程（Prompt Engineering）的目的是？',
        options: ['训练模型权重', '通过精心设计输入引导模型稳定产出期望结果', '清理训练数据', '部署模型'], answer: ['B'],
        explain: '提示工程在不微调的前提下，用清晰指令/示例/格式约束引导模型输出，是 LLM 应用的第一道工程关。' },
      { id: 'aib-c3', tag: 'Token', q: '关于 Token，正确的是？',
        options: ['Token 是模型的最终答案', 'Token 是模型处理文本的最小单位，输入与输出都按 token 计费', '一个汉字恰好等于一个 token', 'Token 与计费无关'], answer: ['B'],
        explain: 'Token 是分词后的最小单元，中英文混合下并不严格一一对应；LLM 按输入+输出 token 计费，长上下文更贵。' },
      { id: 'aib-c4', tag: 'RAG', q: 'RAG（检索增强生成）解决的核心问题是？',
        options: ['让模型跑得更快', '给模型注入外部/私域知识并降低幻觉、支持溯源', '替代所有微调', '压缩模型体积'], answer: ['B'],
        explain: 'RAG 在生成前检索相关片段拼入上下文，让模型基于证据作答，缓解训练数据陈旧/私域知识缺失导致的幻觉，并支持引用。' },
      { id: 'aib-c5', tag: '采样', q: 'Temperature 参数调高会带来？',
        options: ['输出更确定、保守', '输出更随机、发散、有创意', '不影响输出', '只影响速度'], answer: ['B'],
        explain: 'Temperature 高→采样更随机发散（创意强但可能不稳）；低→更确定保守；代码/事实类常用低温。' },
      { id: 'aib-c6', tag: '工具', q: 'Function Calling（工具调用）让模型能做什么？',
        options: ['直接执行代码', '输出“调用哪个函数+参数”的结构化结果，由外部代码执行', '自动训练', '删除数据库'], answer: ['B'],
        explain: '模型不真执行，而是生成工具调用的结构化描述（name+参数），由你的程序执行真实动作（查 API/查库）并把结果回灌模型。' },
      { id: 'aib-c7', tag: '安全', q: '提示注入（Prompt Injection）是指？',
        options: ['用户输入太长', '不可信内容夹带指令劫持模型行为', '模型内存不足', '网络延迟'], answer: ['B'],
        explain: '提示注入通过用户输入或检索内容夹带恶意指令，使模型忽略原系统指令、执行非预期行为，是 LLM 首要安全风险。' },
      { id: 'aib-c8', tag: '评估', q: 'Faithfulness（忠实度）衡量的是？',
        options: ['答案是否流畅', '答案是否完全由检索上下文支撑、无臆造', '答案长度', '检索速度'], answer: ['B'],
        explain: 'Faithfulness 衡量生成答案是否被检索上下文支撑、未凭空捏造，是 RAG 质量的核心指标。' },
      { id: 'aib-c9', tag: 'Embedding', q: '文本向量（Embedding）的作用是？',
        options: ['压缩图片', '把文本映射为语义向量，相似文本在向量空间接近', '加密文本', '统计词频'], answer: ['B'],
        explain: 'Embedding 将语义编码进向量，语义相近者距离近，可用于检索/聚类/去重；是 RAG 与推荐的基础。' },
      { id: 'aib-c10', tag: '架构', q: 'Agent（智能体）相比单次问答，多了什么能力？',
        options: ['什么都没多', '能自主规划、调用工具、观察结果并迭代达成目标', '只能回答固定问题', '不能调用工具'], answer: ['B'],
        explain: 'Agent 通过“思考-行动-观察”循环自主拆解任务、调用工具、迭代直到完成，而不只是单次问答。' },
      { id: 'aib-c11', tag: '成本', q: '降低 LLM 调用成本的有效手段不包括？',
        options: ['语义缓存命中相似问题', '模型路由（简单问题走小模型）', 'Prompt Caching 复用稳定前缀', '对每一个简单分类都调用最大模型'], answer: ['D'],
        explain: '降本常用缓存、路由、Prompt Caching、收紧输出长度；盲目全用最大模型反而最贵。' },
      { id: 'aib-c12', tag: '合规', q: '企业落地 LLM 时，以下正确的是？',
        options: ['所有数据都可无差别发往第三方', 'PII 应脱敏或不出域，敏感场景走私有化/合规通道', '无需告知用户在使用 AI', '不需要审计日志'], answer: ['B'],
        explain: '企业需数据分级：PII 脱敏/不出域，敏感场景私有化或合规 API，配审计与告知义务，合规是跨行业普适要求。' }
    ],
    written: [
      { id: 'aib-w1', q: '用你自己的话解释 LLM、Prompt、RAG、Agent 四个概念及其关系，并各举一个日常应用例子。',
        points: ['LLM=通用语言模型', 'Prompt=引导模型的输入', 'RAG=检索增强', 'Agent=自主调用工具的循环'],
        reference: 'LLM 是底层能力（如写文案）；Prompt 是把任务说清的输入（如“用正式语气写周报”）；RAG 是给 LLM 外挂知识库（如企业 FAQ 问答）；Agent 让 LLM 自动查天气+写日程。关系是：LLM 为基，Prompt 调度，RAG 补知识，Agent 扩能力。' },
      { id: 'aib-w2', q: '什么是 Token？为什么它和成本、上下文长度直接相关？请举例说明一次对话的 token 开销如何估算。',
        points: ['最小处理单位', '输入+输出都计费', '长上下文更贵', '可粗略按字符估算'],
        reference: 'Token 是分词单元，中英文混合约 1-2 字/token。成本=输入 tokens×输入单价 + 输出 tokens×输出单价；一次对话开销≈问题 token + 回答 token。估算：300 字问题+500 字回答≈800-1000 token，乘单价即得单次成本，再×日调用量得预算。' },
      { id: 'aib-w3', q: '为什么 RAG 能降低幻觉？请用“开卷考试”的类比说明其数据流，并点出两个常见失败点。',
        points: ['外挂知识=开卷', '检索→拼提示→生成', '失败点：检索不相关', '失败点：生成不引用'],
        reference: 'RAG 像开卷考试：先翻资料（检索）再作答（生成），答案有据可依、可溯源，从而降低凭空编造。常见失败：①检索回相关度低的片段，答案无依据；②提示未要求“仅基于片段”，模型仍幻觉。需评测 Faithfulness。' }
    ]
  },
  /* ===================== AI 中级 ===================== */
  {
    id: 'exam-ai-inter', name: 'AI 工程实战卷 · 中级', track: 'ai', level: '中级', duration: 35, vipOnly: false,
    choices: [
      { id: 'aii-c1', tag: 'RAG', q: '关于文档切分（chunking），正确的是？',
        options: ['chunk 越大越好', '需在检索精度与上下文完整间权衡，重叠可保留边界语义', '只能用固定字符数', '切分不影响检索'], answer: ['B'],
        explain: '过小丢失上下文、过大稀释相关性；结构感知切分+overlap 优于纯字符切；检索后常配 rerank 提升相关性。' },
      { id: 'aii-c2', tag: '检索', q: '混合检索（Hybrid）通常结合？',
        options: ['只向量', 'BM25 关键词 + 向量语义，融合后重排', '只规则', '随机'], answer: ['B'],
        explain: '混合检索用 BM25（精确术语）+ 向量（语义近义）互补，常以 RRF 融合再用 cross-encoder rerank，提升真实召回。' },
      { id: 'aii-c3', tag: 'Agent', q: 'ReAct 范式的核心循环是？',
        options: ['只思考不行动', '思考→行动→观察 交替直到完成', '只调用一次工具', '随机循环'], answer: ['B'],
        explain: 'ReAct 交替进行 Reasoning（思考）与 Acting（调工具），把 Observation 回灌再思考，形成“想-做-看”循环直至任务完成。' },
      { id: 'aii-c4', tag: '评估', q: 'LLM-as-judge 的主要偏差不包括？',
        options: ['位置偏好', '长度偏好', '自我偏好', '完全客观无偏'], answer: ['D'],
        explain: 'LLM 裁判存在位置（偏好前者）、长度（偏好更长）、自我（偏好相似风格）等偏差，需人工黄金集校准，不能完全替代人。' },
      { id: 'aii-c5', tag: '向量库', q: 'HNSW 与 IVF 的区别是？',
        options: ['都精确无近似', 'HNSW 基于图、快且准但吃内存；IVF 基于聚类、省内存需调 nprobe', 'IVF 无法大规模', 'HNSW 不占内存'], answer: ['B'],
        explain: 'HNSW 图索引查询快召回高但常驻内存；IVF 倒排聚类内存友好、靠 nprobe 权衡召回与速度。选型看规模与延迟。' },
      { id: 'aii-c6', tag: '安全', q: '防御系统提示提取的措施是？',
        options: ['把系统提示写前端', '指令与不可信输入隔离、对越权索取明确拒绝、出口检测泄露', '允许模型复述指令', '无需防护'], answer: ['B'],
        explain: '系统提示本不应含机密；防护靠分层隔离、最小权限、对越权索取拒绝、出口做泄露检测。' },
      { id: 'aii-c7', tag: '成本', q: 'Prompt Caching 的作用是？',
        options: ['重新计算每次前缀', '对稳定前缀缓存 KV，命中后省预填充、降延迟与成本', '只缓存输出', '增加首字延迟'], answer: ['B'],
        explain: 'Prompt Caching 对稳定前缀（系统提示/知识库）缓存注意力 KV，后续请求命中后跳过预填充，显著降低输入成本与 TTFT。' },
      { id: 'aii-c8', tag: '延迟', q: '流式输出（Streaming）的主要价值是？',
        options: ['等全部生成再返回', '逐 token 推送，首字即显、体感更快', '增加服务器负担无意义', '只用于文件'], answer: ['B'],
        explain: '流式（SSE/WebSocket）让首个 token 尽快到达，用户边生成边看，大幅改善体感延迟；TTFT 主要受输入预填充影响。' },
      { id: 'aii-c9', tag: '工具', q: '设计可靠 Agent 时，必须包含？（多选）',
        options: ['步数/预算上限防失控', '单工具超时与有限重试', '错误隔离不拖垮整体', '无限循环允许自由发挥'], answer: ['A', 'B', 'C'], multi: true,
        explain: '可靠 Agent 需步数/预算上限、单调用超时+重试、错误隔离与兜底、高风险动作人工确认；无限循环会导致成本与失败失控。' },
      { id: 'aii-c10', tag: '观测', q: 'LLM 应用可观测应追踪的指标包括？',
        options: ['只 CPU', 'token 成本、TTFT/TPOT 延迟、错误率、缓存命中率、按场景归因', '只数据库 QPS', '只前端 FPS'], answer: ['B'],
        explain: '需覆盖成本（token/单价）、延迟（TTFT 首字、TPOT 逐字）、质量（评分/回归）、缓存命中与失败率，并支持按租户下钻定位贵/慢/错。' },
      { id: 'aii-c11', tag: '量化', q: '4-bit 量化模型的主要目的是？',
        options: ['提升精度', '减小体积、降显存与推理成本，使其能在更便宜硬件运行', '加快训练', '增加参数'], answer: ['B'],
        explain: '量化把权重从高精度降到 INT4，显著降显存/提速，便于消费级硬件部署；但需校准并评测质量以防退化。' },
      { id: 'aii-c12', tag: '架构', q: '多智能体（Multi-Agent）的常见模式是？',
        options: ['只能单 Agent', 'supervisor 调度子 Agent 或辩论/评审协作，需设终止条件', 'Agent 间不能通信', '多 Agent 必更差'], answer: ['B'],
        explain: '多 Agent 通过角色分工（规划/检索/编码/评审）提升复杂任务质量；supervisor 派发汇总，辩论相互校验；需设收敛条件防开销爆炸。' }
    ],
    written: [
      { id: 'aii-w1', q: '设计一个生产级 RAG 流水线：覆盖切分、向量化、检索+重排、生成与引用，并定义 Faithfulness/Answer Relevance 的回归方法。',
        points: ['结构感知切分+overlap', '向量化入库+元数据', '混合检索+rerank', '生成带引用、约束不臆造', '用黄金集评 Faithfulness/相关'],
        reference: '流水线：①结构感知切分→选 embedding 批量入库（带元数据）。②检索：向量 Top-K + 元数据过滤，混合 BM25。③rerank：cross-encoder 取 Top-3。④生成：片段带引用、要求不超上下文臆造。⑤评估：LLM-judge 算 Faithfulness/Answer Relevance，每次变更跑黄金集回归。' },
      { id: 'aii-w2', q: '实现一个带工具调用的 Agent 循环（伪代码）：含规划、并行/串行工具执行、超时重试、步数上限与最终综合，说明如何防失控。',
        points: ['循环：思考→调用→观察', '并行无依赖调用', '超时/重试/隔离', '步数+预算上限', '最终由模型综合'],
        reference: 'for step in MAX: plan=llm(history); if done break; calls=plan.tool_calls; res=parallel(calls, timeout, retries); for r in res: if err: r=fallback or mark; history+=obs; if budget exceeded break; final=llm(history+“综合”)。防失控=步数上限+token 预算+单工具超时；防单点失败=错误隔离。' },
      { id: 'aii-w3', q: '构建 LLM 评测体系：定义质量/成本/延迟/安全四类指标，说明黄金集与回归流程，以及校准 LLM-as-judge 偏差的方法。',
        points: ['四维指标', '黄金集覆盖典型与边界', '每次变更跑回归对比基线', '人工抽检+多裁判校准'],
        reference: '四维：质量（Faithfulness/相关性/人工）、成本（token/单价）、延迟（TTFT/TPOT/p99）、安全（拒答率/注入防御率）。黄金集附标准答案，CI 中跑回归与基线 diff 报警。校准 judge：定期人工抽检、多模型交叉、统计位置/长度/自我偏好并修正判分 prompt。' }
    ]
  },
  /* ===================== AI 高级 VIP（进阶） ===================== */
  {
    id: 'exam-ai-vip-2', name: 'AI 工程高阶架构卷 · 高级 VIP', track: 'ai', level: '高级', duration: 40, vipOnly: false,
    choices: [
      { id: 'aiv2-c1', tag: '推理优化', q: 'vLLM 等推理框架的核心优化是？',
        options: ['串行逐请求', 'continuous batching + PagedAttention 提升 GPU 利用率与吞吐', '关闭所有批处理', '只做模型压缩'], answer: ['B'],
        explain: 'continuous batching 把不同请求步拼批、PagedAttention 分页管理 KV 显存，显著提升吞吐、压低单请求成本。' },
      { id: 'aiv2-c2', tag: 'KV缓存', q: '关于 KV Cache 与 Prompt Caching，正确的是？',
        options: ['每次都从零计算 KV', 'KV 缓存已算的注意力键值，多轮复用前缀省重算；Prompt Caching 即持久化该缓存', 'KV 只存磁盘', '与上下文无关'], answer: ['B'],
        explain: '自回归生成缓存历史 K/V 避免重算，显存随上下文线性增长；Prompt Caching 是对稳定前缀 KV 的持久化复用，降输入成本与 TTFT。' },
      { id: 'aiv2-c3', tag: '蒸馏', q: '模型蒸馏（Distillation）的核心是？',
        options: ['把大模型删掉', '用教师模型输出/软标签训练学生，在变小前提下保留能力', '只做量化', '增加训练数据'], answer: ['B'],
        explain: '蒸馏让学生（小模型）从教师（大模型）的软标签/特征中学习，变小且快、可端侧部署，能力上限受教师约束。' },
      { id: 'aiv2-c4', tag: '路由', q: '模型路由（Model Routing）的价值是？',
        options: ['所有请求都走最大模型', '按难度把简单请求路由到小/便宜模型，难请求才上大模型，降本降延迟', '只用一个模型', '增加延迟'], answer: ['B'],
        explain: '路由在不明显损质量下大幅降本：简单分类/抽取走小模型，推理/创作走大模型；常用 LiteLLM 等网关统一路由与故障转移。' },
      { id: 'aiv2-c5', tag: '安全', q: 'OWASP LLM Top10 中排首位的风险是？',
        options: ['训练数据不足', '提示注入（Prompt Injection）', '模型太大', '延迟过高'], answer: ['B'],
        explain: 'OWASP 将提示注入（LLM01）列为首要风险；间接注入（经检索内容）尤其隐蔽，需指令与不可信内容隔离、最小权限与出口护栏。' },
      { id: 'aiv2-c6', tag: '评估', q: '关于“lost in the middle”现象，正确的是？',
        options: ['模型对任意位置利用率一致', '长上下文首尾利用更好、中间易被忽略，故关键指令放首尾、长文宜检索分段', '只要够长就无需检索', '只在小模型出现'], answer: ['B'],
        explain: '研究表明模型对长上下文中段信息利用率偏低；实务上把系统指令置首尾、用检索把最相关片段带入，比盲目拉长上下文更有效。' },
      { id: 'aiv2-c7', tag: '护栏', q: '输出护栏（Guardrails）应包含？（多选）',
        options: ['结构化 schema 校验', 'PII 过滤与敏感词检测', '越权请求拒答', '无校验直接返回'], answer: ['A', 'B', 'C'], multi: true,
        explain: '护栏=结构化校验（JSON/Pydantic）+ 内容安全（moderation）+ PII 脱敏 + 越权拒答 + 失败重试/降级；不能只靠提示约束。' },
      { id: 'aiv2-c8', tag: '成本', q: '语义缓存（Semantic Cache）的要点是？',
        options: ['只缓存完全相同的问题', '对相似问题（不同措辞同义）向量比对命中则免推理，需调阈值并排除敏感/时效', '缓存一定会误命中', '只用于图片'], answer: ['B'],
        explain: '语义缓存把相似问题映射到同一答案省推理；阈值太松误命中、太紧无效；敏感/时效问题不缓存；可叠加普通 KV 缓存。' },
      { id: 'aiv2-c9', tag: '可观测', q: 'OpenTelemetry 对 LLM 的可观测贡献是？',
        options: ['只做日志', '标准化 gen_ai.* 语义约定，统一埋点 prompt/延迟/token/工具调用', '只监控 CPU', '与 LLM 无关'], answer: ['B'],
        explain: 'OTel 已扩展 LLM 语义约定（gen_ai.*），让不同框架/厂商的 token、延迟、工具调用埋点标准化，便于统一追踪与跨语言互通。' },
      { id: 'aiv2-c10', tag: '架构', q: '构建多模型网关（统一接入多家 LLM）的能力包括？',
        options: ['只接一家', '统一 API、模型路由、故障转移、限流配额、密钥托管、用量审计', '不做任何治理', '每家用不同代码硬写'], answer: ['B'],
        explain: '网关屏蔽厂商差异，提供路由/ fallback/限流/密钥托管/审计/缓存，避免供应商锁定、便于 A/B 与成本护栏（如 LiteLLM）。' },
      { id: 'aiv2-c11', tag: '微调', q: '关于 RAG 与微调的取舍，正确的是？',
        options: ['RAG 永远优于微调', 'RAG 适合易变/私域事实且可溯源；微调适合固化风格/格式/能力，二者可组合', '微调适合注入最新新闻', 'RAG 无法结合模型能力'], answer: ['B'],
        explain: 'RAG 外挂知识、适合变化事实且可溯源；微调改权重、适合稳定风格/格式/难例能力但知识会过时；生产常以 RAG 为主、微调为辅。' },
      { id: 'aiv2-c12', tag: '合规', q: '企业落地 LLM 的合规与隐私要点是？',
        options: ['数据无差别出网', 'PII 脱敏/不出域、敏感走私有化或合规通道、建审计与告知义务', '无需审计', '不告知用户'], answer: ['B'],
        explain: '需数据分级：PII 脱敏或留私有环境，敏感场景私有化/合规 API，配审计日志与越权拒绝，并向用户尽 AI 使用告知义务。' }
    ],
    written: [
      { id: 'aiv2-w1', q: '设计一套大模型推理服务优化方案：从 continuous batching、PagedAttention、量化、到 Prompt Caching 与流式，说明每项对吞吐/成本/延迟的影响。',
        points: ['continuous batching 提 GPU 利用率', 'PagedAttention 省 KV 显存碎片', '量化降显存/提速', 'Prompt Caching 降输入成本+TTFT', '流式降体感延迟'],
        reference: '吞吐：continuous batching 拼批 + PagedAttention 高效管 KV，GPU 利用率↑、单请求成本↓。成本：量化（INT8/4）+ Prompt Caching 复用稳定前缀↓输入计费。延迟：Prompt Caching 省预填充降 TTFT，流式让首字即达改善体感。综合形成“高吞吐+低成本+低延迟”的推理服务。' },
      { id: 'aiv2-w2', q: '设计一个企业级 LLM 安全护栏体系：覆盖入口（注入/越权）、模型层（最小权限）、出口（PII/泄露/拒答），并说明纵深防御与可观测。',
        points: ['入口：注入检测+不可信隔离', '模型层：最小权限指令', '出口：PII 脱敏+泄露检测+拒答', '可观测：记录拦截与降级'],
        reference: '纵深：①入口对用户输入做分类与注入检测，与系统指令用清晰分隔符隔离。②模型层最小权限、禁止复述系统提示。③出口对生成做 PII 脱敏（正则/NER）、敏感/提示泄露检测、越权拒答。④可观测记录拦截率与误杀，持续调阈值。任何一层命中即拦截或降级。' },
      { id: 'aiv2-w3', q: '给出一个“LLM 应用成本-质量联合优化”的治理框架：模型路由、语义缓存、批量、输出约束、评测回归如何协同，并定义关键看板指标。',
        points: ['路由用小模型扛量', '语义缓存免重复推理', '批量走折扣', '约束输出长度', '看板：成本/质量/延迟'],
        reference: '治理：路由把简单任务给小模型、难任务给大模型；语义缓存命中相似问题免调用；非实时任务 batch 异步享折扣；约束 max_tokens/JSON 减冗余。评测回归保证“降本不降质”。看板指标：单次成本、P95 延迟、Faithfulness、缓存命中率、各模型流量占比，据此持续优化路由与缓存阈值。' }
    ]
  }
]

let added = 0
for (const set of newSets) {
  if (s.examSets.find(x => x.id === set.id)) { console.log('skip set(exists):', set.id); continue }
  s.examSets.push(set); added++
}
fs.writeFileSync(SEED, JSON.stringify(s, null, 2) + '\n')
console.log(`FE+AI exam sets: +${added} sets. Total examSets=${s.examSets.length}`)
