// #50 VIP 内容池：① 修复现有 3 套试卷 choice/written id 非全局唯一的根因
// （exam_choices.id / exam_written.id 是 PRIMARY KEY，_reseed 用 INSERT OR IGNORE
//  导致后两套题被静默丢弃）；② 追加 4 套高阶考卷（前端/后端/运维/AI）。
// 幂等：已命名空间化的 id 跳过；已存在的套跳过。零 schema 漂移。
//
// 【2026-08-02 决策：延迟支付集成】用户决定先全站免费、后续再集成 VIP 收费。
// 故以下 4 套高阶卷 vipOnly 统一置 false（与 seed-content.json 保持一致），
// 重灌后全部可免费作答；支付/订单/webhook 代码暂不接入。待收费模式落地时，
// 再把此处与 seed 的 vipOnly 翻回 true 并打通付费解锁链路。
import fs from 'fs'

const SEED = './data/seed-content.json'
const s = JSON.parse(fs.readFileSync(SEED, 'utf-8'))

// ── 步骤 1：把现有 choice/written id 改为「按 set 命名空间」的全局唯一 ──
let fixedChoices = 0, fixedWritten = 0
s.examSets.forEach((st) => {
  const p = st.id // 如 exam-fe-1
  st.choices.forEach((c, i) => {
    if (!c.id.startsWith(p + '-')) { c.id = `${p}-c${i + 1}`; fixedChoices++ }
  })
  st.written.forEach((w, i) => {
    if (!w.id.startsWith(p + '-')) { w.id = `${p}-w${i + 1}`; fixedWritten++ }
  })
})

// ── 步骤 2：定义 4 套 VIP 卷 ──
const vipSets = [
  {
    id: 'exam-fe-vip-1', name: '前端高阶实战卷 · VIP', track: 'frontend', level: '高级', duration: 40, vipOnly: false,
    choices: [
      { id: 'fev1-c1', tag: 'TypeScript', q: '关于 TypeScript 中 unknown 与 any 的区别，正确的是？',
        options: ['any 和 unknown 都允许赋任意值，且都不需类型收窄', 'unknown 赋给具体类型时不需要类型守卫，any 需要', 'unknown 赋给具体类型前必须做类型收窄（类型守卫），any 则不需要', '两者在类型系统里完全等价，只是命名不同'],
        answer: ['C'], explain: 'unknown 是类型安全的 top type：把它赋给 number/string 等具体类型前必须先用 typeof/instanceof 等收窄；any 则跳过所有检查。用 unknown 替代 any 可保留安全性。' },
      { id: 'fev1-c2', tag: 'Vue', q: '关于 Vue3 响应式，下列说法正确的是？',
        options: ['reactive 默认是深层响应式的，嵌套对象属性变化也会触发更新', 'ref 只能包裹基本类型，包裹对象时不会深层代理', '将响应式对象解构到局部变量后，这些变量仍保持响应性', 'shallowRef 与 ref 行为完全一致'],
        answer: ['A'], explain: 'reactive 基于 Proxy 默认深层代理，嵌套属性变更可触发更新；ref 包裹对象时内部仍用 reactive 做深层代理；解构 reactive 会丢失响应性（需用 toRefs）；shallowRef 仅跟踪 .value 本身替换、不深层。' },
      { id: 'fev1-c3', tag: 'React', q: '关于 React 的 startTransition / useTransition，下列说法正确的是？',
        options: ['被 startTransition 包裹的更新会阻塞用户输入', 'startTransition 用于把非紧急更新标记为非阻塞，紧急更新（如输入）优先渲染', 'useTransition 返回的 isPending 表示组件是否正在挂载', 'transition 更新比普通 setState 优先级更高'],
        answer: ['B'], explain: 'startTransition 把更新标记为可中断的非紧急更新，React 会优先处理用户输入等紧急更新，再在空闲时处理 transition，从而保持响应；isPending 表示该 transition 是否进行中。' },
      { id: 'fev1-c4', tag: '性能', q: '以下哪些情况会贡献 CLS（累积布局偏移）？（多选）',
        options: ['为图片/视频显式设置 width 与 height（或 aspect-ratio）', '异步加载的字体导致文本重排', '在已有内容上方插入广告/图片而未预留占位空间', '使用 CSS transform 做位移动画'],
        answer: ['B', 'C'], multi: true, explain: 'CLS 衡量可见元素的意外位移。未预留空间的插入、字体 swap 导致的文本尺寸变化都会造成偏移；显式尺寸/aspect-ratio 反而防止偏移；transform 走合成层、不改变布局，不计入 CLS。' },
      { id: 'fev1-c5', tag: '模块化', q: '关于 ES Module 的 import，下列说法正确的是？',
        options: ['import 是静态的，会被提升到模块顶部，且只能在顶层使用', 'import 可以在函数内部按需动态调用', 'ESM 与 CommonJS 的 require 在循环依赖处理上行为完全一致', 'ESM 默认是运行时动态解析'],
        answer: ['A'], explain: 'ESM 的 import/export 是静态语法，必须位于模块顶层、编译期确定依赖图，便于 tree-shaking；动态导入需用 import() 函数。CommonJS 是运行时求值，循环依赖语义不同。' },
      { id: 'fev1-c6', tag: 'WebAssembly', q: '关于 WebAssembly 的线性内存模型，下列说法正确的是？',
        options: ['WASM 实例直接读写宿主的任意内存地址', 'WASM 拥有独立的线性内存（ArrayBuffer），通过内存导出/导入与 JS 按字节共享', 'WASM 没有内存概念，所有数据通过 DOM 传递', 'WASM 内存大小在实例化后无法增长'],
        answer: ['B'], explain: 'WASM 使用连续的线性内存（类似 typed array 背后的 ArrayBuffer），由模块声明初始/最大页（每页 64KiB），可通过 memory.grow 增长；JS 与 WASM 通过这份共享缓冲区按偏移读写，存在边界检查。' },
      { id: 'fev1-c7', tag: 'CSS', q: 'CSS 选择器 :has() 的主要用途是？',
        options: ['选择自身包含特定子元素的父元素（父选择器能力）', '选择元素的第一个子元素', '选择所有被 hover 的元素', '仅用于匹配伪类状态'],
        answer: ['A'], explain: ':has() 是关系型选择器，允许根据后代/兄弟元素的状态选择祖先（例如 a:has(img) 选中含图片的链接、form:has(:invalid) 校验整表单），补齐了此前缺失的父选择器能力。' },
      { id: 'fev1-c8', tag: '存储', q: '关于浏览器存储，下列说法正确的是？',
        options: ['localStorage 是异步的，IndexedDB 是同步的', 'IndexedDB 是异步的事务型数据库，容量远大于 localStorage（通常数百 MB 起）', 'localStorage 可存储结构化对象而无需序列化', '两者都会在隐私模式下被同源策略禁止写入'],
        answer: ['B'], explain: 'localStorage 是同步的键值存储、约 5MB、仅字符串；IndexedDB 是异步事务型、支持索引与结构化克隆、容量大得多，适合离线数据与大量结构化数据。' },
      { id: 'fev1-c9', tag: 'CORS', q: '以下哪些情况会触发浏览器对跨域请求的 CORS 预检（OPTIONS）？（多选）',
        options: ['使用 GET 且不加自定义请求头', 'Content-Type 为 application/json 发送 POST', '请求携带 Authorization 自定义头', '使用简单方法 GET 且 Content-Type 为 text/plain'],
        answer: ['B', 'C'], multi: true, explain: '预检在「非简单请求」时触发：方法非 GET/HEAD/POST，或 POST 但 Content-Type 非 application/x-www-form-urlencoded、multipart/form-data、text/plain，或带自定义头（如 Authorization）。简单请求直接发、靠响应头授权。' },
      { id: 'fev1-c10', tag: '事件循环', q: '以下关于微任务（microtask）的理解，正确的是？',
        options: ['setTimeout 回调先于 Promise.then 执行', '微任务队列会在每个宏任务结束后、渲染前被清空', 'queueMicrotask 与 Promise.then 不属于同一队列，优先级不同', '微任务不会阻塞渲染，因此可被无限循环而不影响页面'],
        answer: ['B'], explain: '每轮事件循环：执行一个宏任务 → 清空整个微任务队列（含其中新产生的微任务）→ 才进入渲染/下一宏任务。Promise.then 与 queueMicrotask 同属微任务；微任务若无限递归会饿死渲染（页面卡死）。' },
      { id: 'fev1-c11', tag: 'SSR', q: '关于流式 SSR（Streaming SSR），下列说法正确的是？',
        options: ['流式 SSR 必须等全部数据就绪后才向客户端发送首字节', '流式 SSR 允许把已就绪的 HTML 分块发送，配合 Suspense 提升首屏感知速度', '流式 SSR 与客户端 hydration 无法共存', '流式只适用于静态站点生成（SSG）'],
        answer: ['B'], explain: '流式渲染（如 React renderToPipeableStream、Vue renderToStream）可先发 shell 与已就绪区块，Suspense 边界内的慢数据稍后到达，减少 TTFB 与 FCP；客户端仍做 hydration 接管。' },
      { id: 'fev1-c12', tag: 'Web Vitals', q: 'Core Web Vitals 用 INP 取代 FID，主要原因是？',
        options: ['FID 只测量首次交互的延迟，忽略后续大量交互的响应质量', 'INP 实现成本更低', 'FID 已被浏览器废弃不再支持', 'INP 只统计滚动性能'],
        answer: ['A'], explain: 'FID 仅捕获首次交互的输入延迟，无法反映用户在整个会话中点击、输入的真实卡顿；INP 观察全部交互、取最差（或近似 p98）的交互延迟，更全面衡量响应性。' },
      { id: 'fev1-c13', tag: '安全', q: 'Subresource Integrity（SRI）的作用是？',
        options: ['加密传输静态资源', '通过 integrity 属性携带资源哈希，浏览器校验下载内容未被篡改', '加速 CDN 回源', '防止 XSS 注入'],
        answer: ['B'], explain: 'SRI 在 script/link 上用 integrity=sha384-... 声明资源期望哈希，浏览器下载后校验，若不一致则拒绝执行，防御 CDN 被劫持或资源被篡改；与加密传输（HTTPS）职责不同。' },
      { id: 'fev1-c14', tag: '构建', q: '关于 tree-shaking（摇树优化），下列说法正确的是？',
        options: ['tree-shaking 依赖 ES Module 的静态结构，并受 package.json 的 sideEffects 字段影响', 'CommonJS 模块也能被打包器完美 tree-shake', '只要代码写完，打包器就一定能删除所有未使用导出', 'tree-shaking 仅作用于 CSS'],
        answer: ['A'], explain: 'ESM 的静态导入/导出让打包器构建依赖图并剔除未引用代码；sideEffects:false 告知打包器可安全删除无副作用的模块。CommonJS 因动态特性难以静态分析，摇树效果差。' },
      { id: 'fev1-c15', tag: 'Vite', q: '关于 Vite 的开发服务器，下列说法正确的是？',
        options: ['Vite 在开发态对全部依赖做打包后才提供服务', 'Vite 基于原生 ESM 按需编译，并用 esbuild 对依赖做预构建（pre-bundling）', 'Vite 开发态使用 webpack 做模块转换', 'Vite 无法进行 HMR 热更新'],
        answer: ['B'], explain: 'Vite 开发态直接以原生 ESM 服务源码、按需编译单文件；对 node_modules 依赖用 esbuild 预构建为 ESM 并做去重/缓存，启动与热更新远快于传统打包；HMR 基于 ESM 精准更新。' },
      { id: 'fev1-c16', tag: 'HTTP', q: '关于 HTTP/2，下列说法正确的是？',
        options: ['HTTP/2 在同一条 TCP 连接上多路复用流，解决队头阻塞的应用层问题', 'HTTP/2 强制使用文本明文传输', 'HTTP/2 头部不再压缩', 'HTTP/2 每条请求必须新建 TCP 连接'],
        answer: ['A'], explain: 'HTTP/2 通过二进制分帧在单连接上并发多路复用流，消除应用层队头阻塞；用 HPACK 压缩头部；仍基于 TCP，故存在 TCP 层队头阻塞（HTTP/3 才转向 QUIC）。' },
      { id: 'fev1-c17', tag: '内存泄漏', q: '以下哪些情形可能导致前端内存泄漏？（多选）',
        options: ['给 window/document 添加的全局事件监听在组件销毁时未移除', 'setInterval/setTimeout 在组件卸载后未被 clear', '闭包持续引用了大对象且长期不被释放', '使用 const 声明局部变量'],
        answer: ['A', 'B', 'C'], multi: true, explain: '未移除的全局监听、未清理的定时器、长期持有的闭包引用都会阻止 GC 回收；这些是 SPA 常见泄漏源。const 局部变量在函数退出后正常释放，不是泄漏。' },
      { id: 'fev1-c18', tag: '动画', q: '实现动画时，requestAnimationFrame 相比 setTimeout 的主要优势是？',
        options: ['rAF 回调频率固定为每秒 1000 次', 'rAF 与浏览器重绘节奏对齐，页面在后台标签页时会自动暂停，更省电且更流畅', 'rAF 比 setTimeout 精度更低', 'rAF 只能在主线程外运行'],
        answer: ['B'], explain: 'rAF 在每次浏览器重绘前调用（通常 60fps），与刷新同步、避免丢帧；标签页不可见时浏览器会暂停 rAF，减少无谓计算。setTimeout 按设定间隔触发、后台仍可能运行且易与重绘错位。' },
      { id: 'fev1-c19', tag: 'Web Components', q: '关于 Web Components 的 Shadow DOM，下列说法正确的是？',
        options: ['Shadow DOM 让组件内部样式与全局样式完全隔离，外部 CSS 默认不影响内部', 'Shadow DOM 内的元素可以被全局 document.querySelector 直接选中', 'Shadow DOM 无法实现样式封装', 'Shadow DOM 仅用于服务端渲染'],
        answer: ['A'], explain: 'Shadow DOM 提供封装边界，内部 DOM 与样式默认不泄漏、外部选择器也无法穿透（除非用 ::part/变量）；外部 document.querySelector 选不到 shadow 内部节点（需进入 shadowRoot）。' },
      { id: 'fev1-c20', tag: 'Service Worker', q: '关于 Service Worker 的缓存策略，stale-while-revalidate 的含义是？',
        options: ['只使用网络，从不读缓存', '先返回缓存（快），同时后台更新缓存，下次请求用上新值', '只使用缓存，永不联网', '缓存与网络都失败才返回 504'],
        answer: ['B'], explain: 'stale-while-revalidate：优先立即返回缓存内容保证速度，同时异步发起网络请求用新响应刷新缓存，兼顾速度与新鲜度，常见于静态资源与离线优先场景。' }
    ],
    written: [
      { id: 'fev1-w1', q: '实现一个 useThrottle（React Hook 或 Vue composable），支持 leading/trailing，并说明它与 debounce 的本质区别与各自适用场景。',
        points: ['闭包持有定时器与上次执行时间', 'leading：首次立即执行、之后按间隔节流', 'trailing：末尾补一次以确保末次调用被处理', '节流=固定频率执行（滚动/resize）；防抖=停止后才执行（搜索联想）'],
        reference: 'function useThrottle(fn, wait) {\n  const last = useRef(0); const timer = useRef(null); const fnRef = useRef(fn); fnRef.current = fn;\n  return useCallback((...args) => {\n    const now = Date.now(); const remain = wait - (now - last.current);\n    if (remain <= 0) { last.current = now; fnRef.current(...args); }\n    else if (!timer.current) { timer.current = setTimeout(() => { last.current = Date.now(); timer.current = null; fnRef.current(...args); }, remain); }\n  }, [wait]);\n}\n节流保证「wait 毫秒内最多执行一次」，适合高频连续事件（滚动、鼠标移动）；防抖是「事件停止 wait 毫秒后才执行一次」，适合输入联想。' },
      { id: 'fev1-w2', q: '解释 CLS（累积布局偏移）指标的含义，给出至少 5 条降低 CLS 的工程措施并说明原理。',
        points: ['为图片/视频设置 width/height 或 aspect-ratio 预留空间', '字体使用 font-display: optional/swap 并预加载关键字体', '动态插入内容时预留占位/骨架', '避免对上方元素做无预留的尺寸变更', '用 transform 动画代替 top/height 位移', '用监控（Lighthouse/Web Vitals）量化'],
        reference: 'CLS = 所有意外布局偏移分数的累计和，衡量视觉稳定性。措施：①响应式媒体用 aspect-ratio 占位防塌陷；②字体用 size-adjust/fallback 减少 swap 抖动；③SSR 时渲染骨架、异步内容占位；④用 transform 走合成层代替触发布局的属性；⑤监控采集真实用户 CLS 定阈值（良好<0.1）。' },
      { id: 'fev1-w3', q: '简述微前端（Module Federation / qiankun）的加载与通信机制，并指出其 JS 沙箱隔离的主要难点。',
        points: ['运行时按路由/配置加载子应用入口（remoteEntry）', 'Module Federation 通过共享依赖与远程模块按需拉取', '通信：全局状态/自定义事件/Props 下发', '沙箱难点：JS 全局变量/样式污染、多版本依赖共存', '隔离方案：Proxy 沙箱/iframe/Shadow DOM'],
        reference: '加载：主应用按路由加载子应用 remoteEntry.js，Module Federation 解析 exposes 的远程模块并复用 shared 依赖；qiankun 用 import-html-entry 解析子应用 HTML 与脚本。通信：主子通过 props、全局 store 或事件总线。沙箱：单实例下多个子应用共享 window，需用 Proxy 快照/恢复隔离全局副作用，样式用 scoped 或 Shadow DOM 防污染。' },
      { id: 'fev1-w4', q: '设计一个前端监控 SDK：需采集 JS 错误（含 Promise 未捕获、资源错误）、性能指标（FCP/LCP/INP）、用户行为，并说明数据上报策略。',
        points: ['window.onerror / unhandledrejection / error 事件捕获', 'PerformanceObserver 采集 FCP/LCP/INP', '行为：路由变更、点击事件采样', '上报：navigator.sendBeacon 保证不丢、批量+节流', '采样率与去重控制成本'],
        reference: '错误：window.addEventListener("error") 捕获资源与运行时错误，unhandledrejection 捕获未处理的 Promise 拒绝。性能：PerformanceObserver 监听 paint（FCP）、largest-contentful-paint（LCP）、event（INP）。上报：优先 sendBeacon 在页面卸载时也能送达，本地先批量缓存、按条数/时间窗口 flush，并对错误做指纹去重、按采样率上报以控量。' },
      { id: 'fev1-w5', q: '解释 React 并发渲染（Concurrent Features）解决了什么问题，给出逐步迁移一个存量应用以引入 useTransition/Suspense 而不破坏现有逻辑的路径。',
        points: ['问题：长任务/大更新阻塞主线程、输入卡顿', 'startTransition 标记非紧急更新可中断', 'Suspense 边界让慢数据分块到达', '迁移：先包裹非关键更新、再拆分 Suspense 边界', '兼容：保留原有数据请求，仅重构渲染层'],
        reference: '并发渲染让 React 可中断、复用、排优先级渲染，避免大列表/重计算卡住输入。迁移路径：①识别非紧急更新（搜索结果、路由切换）用 useTransition 包裹；②把慢数据获取放进 Suspense 边界，配合流式 SSR 分块；③保留既有数据获取逻辑，仅把渲染层改为支持 Suspense；④用 React DevTools 的 Transition 标记验证优先级。' }
    ]
  },
  {
    id: 'exam-be-vip-1', name: '后端高阶架构卷 · VIP', track: 'backend', level: '高级', duration: 40, vipOnly: false,
    choices: [
      { id: 'bev1-c1', tag: '共识', q: 'Raft 共识算法中，关于 Leader 选举，下列说法正确的是？',
        options: ['所有节点随时可以处理写请求', '节点在 election timeout 内未收到合法 Leader 心跳，则转为 Candidate 发起选举', '选举不需要多数派（quorum）同意', 'Term 仅用于区分日志，不参与选举'],
        answer: ['B'], explain: 'Raft 中 Follower 在随机 election timeout 内未收到 Leader 心跳即变为 Candidate、递增 term 并请求投票；获得多数派选票者成为 Leader。任期（term）单调递增，用于拒绝过期 Leader。' },
      { id: 'bev1-c2', tag: '分布式事务', q: '关于分布式事务，Saga 与 2PC 的区别，正确的是？',
        options: ['2PC 是最终一致，Saga 是强一致', 'Saga 通过一系列本地事务 + 补偿操作实现最终一致，避免长事务锁', '2PC 不会有任何阻塞风险', 'Saga 不需要处理补偿逻辑'],
        answer: ['B'], explain: '2PC 在两阶段持锁、协调者故障会长期阻塞，属强一致但可用性差；Saga 把长事务拆为本地事务序列，每步配有补偿（回滚）操作，失败时反向补偿，达成最终一致、不长期持锁。' },
      { id: 'bev1-c3', tag: '幂等', q: '设计幂等接口时，关于幂等键（Idempotency-Key），下列说法正确的是？',
        options: ['幂等键应由服务端随机生成', '客户端在重试时携带相同幂等键，服务端据其去重/返回首次结果', '幂等键只对 GET 请求有意义', '幂等键无需持久化即可生效'],
        answer: ['B'], explain: '客户端为每次业务操作生成唯一幂等键（如 UUID）并在重试中复用；服务端将其与处理结果持久化，重复提交时直接返回首次结果，从而安全重试（支付、下单等关键路径必备）。' },
      { id: 'bev1-c4', tag: 'Kafka', q: 'Kafka 实现「精确一次（exactly-once）」语义依赖哪些机制？（多选）',
        options: ['幂等生产者（Idempotent Producer）去重', '事务（Transactional）跨分区原子写入', '消费者手动提交 offset 与处理结果落库放在同一事务', '仅依赖 at-most-once 配置'],
        answer: ['A', 'B', 'C'], multi: true, explain: 'EOS 由幂等生产者（去重避免重试导致重复）+ 事务（跨分区原子写、与消费位移协调）组合实现；消费端需将「处理业务 + 提交 offset」原子化（如事务性输出或唯一约束）才能端到端精确一次。' },
      { id: 'bev1-c5', tag: 'CAP', q: '在分布式系统发生网络分区（Partition）时，CAP 理论要求必须在哪两者间取舍？',
        options: ['一致性与可用性（CP 或 AP）', '一致性与持久性', '可用性与吞吐量', '分区与复制'],
        answer: ['A'], explain: 'CAP 指网络分区发生时，系统无法同时保证强一致（C）与高可用（A）：选 CP 则暂停不可用分区以保一致，选 AP 则继续服务但可能读到旧值。分区容错（P）在分布式中必须保证。' },
      { id: 'bev1-c6', tag: 'Redis', q: '关于 Redis 数据结构在高并发场景的选用，下列说法正确的是？',
        options: ['HyperLogLog 用于精准去重计数且占用极小内存', 'Bitmap 适合统计用户每日签到等二值状态', 'ZSet 无法按分数范围查询', 'String 类型是唯一支持过期时间的类型'],
        answer: ['B'], explain: 'Bitmap 以位存二值，非常适合海量用户的签到/在线标记；HyperLogLog 是基数估算（非精准去重）、内存极小但有误差；ZSet 支持按 score 范围/排名查询（榜单常用）；多种类型都支持过期。' },
      { id: 'bev1-c7', tag: 'SQL索引', q: '以下哪些写法会导致 MySQL 索引失效、退化全表扫描？（多选）',
        options: ['对索引列使用函数：WHERE YEAR(create_time) = 2024', '隐式类型转换：WHERE phone = 13800000000（phone 是字符串列）', '最左前缀匹配缺失：联合索引(a,b,c) 查询条件只有 c', '使用覆盖索引查询'],
        answer: ['A', 'B', 'C'], multi: true, explain: '对索引列套函数、隐式类型转换都会破坏有序性使索引失效；联合索引需遵循最左前缀，跳过左侧列则后续列无法用索引。覆盖索引（只查索引列）反而是优化手段。' },
      { id: 'bev1-c8', tag: '连接池', q: '关于数据库连接池，下列说法正确的是？',
        options: ['连接数越大吞吐越高，没有上限', '连接数过多会加剧上下文切换、锁竞争与内存占用，反而降低吞吐', '连接池大小应始终等于并发请求数', '连接池只用于读库，写库不需要'],
        answer: ['B'], explain: '数据库连接（尤其有锁/事务）并非越多越好；超过数据库负载拐点后，竞争与切换开销上升、吞吐下降。应基于 DB 核数/负载实测设定上限，配合排队而非无限扩连接。' },
      { id: 'bev1-c9', tag: 'OAuth2', q: '公共客户端（如移动端/ SPA）使用 OAuth2 授权码模式时，为何要引入 PKCE？',
        options: ['PKCE 用于加密 access token 传输', 'PKCE 通过 code_verifier/code_challenge 防止授权码被截获后遭重放', 'PKCE 替代了 refresh token', 'PKCE 仅用于服务端到服务端的认证'],
        answer: ['B'], explain: '公共客户端无法安全保存 client_secret，PKCE 让客户端生成随机 verifier 并在请求时携带其挑战值，令牌端点校验二者匹配，即使授权码被截获也无法换到令牌，缓解拦截重放。' },
      { id: 'bev1-c10', tag: '限流', q: '关于限流算法，令牌桶与漏桶的区别，正确的是？',
        options: ['漏桶允许突发流量，令牌桶不允许', '令牌桶以固定速率生成令牌、桶满则丢弃/拒绝，允许一定程度的突发；漏桶以恒定速率流出、平滑输出', '两者实现完全一致', '令牌桶无法应对突发'],
        answer: ['B'], explain: '令牌桶按固定速率放令牌、桶有容量故可短时放行积累的突发；漏桶以恒定速率处理、超出则排队或丢弃，重在平滑。不同场景取舍：要削峰用漏桶，要容忍突发用令牌桶。' },
      { id: 'bev1-c11', tag: '缓存', q: '缓存系统的三大经典问题及对策，下列说法正确的组合是？（多选）',
        options: ['缓存穿透：查不存在的 key，可用布隆过滤器或空值缓存拦截', '缓存击穿：热点 key 失效瞬间高并发打到 DB，可用互斥锁/逻辑过期', '缓存雪崩：大量 key 同时失效，可用随机 TTL 错峰', '缓存穿透只能靠加机器解决'],
        answer: ['A', 'B', 'C'], multi: true, explain: '穿透=查不存在数据（布隆过滤器/空值缓存）；击穿=单热点失效（互斥重建/逻辑过期）；雪崩=批量同时失效（随机 TTL/多级缓存）。三者对策不同，加机器无法根治穿透。' },
      { id: 'bev1-c12', tag: '一致性', q: '关于最终一致性，下列说法正确的是？',
        options: ['最终一致性意味着系统永远不一致', '在没有新写入的一段时间内，所有副本会收敛到相同值', '最终一致性比强一致更不安全，应尽量避免', '最终一致性只存在于单库系统'],
        answer: ['B'], explain: '最终一致性保证：若停止写入并经过足够时间，各副本将收敛一致。它在分区/高可用场景下以短暂不一致换取可用性，是大型分布式系统的常见取舍（如 DNS、复制库）。' },
      { id: 'bev1-c13', tag: '异步', q: '关于 Node.js 的事件循环与异步 I/O，下列说法正确的是？',
        options: ['Node 是多线程执行 JS，事件循环只是装饰', 'Node 单线程执行 JS，I/O 由 libuv 线程池与操作系统异步完成，事件循环调度回调', 'Promise 回调属于定时器阶段', 'async/await 让 Node 变成多线程'],
        answer: ['B'], explain: 'Node 主线程单线程跑 JS，事件循环分阶段（timers/I/O/check 等）调度回调；真正的文件/网络 I/O 由 libuv 线程池与 OS 异步处理，完成后回调入队。async/await 只是 Promise 语法糖，仍是单线程。' },
      { id: 'bev1-c14', tag: 'API版本', q: '关于 API 版本管理，下列说法正确的是？',
        options: ['URL 路径版本（/v1/...）与请求头版本（Accept 媒体类型）都能实现，各有取舍', '版本只能在数据库里维护，不能通过接口表达', '一旦发布 v1 就永远不能变更', '版本号必须用日期格式'],
        answer: ['A'], explain: 'URL 版本直观、易调试、利于缓存与网关路由，但污染路径；Header/媒体类型版本保持 URL 干净、利于超媒体，但不直观。两者皆可行，按团队与生态取舍；关键是要向后兼容地演进。' },
      { id: 'bev1-c15', tag: 'gRPC', q: 'gRPC 相比传统 REST/JSON 通常更快，主要原因是？',
        options: ['gRPC 使用 HTTP/1.1 与文本 JSON', 'gRPC 基于 HTTP/2 多路复用 + Protobuf 二进制序列化，体积小、解析快', 'gRPC 不需要定义接口', 'gRPC 不支持流式'],
        answer: ['B'], explain: 'gRPC 用 Protobuf 强类型二进制编码（比 JSON 小且省解析），承载于 HTTP/2（多路复用、头部压缩、双向流），在内部服务间调用上延迟与吞吐显著优于 JSON/HTTP1。需 IDL 定义接口。' },
      { id: 'bev1-c16', tag: '分布式ID', q: '分库分表后生成全局唯一且趋势递增的 ID，Snowflake 方案的核心是？',
        options: ['用数据库自增主键跨分片', '用时间戳 + 机器/实例位 + 序列号组合出 64 位 ID，避免中心化分配', '由客户端随机数决定', '依赖单点 Redis 自增'],
        answer: ['B'], explain: 'Snowflake 把 64 位分为时间戳、机房/机器位、序列号，各节点本地生成、不依赖中心且趋势递增、利于 B+Tree 写入；需解决时钟回拨问题。相比跨分片自增更可扩展。' },
      { id: 'bev1-c17', tag: '消息队列', q: '消息队列出现严重消息积压时，正确的应急思路是？',
        options: ['立即删除消息以清积压', '临时扩容消费者、提升消费并行度，并排查消费慢的根因（如慢 SQL/外部调用）；必要时降级或批量处理', '把生产者也停掉即可', '积压无需处理，会自动消失'],
        answer: ['B'], explain: '应急应定位消费瓶颈（慢查询、外部依赖超时），临时增加消费实例/线程、批量消费、跳过非核心逻辑；根治后再补容量。盲目删消息会丢数据，仅停生产不解决消费慢。' },
      { id: 'bev1-c18', tag: 'TLS', q: '关于 TLS 1.3 握手，下列说法正确的是？',
        options: ['TLS 1.3 仍需完整的两次往返（2-RTT）才能建连', 'TLS 1.3 支持 1-RTT 建连，并对之前连接支持 0-RTT 恢复', 'TLS 1.3 不再加密握手过程', 'TLS 1.3 使用 RSA 密钥交换'],
        answer: ['B'], explain: 'TLS 1.3 精简为 1-RTT（甚至 0-RTT 会话恢复），移除了不安全的密钥交换（如静态 RSA），默认前向安全（ECDHE）。握手消息也加密（除必要明文）。' },
      { id: 'bev1-c19', tag: '链路追踪', q: '关于分布式链路追踪的上下文传播，下列说法正确的是？',
        options: ['只需在网关记录日志即可，无需透传', '通过 W3C traceparent 等标准在跨服务调用中透传 trace/span id，才能拼接完整调用链', '追踪上下文只能在同一进程内有效', 'span 之间不需要父子关系'],
        answer: ['B'], explain: '链路追踪依赖上下文透传：调用方把 trace id 与 parent span id 注入请求头（如 traceparent），下游继续派生子 span，后端按父子关系还原调用拓扑与耗时。标准（W3C）保证跨语言/框架互通。' },
      { id: 'bev1-c20', tag: '幂等消费', q: '消费者处理消息时保证幂等，常见做法是？',
        options: ['依赖消息队列不重复投递（at-most-once）即可高枕无忧', '用业务唯一键（如订单号）+ 去重表/唯一索引，使重复消息被忽略或返回同结果', '每次都直接更新，不关心重复', '只在生产者端保证即可'],
        answer: ['B'], explain: '用业务唯一键配合数据库唯一约束或去重表，重复消息到达时插入/更新会因唯一键冲突被忽略或返回一致结果，从而在「至少一次」投递下实现幂等消费。' }
    ],
    written: [
      { id: 'bev1-w1', q: '设计一个幂等的支付下单接口：说明幂等键生成、服务端去重存储、与第三方支付回调的协同，并给出伪代码。',
        points: ['客户端生成幂等键（UUID）随请求带上', '服务端以唯一约束落库，重复则返首次结果', '回调按业务单号去重处理', '状态机控制支付流转，避免重复记账'],
        reference: 'POST /pay 带 Idempotency-Key 头。服务端：INSERT INTO pay_order(idemp_key,...) ON CONFLICT DO NOTHING；命中冲突则 SELECT 返回既有订单。第三方回调按 order_no 唯一处理，用状态机（CREATED→PAID）保证只入账一次，重复回调因状态已 PAID 直接忽略。' },
      { id: 'bev1-w2', q: '解释缓存击穿（hot key 失效）的成因，给出至少 3 种缓解方案并附关键代码（如互斥重建、逻辑过期、singleflight）。',
        points: ['成因：单热点 key 过期瞬间高并发打到 DB', '互斥锁：仅一个线程重建，其余等待', '逻辑过期：value 带过期时间，异步刷新不阻塞', 'singleflight：合并并发请求为一次回源'],
        reference: '互斥重建：if cache miss { if tryLock { val=load(); set(key,val,exp); unlock } else { sleep; retry get } }。逻辑过期：存 {data,expireAt}，读取时若过期则放后台线程刷新、先返回旧值。singleflight（如 Go）把同一 key 的并发 get 合并为一次 DB 查询。' },
      { id: 'bev1-w3', q: '设计一个分布式限流器（令牌桶），需支持多实例共享状态，说明存储选型（Redis）与原子操作（Lua）要点。',
        points: ['用 Redis 存每个 key 的令牌数与时间戳', '定时按速率 refill（计算 elapsed*rate）', '获取令牌用 Lua 脚本保证原子（计算+扣减）', '多实例共享同一 Redis，避免各自计数'],
        reference: 'Lua 脚本：读取 {tokens, ts}，now = TIME，tokens = min(cap, tokens + (now-ts)*rate)，若 tokens>=1 则 tokens-=1 并放行，否则拒绝；写回。Lua 保证「计算+判断+扣减」原子，避免竞态；多实例指向同一 Redis 即全局限流。' },
      { id: 'bev1-w4', q: '描述如何在 Kafka 上构建端到端精确一次（exactly-once）的「消费-处理-写出」管道，涵盖幂等生产者、事务、消费位移与业务落库原子化。',
        points: ['生产者开启幂等 + 事务', '消费位移与业务写放在同一事务（事务性输出）', '业务表用唯一键防重复', 'enable.idempotence + transactional.id 绑定'],
        reference: '生产者设 enable.idempotence=true 与 transaction.id；消费后在事务内「处理业务落库 + 发送下游 + 提交位移」，由 broker 保证原子。消费端对业务主键加唯一约束，即使 at-least-once 重放也不会重复处理，实现端到端精确一次。' },
      { id: 'bev1-w5', q: '设计一个短链服务：分布式 ID 生成（短码）、302 重定向、点击统计与防刷，并讨论热点短码与存储选型。',
        points: ['短码：发号器/哈希/Base62 生成唯一码', '重定向：302 + 缓存，注意 301 被浏览器缓存', '统计：异步写、布隆去重计数', '防刷：限流 + 验证码/签名', '存储：短码→长链用 KV/Redis，统计用列式/时序'],
        reference: '短码用 Snowflake/号段发号器或长链哈希取前 N 位（冲突重试）。重定向用 302（避免 301 被缓存导致长链无法更新）。点击统计异步写、用 HyperLogLog 估算 UV、布隆过滤去重。热点短码走 Redis 缓存；防刷对单码限频。存储：短码映射用 Redis+DB 双写，统计落时序库。' }
    ]
  },
  {
    id: 'exam-op-vip-1', name: '运维 / DevOps 高阶卷 · VIP', track: 'devops', level: '高级', duration: 40, vipOnly: false,
    choices: [
      { id: 'opv1-c1', tag: 'Kubernetes', q: 'Kubernetes 中 Pod 长期处于 Pending，最常见的原因组合是？（多选）',
        options: ['资源请求（CPU/内存）超过节点可分配量，或没有节点满足 nodeSelector/亲和性', 'PVC 无法绑定到可用 PV', '镜像仓库完全正常、网络通畅', '只是因为 kubelet 太新'],
        answer: ['A', 'B'], multi: true, explain: 'Pending 多因调度失败：节点资源不足以满足 requests、亲和性/污点（taint）不匹配、或依赖的 PVC 无法绑定。需 describe pod 看 Events 与调度器日志定位。' },
      { id: 'opv1-c2', tag: 'etcd', q: '关于 etcd 与 Raft，下列说法正确的是？',
        options: ['etcd 用单点 MySQL 存储元数据', 'etcd 用 Raft 在多个节点间复制日志，保证 Kubernetes 控制面元数据的一致与高可用', 'etcd 不需要持久化', 'Raft 在 etcd 中只用于选举，不复制数据'],
        answer: ['B'], explain: 'etcd 是 K8s 的可靠存储后端，基于 Raft 在奇数节点间复制写日志并达成多数派一致，提供强一致的键值存储；其健康直接决定集群控制面可用性。' },
      { id: 'opv1-c3', tag: 'Service Mesh', q: 'Istio 等服务网格如何让 Sidecar 拦截业务容器的流量？',
        options: ['修改业务代码注入代理', '通过 iptables/IPVS 规则把进出 Pod 的流量重定向到 Sidecar 代理（如 Envoy）的端口', '依赖 DNS 劫持全局域名', '必须由开发者手动配置代理'],
        answer: ['B'], explain: '服务网格在 Pod 内注入 Init 容器，用 iptables（或 IPVS）把应用的入站/出站流量透明重定向到 Envoy sidecar 端口，实现无侵入的流量管理、mTLS 与可观测，业务代码零改动。' },
      { id: 'opv1-c4', tag: 'eBPF', q: '关于 eBPF，下列说法正确的是？',
        options: ['eBPF 只能用于网络加速', 'eBPF 允许在不修改内核源码/加载内核模块的情况下，安全地在内核态挂载程序，用于可观测、网络与安全', 'eBPF 必须重新编译整个内核才能生效', 'eBPF 运行在用户态，无法访问内核数据'],
        answer: ['B'], explain: 'eBPF 提供沙箱化的内核可编程能力：经校验后挂载到钩子（syscall、网络、跟踪点），无需改内核或装模块，广泛用于性能剖析（火焰图）、网络加速（Cilium）、安全观测。' },
      { id: 'opv1-c5', tag: 'OpenTelemetry', q: '关于 OpenTelemetry Collector，下列说法正确的是？',
        options: ['Collector 只支持把数据发往单一后端', 'Collector 通过 Receiver-Processor-Exporter 流水线接收、处理（采样/批处理/转换）、导出到多种后端，解耦埋点与存储', 'OpenTelemetry 只处理日志', 'Collector 不能做采样'],
        answer: ['B'], explain: 'OTel Collector 以可插拔流水线工作：Receiver 接收 OTLP 等格式，Processor 做批处理/采样/脱敏，Exporter 输出到 Prometheus/Jaeger/云厂商等，使应用与后端解耦、可灵活切换。' },
      { id: 'opv1-c6', tag: 'Terraform', q: '关于 Terraform 的 state 与漂移（drift），下列说法正确的是？',
        options: ['state 文件只是缓存，可随意删除', 'state 记录基础设施真实映射，手动改云资源会导致 state 漂移；用 terraform plan/refresh 可检测漂移', 'Terraform 无法检测手动变更', 'state 必须存本地文件，不能用远程后端'],
        answer: ['B'], explain: 'state 是 Terraform 对资源的权威记录；若有人绕过 IaC 手动改资源（漂移），plan 会显示差异。应使用远程后端（带锁）共享 state，并用 plan 周期性检测漂移、以代码为准收敛。' },
      { id: 'opv1-c7', tag: '发布', q: '关于渐进式发布（金丝雀/Canary），下列说法正确的是？',
        options: ['金丝雀发布是一次全量切换', '金丝雀先把少量流量导到新版本，按指标（错误率/延迟）逐步放大，异常则快速回滚', '金丝雀不需要监控指标参与决策', '只有物理机部署才需要金丝雀'],
        answer: ['B'], explain: '金丝雀以可控比例（如 5%→25%→100%）引流到新版本，结合监控与自动分析（如 Argo Rollouts/Flagger）判断健康，异常即回滚，把故障影响面降到最低。' },
      { id: 'opv1-c8', tag: '性能', q: '生成 CPU 火焰图（Flame Graph）的典型流程是？',
        options: ['用 perf 采样后由 perf script/FlameGraph 工具折叠栈并渲染', '直接读取日志即可', '只能靠猜', '火焰图只显示内存，不显示 CPU'],
        answer: ['A'], explain: '流程：perf record 采样 CPU（或 eBPF 工具），perf script 展开调用栈，经 stackcollapse + flamegraph.pl 折叠渲染为火焰图，纵轴栈深、横轴耗时，便于定位热点函数。' },
      { id: 'opv1-c9', tag: 'TCP', q: '关于 TCP 三次握手与 TIME_WAIT，下列说法正确的是？',
        options: ['四次挥手后主动关闭方立即释放端口，无等待', '主动关闭方会进入 TIME_WAIT，等待 2*MSL 以确保最后 ACK 可达、旧报文消散', 'TIME_WAIT 只出现在被动关闭方', '高并发短连接不会因 TIME_WAIT 耗尽端口'],
        answer: ['B'], explain: '主动关闭方在 FIN 后进入 TIME_WAIT（默认 2*MSL）以防最后 ACK 丢失导致对端重传、并让网络中残留报文过期。高并发短连接常因此耗尽本地端口，需调参数或连接复用缓解。' },
      { id: 'opv1-c10', tag: 'QUIC', q: '关于 QUIC（HTTP/3）的 0-RTT，下列说法正确的是？',
        options: ['0-RTT 适用于所有请求且绝对安全', '0-RTT 复用此前会话的密钥，首个请求即可携带数据，降低延迟，但存在重放风险', 'QUIC 仍基于 TCP', '0-RTT 需要完整 TLS 握手'],
        answer: ['B'], explain: 'QUIC 基于 UDP，会话恢复时可 0-RTT 发送数据（客户端用缓存的 early data 密钥），显著降延迟；但 0-RTT 数据可被重放，仅适合幂等请求，需服务端防护。' },
      { id: 'opv1-c11', tag: '密钥', q: '关于 Vault 的动态密钥（Dynamic Secrets），下列说法正确的是？',
        options: ['动态密钥是写死在配置文件里的长期密码', 'Vault 按需为应用生成带 TTL 的临时凭证（如数据库账号），到期自动吊销，缩短暴露面', 'Vault 只能管理静态 KV', '动态密钥无法自动过期'],
        answer: ['B'], explain: 'Vault 通过 secrets engine 在应用请求时生成短期、带租约的凭证（DB/云账号等），并自动在租约到期或 revoke 时吊销，极大降低长期密钥泄露风险，契合最小权限。' },
      { id: 'opv1-c12', tag: '镜像', q: '关于容器镜像最小化（如 distroless / scratch），主要收益是？',
        options: ['镜像更大但更全', '减少攻击面（无 shell/包管理器）、缩小体积、加快拉取与启动', '必须包含完整 OS 才能保证运行', '仅影响构建速度，不影响安全'],
        answer: ['B'], explain: 'distroless/scratch 镜像只含应用与必要运行时，剔除 shell、包管理器与多余库，既缩小体积、加速分发，又显著缩小被攻击面（无法 exec 进容器、缺利用工具）。' },
      { id: 'opv1-c13', tag: 'CI/CD', q: '关于 CI/CD 流水线缓存策略，下列说法正确的是？',
        options: ['每次都从零构建最可靠，缓存有害', '对依赖与构建中间产物做带 key 的缓存可大幅提速，但需保证缓存命中与源码一致', '缓存只能在本地磁盘，无法跨 runner', '缓存永远新鲜，无需失效策略'],
        answer: ['B'], explain: '合理缓存依赖与产物能显著缩短流水线；关键是按 lockfile/分支做缓存 key、并设失效/校验，避免脏缓存导致「本地能过、CI 失败」或用到陈旧依赖。' },
      { id: 'opv1-c14', tag: 'DNS', q: '关于 DNS 解析与 TTL，下列说法正确的是？',
        options: ['TTL 越大越有利于故障切换', 'TTL 是记录在缓存中的存活时间；TTL 越小切换越快但查询压力越大，需按变更频率权衡', 'DNS 只解析 IPv4', 'DNS 解析不需要递归查询'],
        answer: ['B'], explain: 'TTL 决定记录被缓存的时长：小 TTL 利于快速切流（如故障转移），但增加权威 DNS 查询量；大 TTL 减负却拖慢切换。常采用「变更前临时调小 TTL」的灰度策略。' },
      { id: 'opv1-c15', tag: '负载均衡', q: '关于负载均衡，下列说法正确的是？',
        options: ['L4 负载均衡能基于 URL 路径做路由', 'L4 基于 IP/端口转发、性能好；L7 能理解 HTTP，按域名/路径/Header 路由并做健康检查', '一致性哈希只在 L4 使用', 'L7 无法做 SSL 卸载'],
        answer: ['B'], explain: 'L4（传输层）按 IP/端口转发、开销小；L7（应用层）解析 HTTP，可据路径/域名/Header 分流、做 SSL 卸载与更细粒度健康检查；一致性哈希常用于会话亲和/缓存命中。' },
      { id: 'opv1-c16', tag: '磁盘', q: '磁盘仍有空间但写入失败，最可能的原因是？',
        options: ['CPU 不足', 'inode 耗尽（大量小文件占满索引节点）', '内存不足', '网络丢包'],
        answer: ['B'], explain: '文件系统空间由「数据块」与「inode（索引节点）」两部分构成；海量小文件会先耗尽 inode，即使数据块尚有剩余也无法新建文件。用 df -i 可确认，需清理或调整 fs 参数。' },
      { id: 'opv1-c17', tag: '排障', q: '关于网络排障工具，下列说法正确的是？',
        options: ['tcpdump 只能抓应用层日志', 'tcpdump 抓包分析协议/连接，bpftrace/eBPF 可在内核态动态追踪函数与延迟，二者互补', 'bpftrace 无法观测网络', '排障只需看应用日志'],
        answer: ['B'], explain: 'tcpdump 抓包看报文与连接状态；bpftrace 基于 eBPF 在内核态追踪系统调用、函数耗时与丢包点，适合定位「应用层看不出」的内核/网络瓶颈，二者互补。' },
      { id: 'opv1-c18', tag: 'MTTR', q: '降低 MTTR（平均恢复时间）最有效的工程实践组合是？（多选）',
        options: ['完善可观测性（指标/日志/链路）+ 明确告警与 On-call + 预案与自动恢复', '只靠增加服务器数量', '事故后复盘（Postmortem）并形成可执行的改进项', '关闭所有监控以减少噪音'],
        answer: ['A', 'C'], multi: true, explain: '降低 MTTR 靠「快速发现（监控/告警）+ 快速定位（可观测三件套）+ 快速恢复（预案/自动化）+ 事后复盘防复发」的闭环。单纯堆机器或关监控反而延长故障。' },
      { id: 'opv1-c19', tag: '容量', q: '关于容量规划与压测，下列说法正确的是？',
        options: ['压测只需在单机进行', '应基于目标 SLA（如 p99 延迟、错误率）做逐级压测，找到拐点并预留余量（headroom）与弹性伸缩', '容量规划是一次性的，无需重复', '只需看平均 QPS'],
        answer: ['B'], explain: '容量规划以 SLA 为目标，用压测定位吞吐拐点（资源饱和点），据此定容量并留余量、配 HPA；业务增长/架构变化后需复测，只看均值会掩盖长尾风险。' },
      { id: 'opv1-c20', tag: 'GitOps', q: '关于 GitOps，下列说法正确的是？',
        options: ['GitOps 指直接 kubectl 手动改集群', 'GitOps 以 Git 为唯一事实源，由控制器（如 Argo CD）持续比对并自动把集群收敛到声明状态（pull 模型）', 'GitOps 不支持回滚', 'GitOps 只适用于无状态应用'],
        answer: ['B'], explain: 'GitOps 把集群期望状态存于 Git，控制器周期性 drift detection 并自动/审批同步（pull），变更经 PR 评审、回滚即回退提交，审计清晰；有状态应用同样适用（需配合 operator）。' }
    ],
    written: [
      { id: 'opv1-w1', q: '设计一个高可用 Web 服务架构（多可用区）：含接入层、应用层、数据层与故障转移，说明 RTO/RPO 考量。',
        points: ['接入层：多 AZ 的 LB + 健康检查', '应用层：无状态、跨 AZ 多副本 + 自动伸缩', '数据层：主从/多副本 + 跨 AZ 复制', '故障转移：自动切流 + 数据不丢（RPO≈0）', 'RTO/RPO：按业务定恢复目标'],
        reference: '跨至少 2 个 AZ 部署：接入层用多 AZ LB（如 ALB/NLB）做健康检查与切流；应用层无状态、跨 AZ 多副本 + HPA；数据层用主从复制（如 MySQL MGR / Redis 哨兵）跨 AZ，故障时自动选主。RPO 靠同步/半同步复制逼近 0，RTO 靠健康探测与自动切流控制在秒级。' },
      { id: 'opv1-w2', q: '排查一个 OOMKilled 的 Pod：给出从 events、资源 request/limit、内存画像到解决（调优/拆分）的完整思路与命令。',
        points: ['kubectl describe pod 看 Last State/OOMKilled', '对比 request/limit 与实际使用', 'kubectl top / 容器内 memory profile 定位大户', '解决：调大 limit、优化内存、拆服务、加流式处理', '设合理 request 以便调度'],
        reference: '步骤：kubectl describe pod 看 Events 中 OOMKilled 与退出码 137；kubectl top pod 看实时用量；对比 limit（超则被杀）。用 pprof/heap snapshot 定位内存大户（缓存、大对象、泄漏）。解决：合理调大 limit 与 request、优化数据结构/及时释放、改全量加载为流式、或拆出内存密集型子服务。' },
      { id: 'opv1-w3', q: '用 Kubernetes 实现蓝绿或金丝雀发布：说明 Ingress/Service 切换、流量比例控制与基于指标的自动回滚。',
        points: ['蓝绿：两套 Service/Deploy，切 Ingress 指向', '金丝雀：按比例切流量（Istio 权重 / Nginx 分片）', '指标：错误率、延迟、QPS', '自动回滚：Argo Rollouts/Flagger 分析指标异常即回退', '保留快速回退能力'],
        reference: '蓝绿：green 部署就绪后，将 Service selector 或 Ingress 后端一次性切到 green，异常则切回 blue。金丝雀：用 Service Mesh（VirtualService 权重）或 Ingress 注解按比例引流（5%→100%）。用 Argo Rollouts 绑定 Prometheus 指标（错误率/延迟），超出阈值自动 abort 并回滚到稳定版。' },
      { id: 'opv1-w4', q: '设计一套可观测性体系：指标（Prometheus）、日志（Loki/ELK）、链路（OTel/Jaeger）如何采集、关联与告警，给出关键 SLO 指标。',
        points: ['指标：Exporter + Prometheus 拉取 + 规则告警', '日志：结构化 + 标签，Loki 索引', '链路：OTel 注入、traceId 贯穿', '关联：traceId 串联日志与指标', 'SLO：可用性、延迟 p99、错误率'],
        reference: '指标用 Prometheus 拉取 Exporter、配 recording/alerting rule；日志结构化为 JSON 并经 Loki 索引（用 label 关联）；链路用 OTel SDK 注入 traceId，并在日志/指标里带上 traceId 实现三件套关联。SLO 关注可用性（成功比）、延迟 p99、错误率（如 5xx）、饱和度，超错误预算触发告警。' },
      { id: 'opv1-w5', q: '写一个 Terraform 模块实现自动扩缩容组（ASG/节点池）：含实例模板、伸缩策略、健康检查的要点与状态管理。',
        points: ['资源：实例模板/启动配置 + 伸缩组', '伸缩策略：基于 CPU/自定义指标的目标追踪', '健康检查：ELB 健康 + 实例健康', '状态：远程后端 + 锁，避免漂移', '生命周期：滚动更新、保护策略'],
        reference: '模块输出：launch_template（镜像/规格/user_data）、autoscaling_group（min/max/desired、subnets、mixed_instances_policy）、scaling_policy（target tracking on CPU 或队列深度）。健康检查用 ELB 健康 + 实例健康，不健康的实例被替换。状态存远程后端（S3+ DynamoDB 锁）防并发与漂移；启用实例保护避免缩容杀掉关键实例。' }
    ]
  },
  {
    id: 'exam-ai-vip-1', name: 'AI 工程高阶卷 · VIP', track: 'ai', level: '高级', duration: 40, vipOnly: false,
    choices: [
      { id: 'aiv1-c1', tag: '推理优化', q: '关于大模型推理的 Prompt Caching（提示缓存），下列说法正确的是？',
        options: ['Prompt Caching 会把整段对话重新计费、重新计算', '对前缀相同的长系统提示/上下文做哈希缓存 KV，命中后免去重复预填充、降低延迟与成本', 'Prompt Caching 仅对输出 token 有效', 'Prompt Caching 会增加首字延迟'],
        answer: ['B'], explain: 'Prompt Caching（如 Claude cache_control、OpenAI prompt caching）对稳定前缀（系统提示、知识库上下文）缓存注意力 KV，后续请求命中后跳过预填充，显著降低延迟与输入成本。' },
      { id: 'aiv1-c2', tag: 'RAG', q: '关于 RAG 的文档切分（chunking），下列说法正确的是？',
        options: ['chunk 越大越好，信息越全', '切分需在「检索精度」与「上下文完整」间权衡：过小易失上下文、过大引入噪声；重叠（overlap）有助于保留边界语义，配合重排序（rerank）提升相关段命中', '切分方式对检索质量无影响', '必须使用固定字符数切分，不能用结构感知'],
        answer: ['B'], explain: 'chunk 大小直接影响召回：过小丢失上下文、过大稀释相关性。重叠窗口缓解边界割裂；按标题/段落结构切分优于纯字符切；检索后用 cross-encoder rerank 能显著提升 Top-k 相关性。' },
      { id: 'aiv1-c3', tag: 'Embedding', q: '关于文本向量（Embedding），下列说法正确的是？',
        options: ['Embedding 维度越低语义越丰富', 'Embedding 把文本映射为稠密向量，语义相近的文本在向量空间距离更近；通常需归一化以便用点积/余弦度量相似度', 'Embedding 与模型无关，可任意混用不同模型的向量', 'Embedding 只能用于分类'],
        answer: ['B'], explain: 'Embedding 将语义编码进向量，相似语义聚拢；检索时按余弦/点积找近邻。不同模型的向量空间不可比，混用会失效；通常 L2 归一化后用点积等价余弦，便于向量库加速。' },
      { id: 'aiv1-c4', tag: 'Agent', q: '关于 Agent 的工具调用（function calling）可靠性，下列说法正确的是？',
        options: ['模型一次只能调用一个工具，且 guaranteed 成功', '应设计重试/超时/降级、对工具返回做校验与错误兜底，并以循环（如 ReAct）根据观察决定下一步，防止死循环需设步数上限', '工具调用不需要任何错误处理', 'Agent 不需要把工具结果回灌给模型'],
        answer: ['B'], explain: '可靠 Agent 需把工具结果回灌模型形成「思考-行动-观察」循环（ReAct），并对调用加超时、重试、结果校验与步数上限，避免无限循环或单点失败导致整体不可用。' },
      { id: 'aiv1-c5', tag: '评估', q: '用 LLM 当裁判（LLM-as-judge）评估生成质量时，主要风险是？',
        options: ['LLM 裁判绝对客观无偏', '存在位置偏好、冗长偏好、自我偏好（偏好自身生成的风格）等偏差，需用多裁判/对照基准校准', 'LLM 裁判成本为零', 'LLM 裁判不需要人工抽查'],
        answer: ['B'], explain: 'LLM 裁判易受位置（偏好前者）、长度（偏好更长）、自我偏好（偏好与自身风格相近）等偏差影响；应以黄金集人工校验、多模型交叉、控制变量来校准，不能完全替代人工。' },
      { id: 'aiv1-c6', tag: '安全', q: 'OWASP 为 LLM 应用列出的十大风险中，提示注入（Prompt Injection）指的是？',
        options: ['用户正常提问', '攻击者通过输入操纵模型忽略原系统指令、执行非预期行为（如泄露指令、越权操作）', '模型输出太长', '训练数据不足'],
        answer: ['B'], explain: '提示注入分直接（用户在输入中嵌入恶意指令）与间接（通过检索的外部内容注入），目标是劫持模型行为。防护需指令与不可信内容隔离、最小权限、输出校验与护栏。' },
      { id: 'aiv1-c7', tag: '成本', q: '降低大模型调用成本的有效手段包括？（多选）',
        options: ['批量接口（batch）以更低价格异步处理非实时请求', '缓存高频/相似查询的结果（语义缓存）', '用更大模型处理所有请求以保质量', '蒸馏/路由：简单问题走小模型，复杂问题才上大模型'],
        answer: ['A', 'B', 'D'], multi: true, explain: '降本组合：batch 异步走折扣价、语义缓存命中免推理、模型路由（小模型扛量、大模型兜底难例）、以及收紧上下文与输出长度。盲目全用大模型反而最贵。' },
      { id: 'aiv1-c8', tag: '延迟', q: '关于降低大模型首字延迟（TTFT），下列说法正确的是？',
        options: ['TTFT 只取决于输出长度', '流式输出（streaming）让用户更早看到首个 token；预填充阶段可用 Prompt Caching 减少等待', 'TTFT 与输入长度无关', '必须等全部生成完才返回'],
        answer: ['B'], explain: 'TTFT 主要受输入预填充耗时影响；Prompt Caching 命中可省去重复预填充，流式输出使首个 token 尽快抵达、提升体感。输入越长、模型越大，预填充越慢。' },
      { id: 'aiv1-c9', tag: '向量库', q: '关于向量检索索引，HNSW 与 IVF 的区别，正确的是？',
        options: ['两者都是精确最近邻，无近似', 'HNSW 基于图、召回高且查询快但内存占用大；IVF 基于倒排聚类、内存小但需调 nprobe 平衡召回与速度', 'IVF 无法用于大规模', 'HNSW 不占内存'],
        answer: ['B'], explain: 'HNSW（分层可导航小世界图）查询快、召回高，但需常驻内存、构建慢；IVF（倒排文件）按聚类分桶、内存友好，靠 nprobe 控制查多少桶来权衡召回/延迟。选型看规模与延迟要求。' },
      { id: 'aiv1-c10', tag: 'RAGvs微调', q: '关于微调（Fine-tuning）与 RAG 的取舍，下列说法正确的是？',
        options: ['RAG 永远优于微调', 'RAG 适合注入「频繁变化的事实/私有知识」；微调适合固化「稳定的风格/格式/能力」，二者可组合', '微调适合注入最新新闻', 'RAG 无法结合模型能力'],
        answer: ['B'], explain: 'RAG 把外部知识检索进上下文，适合易变/专有事实且可溯源；微调改变模型权重，适合稳定风格、特定任务格式、难例能力，但知识会过时。生产中常以 RAG 为主、微调为辅。' },
      { id: 'aiv1-c11', tag: '并行调用', q: '关于大模型的函数调用（tool/function calling），下列说法正确的是？',
        options: ['模型只能串行调用工具，无法并行', '支持并行工具调用时，彼此独立的调用应并发执行以省时延；需对单个调用设超时与错误隔离', '函数调用不需要 schema 描述', '工具返回无需回灌模型'],
        answer: ['B'], explain: '并行工具调用可让无依赖的查询同时执行、缩短总时延；实现上需并发控制、单调用超时与隔离，避免一个慢/失败工具拖垮整体，并将结果汇总回灌模型继续推理。' },
      { id: 'aiv1-c12', tag: '长上下文', q: '关于长上下文的「中间遗忘（lost in the middle）」现象，下列说法正确的是？',
        options: ['模型对长文档任意位置的信息利用率完全一致', '模型常在长上下文的首尾利用更好、中间信息易被忽略，故关键指令放首尾、长文档宜检索分段而非全量塞入', '只要上下文够长，检索就不需要', 'lost in middle 只在小模型出现'],
        answer: ['B'], explain: '研究表明模型对长上下文中段信息的利用率偏低（首尾更强）。实务上把系统指令置于首尾、用检索把最相关片段带入上下文，比盲目拉长上下文更有效且更省。' },
      { id: 'aiv1-c13', tag: '护栏', q: '防御用户套取系统提示（system prompt extraction）的措施包括？',
        options: ['把系统提示明文写在前端', '将系统指令与不可信用户输入在语义/结构上隔离，对越权请求做拒绝，并对输出做护栏检测是否泄露内部指令', '完全不写系统提示', '允许用户直接编辑系统提示'],
        answer: ['B'], explain: '提示提取攻击试图让模型吐出隐藏指令。防护：指令与用户输入分层、最小权限、用护栏/分类器识别越权索取、对输出做敏感信息过滤，并在越权时明确拒绝而非复述。' },
      { id: 'aiv1-c14', tag: 'RAG评估', q: '评估 RAG 答案质量时，Faithfulness（忠实度）衡量的是？',
        options: ['答案是否流畅', '答案是否完全由检索到的上下文支撑、无臆造（hallucination）', '答案长度是否够长', '检索速度是否快'],
        answer: ['B'], explain: 'Faithfulness 衡量生成答案是否被检索上下文所支撑、未凭空捏造；Answer Relevance 衡量是否切题；Context Relevance 衡量检索段落是否相关。三者共同刻画 RAG 端到端质量。' },
      { id: 'aiv1-c15', tag: '多智能体', q: '关于多智能体（Multi-Agent）编排，下列说法正确的是？',
        options: ['多智能体必然比单智能体更差', '常见模式有主管（supervisor）调度子智能体、或辩论/评审协作；需控制通信开销与收敛条件，避免无限协商', '多智能体之间不能共享上下文', '多智能体不需要 orchestrator'],
        answer: ['B'], explain: '多智能体通过角色分工（如规划/检索/编码/评审）提升复杂任务质量；supervisor 负责派发与汇总，辩论模式相互校验。需设终止条件与成本上限，防止无谓循环与开销爆炸。' },
      { id: 'aiv1-c16', tag: 'KV缓存', q: '关于推理中的 KV Cache，下列说法正确的是？',
        options: ['KV Cache 在每个请求都从零计算、无法复用', 'KV Cache 缓存已计算的自/交叉注意力键值，多轮对话复用历史前缀可省重算；Prompt Caching 本质即持久化该缓存', 'KV Cache 只占用磁盘', 'KV Cache 与上下文长度无关'],
        answer: ['B'], explain: '自回归生成时每 token 需历史 K/V；KV Cache 将其缓存避免重算，显存随上下文线性增长。多轮对话复用前缀的 KV 即省算力，厂商的 Prompt Caching 是对该缓存的持久化与复用。' },
      { id: 'aiv1-c17', tag: '可观测', q: '关于大模型应用的可观测性，应重点追踪的指标包括？',
        options: ['只需追踪服务器 CPU', '应追踪 token 用量与成本、TTFT/TPOT 延迟、错误率、缓存命中率、以及按用户/场景的归因', '无需追踪成本', '只需追踪数据库 QPS'],
        answer: ['B'], explain: 'LLM 可观测需覆盖成本（token/单价）、延迟（TTFT 首字、TPOT 逐字）、质量（评分/回归）、缓存命中与失败率，并支持按租户/场景下钻，才能定位贵/慢/错的来源。' },
      { id: 'aiv1-c18', tag: '推理服务', q: '关于推理服务优化（如 vLLM / TGI），核心手段是？',
        options: ['仅依靠单请求串行', '通过连续批处理（continuous batching）、PagedAttention 等提升 GPU 利用率与吞吐，降低单位请求成本', '关闭所有批处理', '推理服务无法优化吞吐'],
        answer: ['B'], explain: 'vLLM 等用 continuous batching 把不同请求的步拼批、PagedAttention 高效管理 KV 显存分页，显著提升吞吐、压低延迟与单请求成本；是规模化部署 LLM 的关键。' },
      { id: 'aiv1-c19', tag: '评测平台', q: '构建 LLM 评测平台（eval harness）时，正确的做法是？',
        options: ['只在上线当天测一次', '维护黄金集（golden set）与自动化用例，每次模型/提示变更跑回归，关注质量指标与成本的联合变化', '评测完全靠主观感觉', '不需要版本化提示词'],
        answer: ['B'], explain: '稳健的评测靠固化黄金集与可复跑用例，对每次提示/模型变更做回归，对比质量与成本曲线，防止「优化一项、退化另一项」。提示词应版本化以便追溯。' },
      { id: 'aiv1-c20', tag: '合规', q: '关于企业落地 LLM 的合规与隐私，下列说法正确的是？',
        options: ['所有数据都可无差别发往第三方大模型', '应对 PII 做脱敏/不出域，敏感数据走私有化或合规通道，并建立审计与拒绝策略', '合规只在金融行业的约束', '无需告知用户正在使用 AI'],
        answer: ['B'], explain: '企业落地需数据分级：PII 脱敏或留在私有环境，敏感场景用私有化/合规 API，配审计日志与越权拒绝；并在面向用户时尽到 AI 使用告知义务。合规是跨行业的普适要求。' }
    ],
    written: [
      { id: 'aiv1-w1', q: '设计一个生产级 RAG 流水线：覆盖切分策略、向量化与存储、检索与重排序、生成与引用，并定义 Faithfulness/Answer Relevance 评测与回归方法。',
        points: ['切分：结构感知 + overlap，按内容类型调大小', '向量化：选模型、归一化、批量入库', '检索：向量召回 Top-k + 元数据过滤', '重排：cross-encoder rerank 提升相关性', '生成：带引用、约束不臆造', '评测：Faithfulness/Answer Relevance + 黄金集回归'],
        reference: '流水线：①文档解析→结构感知切分（按标题/段落，overlap 10-20%）→选 embedding 模型批量向量化入库（HNSW）。②检索：向量 Top-k + 业务元数据过滤。③重排：用 cross-encoder 对候选 rerank 取 Top-3。④生成：把片段带引用拼接进 prompt，要求模型标注来源、禁止超上下文臆造。⑤评测：用 LLM-judge 或规则算 Faithfulness（答案是否由上下文支撑）与 Answer Relevance，每次变更跑黄金集回归防止退化。' },
      { id: 'aiv1-w2', q: '实现一个带工具调用的 Agent 循环（伪代码）：含规划、并行/串行工具执行、超时重试、结果校验、步数上限与最终综合，说明如何防止无限循环与单点失败。',
        points: ['循环：思考→调用→观察，直到完成或达步数上限', '并行：无依赖工具并发执行', '超时/重试：单工具设 timeout 与有限重试', '校验：解析工具返回，异常走兜底', '步数上限 + 预算上限防失控'],
        reference: 'for step in range(MAX_STEPS): plan = llm(history); if plan.done: break; calls = plan.tool_calls; results = parallel(calls, timeout=T, retries=2); for r in results: if r.error: r = fallback(call) or mark_failed; history.append(obs=r); if budget_exceeded: break; final = llm(history + "综合答案"). 防失控：MAX_STEPS + token 预算 + 单工具超时；防单点失败：错误隔离，个别工具失败不影响整体，最终由模型综合已有观察作答。' },
      { id: 'aiv1-w3', q: '设计一套大模型护栏（guardrails）：防御提示注入与系统提示提取、对输出做敏感信息过滤与越权拒绝，说明在哪些环节拦截（入口/模型/出口）。',
        points: ['入口：输入分类/越权检测、隔离不可信内容', '模型层：最小权限指令、结构化分隔符', '出口：PII 过滤、敏感词/泄露检测、越权拒绝', '可观测：记录拦截与降级', '多层纵深防御'],
        reference: '纵深：①入口对用户输入做分类与注入检测，把不可信内容与系统指令用清晰分隔符隔离、明确标注边界。②模型层用最小权限指令，禁止模型复述系统提示。③出口对生成做 PII 脱敏（正则/NER）、敏感信息/提示泄露检测、越权内容拒绝。④可观测记录拦截率与误杀，持续调阈值。任何一层命中即拦截或降级回复。' },
      { id: 'aiv1-w4', q: '针对一个生产聊天机器人，给出至少 5 条降低 LLM 成本与延迟的工程措施（含缓存、路由、Prompt Caching、流式、输出约束），并说明各自适用场景。',
        points: ['语义缓存：命中相似问题免推理', '模型路由：简单走小模型', 'Prompt Caching：稳定前缀缓存 KV', '流式：降 TTFT 体感', '输出约束：限制 max_tokens/结构化', '批量：非实时走 batch 折扣'],
        reference: '①语义缓存：对相似问题哈希/向量检索命中则直接返回，省推理（适合 FAQ 类）。②模型路由：先用小模型判难度，简单问题小模型答、难问题才上大模型。③Prompt Caching：系统提示/知识库前缀稳定，缓存 KV 降输入成本与 TTFT。④流式输出：首字即达，体感更快。⑤输出约束：设合理 max_tokens、要求 JSON 以减少冗余。⑥非实时任务（摘要/打标）走 batch 异步享折扣价。' },
      { id: 'aiv1-w5', q: '构建 LLM 评测体系：定义指标（质量/成本/延迟/安全）、黄金集与回归流程、人工抽检校准 LLM-as-judge 偏差的方法。',
        points: ['指标：质量( Faithfulness/相关)、成本(token)、延迟(TTFT/TPOT)、安全(拒答率)', '黄金集：覆盖典型与边界用例、带标准答案', '回归：每次变更跑全集、对比基线', '校准：人工抽检 + 多裁判交叉', '看板：质量-成本联合曲线'],
        reference: '指标四维：质量（Faithfulness/Answer Relevance/人工评分）、成本（输入/输出 token 与单价）、延迟（TTFT/TPOT/p99）、安全（越权拒答率、注入防御率）。黄金集覆盖高频与对抗样本，附标准答案/评分要点。回归：每次模型或提示变更全量跑、与基线 diff 报警。校准 LLM-judge：定期人工抽检样本、用多模型交叉裁判、统计位置/长度/自我偏好偏差并修正判分 prompt。' }
    ]
  }
]

let added = 0
vipSets.forEach((vs) => {
  if (!s.examSets.find((x) => x.id === vs.id)) { s.examSets.push(vs); added++ }
})

fs.writeFileSync(SEED, JSON.stringify(s, null, 2) + '\n')
console.log(`done: 修复 choice id ${fixedChoices} 个、written id ${fixedWritten} 个；新增 VIP 卷 ${added} 套；当前 examSets 共 ${s.examSets.length} 套`)
