// be-web 内容补齐 Batch 3：Go 测试/部署/gRPC + Python 测试/部署/异步任务
// 说明：content 用「行数组 + join(NL)」构建，NL 取自 String.fromCharCode(10)，
// 源码中不出现 \n 字面量 —— 避免编辑器/工具把 \n 误写成真实换行导致 JS 字符串断行（Batch 2 曾踩此坑）。
const NL = String.fromCharCode(10)

export const BATCH3 = [
  {
    id: 'go-c6', subtrack: 'go', position: 109,
    title: 'Go 测试与质量保障',
    goal: '掌握表驱动测试、基准测试、testify 与覆盖率，写出可信赖的 Go 代码。',
    sections: [
      {
        id: 'go-c6-s1', title: '表驱动测试',
        direction: '用切片组织用例，循环执行同一断言逻辑。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **基本结构**：`func TestXxx(t *testing.T)`，函数名以 `Test` 开头、首字母大写。[testing 包](https://pkg.go.dev/testing)',
          '- **表驱动**：`tests := []struct{ in string; want int }{...}`，再 `for _, tt := range tests { t.Run(tt.in, func(t *testing.T){ ... }) }`。[Add a test 教程](https://go.dev/doc/tutorial/add-a-test)',
          '- **子测试**：`t.Run(name, fn)` 让每个用例独立报告成败，某个失败时其余照常执行，并支持 `-run TestX/子名` 精准运行。',
          '',
          '## 常见坑',
          '',
          '- **忘记调用 t.Helper()**：在断言辅助函数里调用 `t.Helper()`，失败行号才会指向调用方而不是辅助函数内部。',
          '- **共享可变状态**：表驱动用例若共享同一切片/map，配合 `t.Parallel()` 会互相干扰，用例内应自建副本。',
          '',
          '## 动手自测',
          '',
          '```go',
          'func TestAdd(t *testing.T) {',
          '  cases := []struct{ a, b, want int }{{1, 2, 3}, {0, 0, 0}}',
          '  for _, c := range cases {',
          '    if got := Add(c.a, c.b); got != c.want {',
          '      t.Errorf("Add(%d,%d)=%d want %d", c.a, c.b, got, c.want)',
          '    }',
          '  }',
          '}',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么表驱动优于复制粘贴？**（答：用例即数据，新增零成本、审阅直观、失败定位清晰）',
          '- **t.Run 有什么用？**（答：隔离子测试、独立命名、支持并行与选择性运行）'
        ].join(NL)
      },
      {
        id: 'go-c6-s2', title: '基准与覆盖率',
        direction: '用 go test -bench 量化性能，用 -cover 看覆盖盲区。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **基准函数**：`func BenchmarkXxx(b *testing.B)`，循环体写成 `for i := 0; i < b.N; i++ { ... }`，N 由框架自适应决定。[Benchmark 指南](https://go.dev/doc/tutorial/add-a-test)',
          '- **覆盖率**：`go test -cover` 看总比例；`go test -coverprofile=c.out && go tool cover -html=c.out` 可视化盲区。',
          '- **内存观测**：`b.ReportAllocs()` 报告每次操作的分配次数与字节数，定位内存热点。',
          '',
          '## 常见坑',
          '',
          '- **基准里含预热无关代码**：用 `b.ResetTimer()` 排除初始化耗时，否则数据严重失真。',
          '- **只追高覆盖率数字**：100% 行覆盖也可能漏掉并发与错误分支，覆盖率不是正确性证明。',
          '',
          '## 动手自测',
          '',
          '```go',
          'func BenchmarkAdd(b *testing.B) {',
          '  for i := 0; i < b.N; i++ { Add(1, 2) }',
          '}',
          '// go test -bench=. -benchmem',
          '```',
          '',
          '## 面试视角',
          '',
          '- **基准测试能证明什么、不能证明什么？**（答：能发现显著回退，不能替代真实压测与 profiling）',
          '- **覆盖率 100% 是否足够？**（答：不足够，仍需针对错误路径与并发做针对性测试）'
        ].join(NL)
      },
      {
        id: 'go-c6-s3', title: 'testify 与 mock',
        direction: '用 testify 的 assert/require 减少样板，用接口隔离做 mock。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **assert 与 require**：`assert` 失败后用例继续，`require` 失败即刻终止，前置条件用后者。[testify](https://github.com/stretchr/testify)',
          '- **接口即契约**：Go 的隐式接口让 mock 极简——定义 `type Store interface{ Get(id int) (Item, error) }`，测试时传一个内存实现即可。',
          '- **gomock**：为接口生成 mock，用 `EXPECT().Get(1).Return(item, nil)` 设定并自动验证调用参数与次数。',
          '',
          '## 常见坑',
          '',
          '- **过度 mock 导致测的是 mock 而非逻辑**：只 mock 真正有副作用的边界（DB/HTTP/时间），纯函数直接测。',
          '- **mock 期望未设 Times**：默认语义是“至少一次”，漏设会让“调用压根没发生”这类缺陷被放过。',
          '',
          '## 动手自测',
          '',
          '```go',
          'type fakeStore struct{ m map[int]Item }',
          'func (f fakeStore) Get(id int) (Item, error) { return f.m[id], nil }',
          '',
          'func TestSvc(t *testing.T) {',
          '  s := NewSvc(fakeStore{m: map[int]Item{1: {Name: "x"}}})',
          '  assert.NoError(t, s.Do(1))',
          '}',
          '```',
          '',
          '## 面试视角',
          '',
          '- **Go 为什么推崇用接口做测试替身？**（答：接口隐式实现，无需代码生成即可注入假实现，解耦清晰）',
          '- **mock 与 fake 的区别？**（答：mock 验证交互行为是否被正确调用，fake 是轻量可用实现；依场景选）'
        ].join(NL)
      },
      {
        id: 'go-c6-s4', title: '集成与 CI 测试策略',
        direction: '用 build tag 隔离重型测试，设计分层测试金字塔。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **build tag**：文件首行写 `//go:build integration`，只有 `go test -tags=integration` 才编译运行。[Build constraints](https://pkg.go.dev/cmd/go#hdr-Build_constraints)',
          '- **临时资源**：用 `t.TempDir()` 拿一个用例结束后自动清理的临时目录，避免互相污染。',
          '- **外部服务桩**：用 `httptest.NewServer(handler)` 起内存 HTTP 服务，不依赖真实网络与端口。',
          '',
          '## 常见坑',
          '',
          '- **集成测试依赖固定端口/全局状态**：并行跑时互相踩，改用随机端口或 `t.TempDir()`。',
          '- **CI 漏跑集成 tag**：流水线里单测与集成应分成不同步骤，各自用对应的 `-tags` 触发。',
          '',
          '## 动手自测',
          '',
          '```go',
          '//go:build integration',
          '',
          'package main',
          '',
          'func TestE2E(t *testing.T) {',
          '  srv := httptest.NewServer(handler())',
          '  defer srv.Close()',
          '  // ... 对 srv.URL 发起真实 HTTP 调用',
          '}',
          '```',
          '',
          '## 面试视角',
          '',
          '- **测试金字塔的意义？**（答：单测多而快、集成/端到端少而慢，整体反馈快、维护成本低）',
          '- **build tag 在测试中怎么用？**（答：隔离重型或依赖外部的测试，按需用 -tags 触发）'
        ].join(NL)
      }
    ]
  },
  {
    id: 'go-c7', subtrack: 'go', position: 110,
    title: '容器化与部署',
    goal: '用多阶段 Dockerfile 构建极小镜像，理解容器编排与优雅发布的完整链路。',
    sections: [
      {
        id: 'go-c7-s1', title: '多阶段 Docker 构建',
        direction: '用 builder 阶段编译，运行时只拷二进制，镜像可小到数 MB。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **两阶段**：`FROM golang:1.22 AS builder` 负责编译，`FROM gcr.io/distroless/static` 只放产物。[Docker 多阶段构建](https://docs.docker.com/build/building/multi-stage/)',
          '- **静态链接**：编译加 `-ldflags "-s -w"` 去除符号与调试信息，配合 `CGO_ENABLED=0` 产出纯静态二进制，可直接跑在 `scratch`。',
          '- **构建上下文**：写 `.dockerignore` 排除 `vendor`/`.git`/本地二进制，避免无谓传输拖慢构建。',
          '',
          '## 常见坑',
          '',
          '- **CGO 开启导致 scratch 缺 libc**：务必设 `CGO_ENABLED=0 GOOS=linux` 静��编译。',
          '- **时区与 CA 证书缺失**：distroless 镜像需额外拷贝 `ca-certificates.crt`，否则对外 HTTPS 请求全部失败。',
          '',
          '## 动手自测',
          '',
          '```dockerfile',
          'FROM golang:1.22 AS b',
          'WORKDIR /src',
          'COPY . .',
          'RUN CGO_ENABLED=0 go build -ldflags "-s -w" -o /app .',
          'FROM gcr.io/distroless/static',
          'COPY --from=b /app /app',
          'COPY --from=b /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/',
          'ENTRYPOINT ["/app"]',
          '```',
          '',
          '## 面试视角',
          '',
          '- **多阶段构建解决了什么？**（答：分离构建依赖与运行时依赖，大幅缩小镜像、减少攻击面）',
          '- **为什么 Go 能跑在 scratch？**（答：静态链接后无外部动态库依赖，不需要 libc）'
        ].join(NL)
      },
      {
        id: 'go-c7-s2', title: '配置与优雅退出',
        direction: '用环境变量注入配置，捕获信号做优雅关闭。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **信号捕获**：`sig := make(chan os.Signal, 1); signal.Notify(sig, syscall.SIGTERM)`，收到后触发关闭流程。[signal 包](https://pkg.go.dev/os/signal)',
          '- **优雅关闭**：`http.Server.Shutdown(ctx)` 停止接受新连接并等待活跃连接结束；`Close()` 则是立即切断。',
          '- **配置注入**：`os.Getenv` 读取，或用 `viper`/`envconfig` 统一管理，区分必填项与默认值。',
          '',
          '## 常见坑',
          '',
          '- **只 ListenAndServe 不处理信号**：Pod 被删除时请求被硬切断，客户端报错、事务中断。',
          '- **Shutdown 无超时 ctx**：必须用 `context.WithTimeout` 兜底，否则个别长连接会让进程永久挂起。',
          '',
          '## 动手自测',
          '',
          '```go',
          'srv := &http.Server{Addr: ":8080"}',
          'go srv.ListenAndServe()',
          'sig := make(chan os.Signal, 1)',
          'signal.Notify(sig, syscall.SIGTERM)',
          '<-sig',
          'ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)',
          'defer cancel()',
          'srv.Shutdown(ctx)',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么需要优雅退出？**（答：避免请求中断、连接泄漏与消息丢失，保证发布平滑）',
          '- **Shutdown 与 Close 的区别？**（答：Shutdown 优雅等待活跃请求完成；Close 立即切断所有连接）'
        ].join(NL)
      },
      {
        id: 'go-c7-s3', title: 'Kubernetes 基础编排',
        direction: '用 Deployment/Service 描述无状态服务，理解探针与滚动更新。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **Deployment**：声明 `replicas`、`image`、`resources` 等期望状态，控制器负责维持。[Deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)',
          '- **探针三件套**：`livenessProbe` 失败会重启容器、`readinessProbe` 通过才接流量、`startupProbe` 防止慢启动被误杀。',
          '- **滚动更新**：`strategy.rollingUpdate` 的 `maxSurge`/`maxUnavailable` 控制新旧副本比例，实现零停机发布。',
          '',
          '## 常见坑',
          '',
          '- **探针路径未就绪就接流量**：readiness 必须等依赖（DB、缓存预热）连通后再放行，否则发布期报错率飙升。',
          '- **没设 resources limits**：单个 Pod 吃满节点资源，会触发驱逐连锁反应。',
          '',
          '## 动手自测',
          '',
          '```yaml',
          'livenessProbe:',
          '  httpGet: { path: /healthz, port: 8080 }',
          '  initialDelaySeconds: 5',
          'readinessProbe:',
          '  httpGet: { path: /ready, port: 8080 }',
          '```',
          '',
          '## 面试视角',
          '',
          '- **liveness 与 readiness 的区别？**（答：liveness 决定是否重启容器，readiness 决定是否接入流量）',
          '- **滚动更新如何做到零停机？**（答：逐步替换副本，新 Pod ready 后才切流量、再退旧 Pod）'
        ].join(NL)
      },
      {
        id: 'go-c7-s4', title: '可观测性入门',
        direction: '接入结构化日志、指标与链路追踪，建立发布后的仪表盘。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **结构化日志**：Go 1.21+ 标准库 `log/slog` 输出 JSON，便于采集与过滤。[slog](https://pkg.go.dev/log/slog)',
          '- **指标**：Prometheus 定时拉取 `/metrics` 端点，用 Counter/Histogram 记录请求量与延迟分布。',
          '- **追踪**：OpenTelemetry 注入 traceID 并跨服务透传，Go SDK 对 HTTP/gRPC 提供自动埋点。',
          '',
          '## 常见坑',
          '',
          '- **日志打敏感字段**：请求体、令牌进日志即成泄露源，必须脱敏。',
          '- **指标维度爆炸**：把 user_id 这类高基数标签放进 label，会让时间序列数量失控、拖垮 Prometheus。',
          '',
          '## 动手自测',
          '',
          '```go',
          'logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))',
          'slog.SetDefault(logger)',
          'slog.Info("request", "path", r.URL.Path, "latency_ms", 12)',
          '```',
          '',
          '## 面试视角',
          '',
          '- **日志/指标/追踪各自解决什么？**（答：日志查离散事件、指标看趋势与告警、追踪定位跨服务瓶颈）',
          '- **高基数 label 为什么危险？**（答：时间序列数量爆炸，存储与查询成本急剧上升）'
        ].join(NL)
      }
    ]
  },
  {
    id: 'go-c8', subtrack: 'go', position: 111,
    title: '微服务与 gRPC',
    goal: '用 Protobuf 定义契约，搭建 gRPC 服务与客户端，理解微服务边界。',
    sections: [
      {
        id: 'go-c8-s1', title: 'Protobuf 契约定义',
        direction: '用 .proto 描述服务与消息，生成强类型代码。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **message 与 service**：`message User { int64 id = 1; string name = 2; }`；`service UserSvc { rpc Get(GetReq) returns (User); }`。[Protobuf 指南](https://protobuf.dev/getting-started/)',
          '- **字段编号**：`=1`、`=2` 是二进制线格式里的稳定标识，增删字段必须保留旧编号才能向后兼容。',
          '- **代码生成**：`protoc --go_out=. --go-grpc_out=. *.proto` 产出 `.pb.go` 与 gRPC Stub。',
          '',
          '## 常见坑',
          '',
          '- **改字段编号破坏兼容**：编号一经使用不可复用，删除字段应标 `reserved` 占位。',
          '- **把业务逻辑写进 proto**：proto 只描述数据结构与服务签名，行为应在服务端实现。',
          '',
          '## 动手自测',
          '',
          '```protobuf',
          'syntax = "proto3";',
          'package api;',
          'service Greeter { rpc Hello(HelloReq) returns (HelloResp); }',
          'message HelloReq  { string name = 1; }',
          'message HelloResp { string msg  = 1; }',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么用 Protobuf 而非 JSON？**（答：二进制紧凑、强类型契约、向前兼容、跨语言）',
          '- **字段编号为什么不能改？**（答：线格式靠编号定位字段，改编号等于破坏老客户端）'
        ].join(NL)
      },
      {
        id: 'go-c8-s2', title: 'gRPC 服务端与客户端',
        direction: '实现生成的服务接口并启动 Server，客户端用 Stub 调用。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **服务端**：`s := grpc.NewServer()` → `pb.RegisterGreeterServer(s, &svc{})` → `s.Serve(lis)`。[Go 快速开始](https://grpc.io/docs/languages/go/quickstart/)',
          '- **客户端**：`conn, _ := grpc.Dial(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))`，再 `client := pb.NewGreeterClient(conn)`。',
          '- **拦截器**：`grpc.UnaryInterceptor` 统一做认证、日志、限流与追踪，避免每个方法重复。',
          '',
          '## 常见坑',
          '',
          '- **忘记调用 s.Serve 或连接未 Close**：前者请求无响应，后者连接泄漏。',
          '- **生产使用 insecure 凭证**：线上必须 `credentials.NewTLS` 开启 TLS/mTLS。',
          '',
          '## 动手自测',
          '',
          '```go',
          'type svc struct{ pb.UnimplementedGreeterServer }',
          '',
          'func (s *svc) Hello(ctx context.Context, in *pb.HelloReq) (*pb.HelloResp, error) {',
          '  return &pb.HelloResp{Msg: "hi " + in.Name}, nil',
          '}',
          '```',
          '',
          '## 面试视角',
          '',
          '- **gRPC 相比 REST 的优势？**（答：强类型契约、HTTP/2 多路复用、支持双向流、序列化更高效）',
          '- **拦截器能做什么？**（答：统一认证、日志、限流、追踪，避免每个方法重复实现）'
        ].join(NL)
      },
      {
        id: 'go-c8-s3', title: '错误处理与状态码',
        direction: '用 status 包返回标准 gRPC 状态码，客户端按码分支。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **返回错误**：`return nil, status.Error(codes.NotFound, "user not found")`。[status 包](https://pkg.go.dev/google.golang.org/grpc/status)',
          '- **客户端判码**：`st, ok := status.FromError(err); if st.Code() == codes.NotFound { ... }`。',
          '- **标准码语义**：`OK`/`InvalidArgument`/`NotFound`/`AlreadyExists`/`PermissionDenied`/`Internal` 各自含义明确。',
          '',
          '## 常见坑',
          '',
          '- **直接返回裸 Go error**：客户端只会拿到 `codes.Unknown`，无法精确分支。',
          '- **把敏感信息塞进错误消息**：错误会透传给调用方，必须脱敏。',
          '',
          '## 动手自测',
          '',
          '```go',
          'if u == nil {',
          '  return nil, status.Errorf(codes.NotFound, "user %d", id)',
          '}',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么用语义状态码而非 HTTP 码？**（答：跨传输层一致、语义明确、便于客户端分支处理）',
          '- **status details 有什么用？**（答：携带结构化错误上下文，如字段校验失败清单）'
        ].join(NL)
      },
      {
        id: 'go-c8-s4', title: '微服务边界与通信',
        direction: '理解服务拆分原则，以及同步 gRPC 与异步消息的取舍。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **拆分原则**：单一职责、数据自治、与团队边界对齐（康威定律）。',
          '- **同步 gRPC**：适合强一致、低延迟的内部调用，语义直观。',
          '- **异步消息**：Kafka/RabbitMQ 做事件驱动，削峰填谷、解耦多消费者。',
          '',
          '## 常见坑',
          '',
          '- **分布式单体**：服务间通过共享库或共享数据表紧耦合，拆了等于没拆。',
          '- **同步调用链过长**：A→B→C→D 同步串联，尾延迟叠加且一处故障全链瘫痪，应改异步或加超时与熔断。',
          '',
          '## 动手自测',
          '',
          '```go',
          '// 同步获取用户，并对“不存在”做降级处理',
          'u, err := userCli.Get(ctx, &pb.GetReq{Id: id})',
          'if status.Code(err) == codes.NotFound { /* 走默认用户降级 */ }',
          '```',
          '',
          '## 面试视角',
          '',
          '- **什么时候用异步消息而非同步 RPC？**（答：调用方不需即时结果、需要削峰、需要解耦多消费者时）',
          '- **微服务最常见的反模式？**（答：分布式单体、同步长调用链、共享数据库）'
        ].join(NL)
      }
    ]
  },
  {
    id: 'py-c6', subtrack: 'python', position: 112,
    title: '测试与质量保障',
    goal: '用 pytest 组织用例、fixture 管理依赖、mock 隔离外部，保证代码可信。',
    sections: [
      {
        id: 'py-c6-s1', title: 'pytest 基础',
        direction: '用函数式用例与原生断言，享受极简测试体验。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **用例发现**：`test_*.py` 文件中的 `def test_x(): assert f() == 1` 会被自动收集。[pytest 入门](https://docs.pytest.org/en/stable/getting-started.html)',
          '- **参数化**：`@pytest.mark.parametrize("a,b,exp", [(1,2,3),(0,0,0)])` 一行生成多组用例。',
          '- **常用运行参数**：`pytest -q` 安静模式、`pytest -k 关键字` 按名筛选、`pytest -x` 首次失败即停。',
          '',
          '## 常见坑',
          '',
          '- **断言无消息难定位**：写成 `assert got == exp, f"got {got}"` 补上上下文。',
          '- **用例互相依赖执行顺序**：pytest 默认不保证顺序，每个用例必须能独立单跑。',
          '',
          '## 动手自测',
          '',
          '```python',
          'import pytest',
          '',
          '@pytest.mark.parametrize("a,b,exp", [(1, 2, 3), (0, 0, 0)])',
          'def test_add(a, b, exp):',
          '    assert add(a, b) == exp',
          '```',
          '',
          '## 面试视角',
          '',
          '- **pytest 相比 unittest 的优势？**（答：原生 assert、fixture 依赖注入、参数化、插件生态，样板代码少）',
          '- **参数化解决了什么？**（答：同一逻辑跑多组数据，新增用例零复制）'
        ].join(NL)
      },
      {
        id: 'py-c6-s2', title: 'fixture 与依赖管理',
        direction: '用 fixture 注入测试依赖，控制生命周期与复用。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **定义与注入**：`@pytest.fixture` 装饰一个函数，用例签名里写同名参数即可拿到返回值。[fixtures](https://docs.pytest.org/en/stable/how-to/fixtures.html)',
          '- **作用域**：`scope="function"`/`"module"`/`"session"` 控制创建与复用次数。',
          '- **清理**：用 `yield` 返回资源，`yield` 之后的代码在用例结束后执行，充当 teardown。',
          '',
          '## 常见坑',
          '',
          '- **手写临时路径不清理**：用内置 `tmp_path` fixture，它会自动分配并隔离临时目录。',
          '- **作用域选错导致串扰**：`session` 级共享的可变状态会在用例间互相污染。',
          '',
          '## 动手自测',
          '',
          '```python',
          '@pytest.fixture',
          'def client():',
          '    app = create_app()',
          '    with app.test_client() as c:',
          '        yield c',
          '',
          'def test_health(client):',
          '    assert client.get("/health").status_code == 200',
          '```',
          '',
          '## 面试视角',
          '',
          '- **fixture 相比 setUp/tearDown 的优势？**（答：依赖注入、作用域灵活、可组合复用、可读性强）',
          '- **yield fixture 的清理时机？**（答：yield 之后的代码在用例结束后运行，用于释放资源）'
        ].join(NL)
      },
      {
        id: 'py-c6-s3', title: 'mock 与异步测试',
        direction: '用 unittest.mock 隔离外部依赖，用 pytest-asyncio 测协程。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **打补丁**：`from unittest.mock import patch`，用 `with patch("mod.requests.get") as m:` 临时替换。[unittest.mock](https://docs.python.org/3/library/unittest.mock.html)',
          '- **断言调用**：`m.assert_called_once_with(url)` 验证调用参数与次数。',
          '- **异步用例**：安装 `pytest-asyncio` 后，用 `@pytest.mark.asyncio` 标记 `async def test_x()`。',
          '',
          '## 常见坑',
          '',
          '- **mock 路径打错**：必须 patch“被测试模块里导入后的名字”，而不是定义处的名字。',
          '- **异步用例未标 mark**：会被静默跳过或报事件循环相关错误。',
          '',
          '## 动手自测',
          '',
          '```python',
          'from unittest.mock import patch',
          '',
          'with patch("requests.get") as m:',
          '    m.return_value.json.return_value = {"ok": True}',
          '    assert fetch().ok',
          '```',
          '',
          '## 面试视角',
          '',
          '- **mock 应该用在哪一层？**（答：只 mock 真实副作用的边界如网络/DB；纯逻辑直接测）',
          '- **pytest-asyncio 做什么？**（答：为 async 测试提供事件循环与运行器）'
        ].join(NL)
      },
      {
        id: 'py-c6-s4', title: '覆盖率与 CI',
        direction: '用 pytest-cov 量化覆盖，设计金字塔式测试分层。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **覆盖率**：安装 `pytest-cov` 后执行 `pytest --cov=myapp --cov-report=html` 生成报告。[pytest-cov](https://pytest-cov.readthedocs.io/)',
          '- **CI 门禁**：流水线里用 `--cov-fail-under=80` 让覆盖率低于阈值时构建失败。',
          '- **分层**：单测隔离纯逻辑、集成测关键链路、端到端只保核心流程。',
          '',
          '## 常见坑',
          '',
          '- **为覆盖率数字补无意义断言**：覆盖不等于正确，需针对错误分支设计用例。',
          '- **集成测试依赖固定端口**：用随机端口或 test container，避免 CI 并行时冲突。',
          '',
          '## 动手自测',
          '',
          '```ini',
          '# pyproject.toml',
          '[tool.pytest.ini_options]',
          'addopts = "--cov=myapp --cov-report=term-missing"',
          '```',
          '',
          '## 面试视角',
          '',
          '- **覆盖率 100% 等于没 bug 吗？**（答：不等于，仍需针对错误路径与并发做专项测试）',
          '- **测试金字塔的意义？**（答：单测多而快、集成/端到端少而慢，反馈快、维护成本低）'
        ].join(NL)
      }
    ]
  },
  {
    id: 'py-c7', subtrack: 'python', position: 113,
    title: '容器化与部署',
    goal: '用 Docker 打包 Python 服务，理解 WSGI/ASGI 服务器与编排发布。',
    sections: [
      {
        id: 'py-c7-s1', title: 'Python 镜像构建',
        direction: '用虚拟环境与锁定依赖，构建可复现的精简镜像。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **基础镜像**：`FROM python:3.12-slim` 相比 full 版本体积小很多。[Docker 官方 Python 镜像](https://hub.docker.com/_/python)',
          '- **依赖隔离**：`python -m venv /opt/venv` 后 `pip install -r requirements.txt`，运行时用虚拟环境的解释器。',
          '- **非 root 运行**：`useradd` 创建普通用户后 `USER appuser`，减小容器提权风险。',
          '',
          '## 常见坑',
          '',
          '- **不锁版本导致漂移**：用 `pip freeze > requirements.txt` 固定版本，避免 latest 带来的暗坑。',
          '- **依赖装进系统 Python**：会污染镜像层且不利于缓存，务必使用 venv。',
          '',
          '## 动手自测',
          '',
          '```dockerfile',
          'FROM python:3.12-slim',
          'WORKDIR /app',
          'COPY requirements.txt .',
          'RUN python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt',
          'COPY . .',
          'CMD ["/opt/venv/bin/python", "-m", "app"]',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么用 slim 而非 full 镜像？**（答：体积小、层数少、攻击面低、构建与拉取更快）',
          '- **容器里还有必要用 venv 吗？**（答：有必要，隔离依赖层、利于构建缓存与结果复现）'
        ].join(NL)
      },
      {
        id: 'py-c7-s2', title: 'WSGI 与 ASGI 服务器',
        direction: '用 gunicorn/uvicorn 托管应用，理解同步与异步服务器的差异。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **组合用法**：`gunicorn -k uvicorn.workers.UvicornWorker -w 4 app:app` —— gunicorn 管多进程，uvicorn worker 跑 ASGI。[gunicorn 文档](https://docs.gunicorn.org/)',
          '- **workers 数量**：经验值 `2 * CPU + 1`，实际以压测结果为准。',
          '- **同步 vs 异步**：WSGI 每请求占用一个 worker 线程；ASGI 单 worker 用事件循环并发处理大量 IO 等待。',
          '',
          '## 常见坑',
          '',
          '- **FastAPI 用错 worker 类型**：异步应用必须用 `UvicornWorker`，否则退化为同步、丢失并发优势。',
          '- **workers 过多压垮内存**：每个 worker 独立加载模型与连接池，盲目加大会 OOM。',
          '',
          '## 动手自测',
          '',
          '```bash',
          'gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:8000 app:app',
          '```',
          '',
          '## 面试视角',
          '',
          '- **ASGI 相比 WSGI 多了什么？**（答：原生支持异步、WebSocket 与长连接，适配高并发 IO 场景）',
          '- **gunicorn 与 uvicorn 的关系？**（答：gunicorn 负责进程管理，uvicorn worker 负责执行 ASGI 应用）'
        ].join(NL)
      },
      {
        id: 'py-c7-s3', title: '优雅退出与信号',
        direction: '捕获 SIGTERM 完成在途请求，配合编排平滑发布。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **注册处理器**：`signal.signal(signal.SIGTERM, handler)` 捕获终止信号；ASGI 服务器（uvicorn）已内置该行为。',
          '- **uvicorn 行为**：收到 SIGTERM 后停止 accept 新连接，等待 `graceful_timeout` 后关闭。',
          '- **配合探针**：K8s 的 `readinessProbe` 未通过即摘除流量，与优雅退出配合完成无损发布。',
          '',
          '## 常见坑',
          '',
          '- **暴力 kill 丢请求**：直接 SIGKILL 或超时设置过短，在途事务会回滚或丢失。',
          '- **未设 readiness 就切流量**：依赖尚未就绪时新 Pod 已接流量，发布期报错率飙升。',
          '',
          '## 动手自测',
          '',
          '```python',
          'import signal',
          '',
          'stop = False',
          '',
          'def _h(signum, frame):',
          '    global stop',
          '    stop = True',
          '',
          'signal.signal(signal.SIGTERM, _h)',
          'while not stop:',
          '    handle_one()',
          '```',
          '',
          '## 面试视角',
          '',
          '- **优雅退出对发布的意义？**（答：零停机、不丢在途请求、配合滚动更新）',
          '- **SIGTERM 与 SIGKILL 区别？**（答：前者可被程序捕获做清理，后者立即强杀无法拦截）'
        ].join(NL)
      },
      {
        id: 'py-c7-s4', title: 'K8s 部署与探针',
        direction: '用 Deployment/Service 描述服务，配置探针与资源上限。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **Deployment**：声明 `replicas`、`image`、`resources.requests/limits`。[Deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)',
          '- **探针三件套**：`livenessProbe` 失败重启、`readinessProbe` 通过才接流量、`startupProbe` 防止慢启动被误杀。',
          '- **滚动更新**：`maxSurge`/`maxUnavailable` 控制新旧副本替换节奏。',
          '',
          '## 常见坑',
          '',
          '- **探针路径未就绪就接流量**：readiness 必须等数据库等依赖连通后再放行。',
          '- **无 resources.limits**：单个 Pod 吃满节点资源，引发驱逐连锁反应。',
          '',
          '## 动手自测',
          '',
          '```yaml',
          'readinessProbe:',
          '  httpGet: { path: /ready, port: 8000 }',
          '  initialDelaySeconds: 5',
          'livenessProbe:',
          '  httpGet: { path: /healthz, port: 8000 }',
          '```',
          '',
          '## 面试视角',
          '',
          '- **liveness 与 readiness 区别？**（答：liveness 决定是否重启容器，readiness 决定是否接入流量）',
          '- **HPA 怎么扩缩容？**（答：按 CPU 或自定义指标自动调整 replicas 数量）'
        ].join(NL)
      }
    ]
  },
  {
    id: 'py-c8', subtrack: 'python', position: 114,
    title: '微服务与异步任务',
    goal: '用 Celery/RQ 做异步任务，用消息队列解耦，理解 Python 微服务通信。',
    sections: [
      {
        id: 'py-c8-s1', title: '异步任务队列',
        direction: '用 Celery/RQ 把耗时操作移出请求链路。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **Celery**：`@app.task` 装饰函数，`send_mail.delay(uid)` 入队，worker 用 `celery -A proj worker` 消费。[Celery 文档](https://docs.celeryq.dev/)',
          '- **RQ**：更轻量的替代，`queue.enqueue(send_mail, uid)`，依赖 Redis 作为 broker。',
          '- **broker 角色**：Redis/RabbitMQ 做消息中转，彻底解耦生产者与消费者。',
          '',
          '## 常见坑',
          '',
          '- **任务里使用请求上下文**：worker 进程没有 request 对象，必要参数必须随任务显式传入。',
          '- **任务不幂等**：重试会导致重复发邮件或重复扣款，关键任务要做幂等设计或去重。',
          '',
          '## 动手自测',
          '',
          '```python',
          'from celery import Celery',
          '',
          "app = Celery('p', broker='redis://localhost/0')",
          '',
          '@app.task',
          'def send_mail(uid):',
          '    ...',
          '',
          'send_mail.delay(uid)',
          '```',
          '',
          '## 面试视角',
          '',
          '- **什么时候该用异步任务？**（答：耗时、可延迟、不需即时返回结果的操作，如发邮件、转码、出报表）',
          '- **任务重试如何保证幂等？**（答：用唯一任务 ID 去重，或让业务操作本身可重复执行）'
        ].join(NL)
      },
      {
        id: 'py-c8-s2', title: '消息队列解耦',
        direction: '用发布/订阅模式解耦服务，实现削峰填谷。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **Kafka / RabbitMQ**：前者是高吞吐日志流，后者提供灵活路由与确认机制。[RabbitMQ 教程](https://www.rabbitmq.com/tutorials)',
          '- **发布订阅**：订单服务发出 `OrderCreated`，库存、积分、通知各自订阅，互不影响。',
          '- **消费幂等**：同一条消息可能被重复投递，消费者需按业务键去重。',
          '',
          '## 常见坑',
          '',
          '- **消费者处理慢导致积压**：监控消费 lag，水平扩容消费者或对上游限流。',
          '- **消息丢失**：需开启持久化并在处理成功后再 ack，否则崩溃即丢消息。',
          '',
          '## 动手自测',
          '',
          '```python',
          '# 生产者：发布事件',
          'producer.publish("OrderCreated", json.dumps(order))',
          '',
          '# 消费者：订阅并处理',
          'def on_msg(body):',
          '    process(json.loads(body))',
          '```',
          '',
          '## 面试视角',
          '',
          '- **消息队列解决了什么问题？**（答：异步化、服务解耦、削峰填谷、易于横向扩展）',
          '- **如何防止重复消费？**（答：消费端做幂等，配合去重表或唯一键）'
        ].join(NL)
      },
      {
        id: 'py-c8-s3', title: '服务间 HTTP 通信',
        direction: '用 httpx 调用下游，做好超时、重试与熔断。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **httpx**：同时支持同步与异步，`timeout=5` 设超时，`limits` 控连接池。[httpx](https://www.python-httpx.org/)',
          '- **重试退避**：`tenacity` 的 `@retry(wait=wait_exponential(), stop=stop_after_attempt(3))`。',
          '- **熔断**：`pybreaker` 在错误率超阈值时快速失败，给下游留出恢复窗口。',
          '',
          '## 常见坑',
          '',
          '- **不设超时**：下游卡死会拖垮调用方的线程或协程池，故障沿调用链扩散。',
          '- **无退避的重试**：下游故障时制造请求风暴，把小故障放大成雪崩。',
          '',
          '## 动手自测',
          '',
          '```python',
          'import httpx',
          'import tenacity',
          '',
          '@tenacity.retry(stop=tenacity.stop_after_attempt(3), wait=tenacity.wait_exponential())',
          'def call_downstream():',
          '    return httpx.get("http://svc/api", timeout=5)',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么必须设超时？**（答：防止下游故障拖垮调用方资源，把故障局部化）',
          '- **重试为什么要用指数退避？**（答：给下游恢复时间，避免重试请求形成风暴）'
        ].join(NL)
      },
      {
        id: 'py-c8-s4', title: '微服务边界与数据自治',
        direction: '理解服务拆分、数据库私有与最终一致性。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方',
          '',
          '',
'## 核心知识点（锚定官方）',
          '',
          '- **数据库私有**：每个服务独享自己的库，别的服务只能通过 API 访问，杜绝隐式耦合。',
          '- **最终一致**：通过事件总线异步更新读模型，用户短暂看到旧值通常可以接受。',
          '- **Saga 模式**：长事务拆成一串本地事务加补偿动作，失败时逐步回滚已完成的步骤。',
          '',
          '## 常见坑',
          '',
          '- **分布式单体**：共享库或共享数据表导致“拆了等于没拆”，改一处仍要全量发布。',
          '- **强一致跨服务事务**：两阶段提交复杂且易错，能用最终一致就别强一致。',
          '',
          '## 动手自测',
          '',
          '```python',
          '# 订单服务发布事件，库存服务订阅后自行扣减（最终一致）',
          'producer.publish("OrderCreated", order_json)',
          '# 库存服务消费事件并更新自己的表',
          '```',
          '',
          '## 面试视角',
          '',
          '- **微服务最常见的反模式？**（答：分布式单体、共享数据库、过长的同步调用链）',
          '- **最终一致为什么常被接受？**（答：多数业务容忍短暂旧值，以此换取可用性与解耦）'
        ].join(NL)
      }
    ]
  }
]
