// be-web 内容补齐 Batch 4：Go/Python 各 +3 章（运行时与性能剖析 / 数据结构与算法 / 网络编程与 IO 模型）
// 这三类是 Java 骨架中 be-jvm+bw-c2、be-dsa、be-net 的对应项，也是 Go/Python 此前唯一未覆盖的主题域。
// 说明：content 用「行数组 + join(NL)」构建，NL 取自 String.fromCharCode(10)，
// 源码中不出现 \n 字面量 —— 避免编辑器/工具把 \n 误写成真实换行导致 JS 字符串断行（Batch 2 曾踩此坑）。
const NL = String.fromCharCode(10)

export const BATCH4 = [
  {
    id: 'go-c9', subtrack: 'go', position: 115,
    title: 'Go 运行时与性能剖析',
    goal: '理解 Go 的内存分配、GC 与 GMP 调度，能用 pprof 定位 CPU 与内存瓶颈。',
    sections: [
      {
        id: 'go-c9-s1', title: '内存分配与逃逸分析',
        direction: '理解栈/堆分配边界，用逃逸分析指导写法减少 GC 压力。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          '逃逸分析是**编译期的“去向判决”**：编译器判断一个变量出了函数作用域后还有没有人引用。没人引用就放栈上（函数返回即回收，零 GC 成本）；还有人引用就“逃逸”到堆上，交给 GC 管理。写法的细微差别（如返回指针、存入接口、闭包捕获）就会改变判决结果。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **逃逸分析**：`go build -gcflags="-m"` 打印每个变量的逃逸决策与理由。[逃逸分析](https://go.dev/doc/faq#stack_or_heap)',
          '- **常见逃逸场景**：返回局部变量指针、赋值给 `interface{}`、闭包捕获、切片/map 存入指针、发送进 channel。',
          '- **分配路径**：小对象走 per-P 的 mcache→mcentral→mheap 三级缓存，大对象（>32KB）直接从 heap 分配。',
          '',
          '## 常见坑',
          '',
          '- **为“性能”盲目避免指针**：小对象逃逸到堆未必更慢，Go 的分配器极快；先测量再优化。',
          '- **循环内反复分配**：把可复用的 `[]byte`/结构体提到循环外或放入 `sync.Pool`，能显著降低 GC 次数。',
          '',
          '## 动手自测',
          '',
          '```bash',
          'go build -gcflags="-m -m" ./...   # 查看逃逸分析详细理由',
          'go test -bench=. -benchmem        # 看 B/op 与 allocs/op 判断分配开销',
          '```',
          '',
          '## 面试视角',
          '',
          '- **逃逸分析在编译期还是运行期？**（答：编译期静态分析，运行时无额外开销）',
          '- **哪些写法会导致变量逃逸到堆？**（答：返回指针、装箱成接口、闭包捕获、跨 goroutine 共享）'
        ].join(NL)
      },
      {
        id: 'go-c9-s2', title: '垃圾回收与 GC 调优',
        direction: '理解三色标记与混合写屏障，用 GOGC 控制回收频率。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'Go 的 GC 是**“边扫地边营业”的并发三色标记清除**：起初全白，从根对象出发把可达对象标灰再转黑，全程与用户代码并发跑，只用极短的 STW（停止世界）做起止同步。混合写屏障保证并发期间新引用不会漏标，代价是几乎不需要长时间暂停。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **三色标记**：白（未访问）→ 灰（已发现待扫描）→ 黑（已扫描完）；结束时剩余白色即垃圾。',
          '- **混合写屏障**：GC 期间对指针写操作插入屏障，把被覆盖的旧对象与新引用对象标灰，避免漏标。[Go GC 指南](https://tip.golang.org/doc/gc-guide)',
          '- **GOGC**：`GOGC=100`（默认）表示下次 GC 的堆目标 = 当前存活堆 × 2；调大降低 GC 频率但增加内存占用，调小反之。`GOMEMLIMIT` 可设硬上限。',
          '',
          '## 常见坑',
          '',
          '- **把 GOGC 当万能药**：真正的优化是减少分配（复用对象、预分配容量），而非调参掩盖。',
          '- **忽略 GC 的 CPU 占用**：高并发下标记阶段会与业务争 CPU，需给容器留足 CPU 预算。',
          '',
          '## 动手自测',
          '',
          '```bash',
          'GODEBUG=gctrace=1 go run main.go   # 打印每次 GC 的耗时与堆变化',
          'GOGC=200 go run main.go            # 降低 GC 频率（以内存换 CPU）',
          '```',
          '',
          '## 面试视角',
          '',
          '- **Go GC 为什么停顿这么短？**（答：并发标记 + 混合写屏障，STW 仅用于起止同步）',
          '- **GOGC 调大有什么代价？**（答：GC 次数减少、CPU 占用降低，但堆峰值与内存占用上升）'
        ].join(NL)
      },
      {
        id: 'go-c9-s3', title: 'GMP 调度模型',
        direction: '理解 G/M/P 三者关系与调度时机，解释高并发的底层支撑。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'GMP 是**“任务、工人、工位”三层模型**：G 是要跑的 goroutine（任务），M 是操作系统线程（工人），P 是逻辑处理器（工位，持有可运行 G 队列）。工人必须占到工位才能干活，工位数量由 `GOMAXPROCS` 决定。goroutine 之所以轻，是因为它在用户态被复用调度，切换无需陷入内核。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **G/M/P**：P 的数量默认等于 CPU 核数，可通过 `runtime.GOMAXPROCS(n)` 调整。[调度器设计文档](https://go.dev/src/runtime/proc.go)',
          '- **调度时机**：`go` 关键字创建、系统调用返回、channel 阻塞、抢占（Go 1.14+ 支持异步抢占长循环）。',
          '- **系统调用处理**：G 陷入阻塞 syscall 时，M 与 P 分离（P 转交给其他 M），避免整个 P 被拖住。',
          '',
          '## 常见坑',
          '',
          '- **CPU 密集型任务设超大 GOMAXPROCS**：超过核数只会徒增调度开销，收益为负。',
          '- **CGO 调用阻塞 M**：大量 CGO 会占用 M，需留意 `runtime.NumGoroutine()` 与线程数异常增长。',
          '',
          '## 动手自测',
          '',
          '```go',
          'runtime.GOMAXPROCS(4)',
          'fmt.Println(runtime.NumGoroutine(), runtime.NumCPU())',
          '```',
          '',
          '## 面试视角',
          '',
          '- **goroutine 为什么比线程轻量？**（答：栈初始仅 2KB 且可动态伸缩，用户态调度免内核切换）',
          '- **系统调用阻塞时会发生什么？**（答：M 与 P 解绑，P 转交其他 M 继续跑别的 G）'
        ].join(NL)
      },
      {
        id: 'go-c9-s4', title: 'pprof 性能剖析',
        direction: '用 pprof 采集 CPU/内存/goroutine 画像，定位真实瓶颈。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'pprof 是**“给程序做 CT”**：CPU profile 按采样统计各函数耗时占比，heap profile 记录分配点的内存占用，goroutine profile 看协程堆积在哪一行。先采样、再定位、后优化——顺序颠倒就是拍脑袋。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **接入**：`import _ "net/http/pprof"` 暴露 `/debug/pprof/`，或用 `runtime/pprof` 写文件。[pprof 诊断](https://go.dev/doc/diagnostics)',
          '- **分析命令**：`go tool pprof -http=:8080 http://host/debug/pprof/profile?seconds=30`（CPU）；`/heap`（内存）；`/goroutine`（协程）。',
          '- **关键视图**：`top` 看热点函数、`flame graph` 看调用链、`list 函数名` 看逐行开销。',
          '',
          '## 常见坑',
          '',
          '- **优化前不采样**：凭直觉改代码常优化到非瓶颈处，度量先行。',
          '- **heap profile 只看 inuse 不看 alloc**：频繁分配但已回收的对象要用 `-alloc_space` 才看得到。',
          '',
          '## 动手自测',
          '',
          '```bash',
          'go tool pprof -top http://localhost:6060/debug/pprof/heap',
          'go tool pprof -http=:0 http://localhost:6060/debug/pprof/profile?seconds=30',
          '```',
          '',
          '## 面试视角',
          '',
          '- **线上服务如何定位 CPU 飙高？**（答：开启 pprof，采样 CPU profile，看 top/火焰图定位热点）',
          '- **inuse_space 与 alloc_space 的区别？**（答：前者是当前存活占用，后者是累计分配总量，查频繁分配用后者）'
        ].join(NL)
      }
    ]
  },
  {
    id: 'go-c10', subtrack: 'go', position: 116,
    title: 'Go 数据结构与算法',
    goal: '用 Go 标准库实现常用结构与算法，理解底层实现与复杂度取舍。',
    sections: [
      {
        id: 'go-c10-s1', title: '复杂度分析与切片底层',
        direction: '用大 O 度量增长趋势，理解 slice 的三要素与扩容策略。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '## 心智模型',
          '',
          '复杂度是**“输入翻倍时耗时的变化规律”**，它回答的是“规模变大还撑不撑得住”，而不是“这次跑了几毫秒”。切片则是**“一段连续内存上的视图”**，由指针、长度、容量三要素构成——`append` 超容量就搬家（重新分配并拷贝），这是很多隐性开销的来源。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **切片结构**：底层数组指针 + `len` + `cap`；`s[a:b]` 共享底层数组，改动会互相影响。[Go Slices 用法](https://go.dev/blog/slices-intro)',
          '- **扩容策略**：小切片（<256 元素）容量翻倍，大切片按约 1.25 倍增长，并对齐到内存规格；具体倍数属实现细节，不可依赖。',
          '- **预分配**：已知规模用 `make([]T, 0, n)` 预留容量，避免反复扩容拷贝。',
          '',
          '## 常见坑',
          '',
          '- **append 后原切片未共享新数组**：`a := append(b, x)` 若 b 容量足够会就地写入，可能改动他人数据；需独立副本时显式 copy。',
          '- **持有大数组的小切片导致内存泄漏**：`s := bigArr[:10]` 会让整个 bigArr 无法回收，需 `copy` 到新切片。',
          '',
          '## 动手自测',
          '',
          '```go',
          's := make([]int, 0, 1000)   // 预分配，避免多次扩容',
          'sub := make([]int, len(big[0:10])); copy(sub, big[0:10])  // 切断大数组引用',
          '```',
          '',
          '## 面试视角',
          '',
          '- **切片的 len 与 cap 区别？**（答：len 是当前元素数，cap 是底层数组可容纳数）',
          '- **为什么 append 有时会影响另一个切片？**（答：容量足够时共享底层数组就地写入）'
        ].join(NL)
      },
      {
        id: 'go-c10-s2', title: '线性结构：栈、队列与链表',
        direction: '用切片与 container/list 实现线性结构，理解各自适用场景。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '## 心智模型',
          '',
          '线性结构的差别是**“从哪端进出”**：栈只在顶端进出（后进先出，如函数调用、撤销操作）；队列一端进另一端出（先进先出，如任务排队）；链表则是**“用指针串起来的散装节点”**，插入删除 O(1) 但随机访问 O(n)、缓存不友好。Go 里绝大多数场景用切片即可，链表只在频繁中间插入时才值得。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **栈**：`append` 入栈、`s[len(s)-1]` 取顶、`s = s[:len(s)-1]` 出栈，均 O(1)。',
          '- **队列**：`container/list` 提供双向链表实现；环形队列可用定长切片 + 头尾指针，避免出队后的数据搬移。[container/list](https://pkg.go.dev/container/list)',
          '- **堆**：`container/heap` 需实现 `heap.Interface`（Len/Less/Swap/Push/Pop），常用于 Top-K 与优先队列。',
          '',
          '## 常见坑',
          '',
          '- **用 `s = s[1:]` 做队列出队**：底层数组被长期持有，内存无法回收，且反复切片会耗尽容量。',
          '- **忘记实现 heap.Interface 的全部方法**：编译期就会报错，注意 Push/Pop 操作的是底层切片而非元素本身。',
          '',
          '## 动手自测',
          '',
          '```go',
          '// 栈',
          'st = append(st, v); top := st[len(st)-1]; st = st[:len(st)-1]',
          '// 用堆求 Top-K',
          'h := &MinHeap{}; heap.Init(h); heap.Push(h, v); if h.Len() > k { heap.Pop(h) }',
          '```',
          '',
          '## 面试视角',
          '',
          '- **切片与链表怎么选？**（答：多数场景选切片，缓存友好、实现简单；仅频繁中间增删才考虑链表）',
          '- **如何用堆求 Top-K？**（答：维护大小为 K 的小顶堆，超过 K 就弹出最小者）'
        ].join(NL)
      },
      {
        id: 'go-c10-s3', title: '映射与集合：map 原理',
        direction: '理解哈希表实现、负载因子与遍历无序性。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'map 是**“按键直接定位的柜子”**：对 key 算哈希、映射到桶（bucket）、桶内线性比对找到值，平均 O(1)。代价是**遍历顺序被刻意随机化**——Go 不想让你依赖顺序，因为顺序本就不保证。当元素太多（负载因子过高）时整表扩容搬迁，这是一次性的大额开销。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **实现**：桶数组 + 溢出桶；负载因子超过约 6.5（每桶元素数）触发翻倍扩容。[map 实现说明](https://go.dev/blog/maps)',
          '- **遍历无序**：`for k := range m` 的起始桶与起始偏移是随机的，同一 map 两次遍历顺序可能不同。',
          '- **零值陷阱**：访问不存在的 key 返回 value 类型的零值，需用 `v, ok := m[k]` 区分“不存在”与“值为零”。',
          '',
          '## 常见坑',
          '',
          '- **遍历时写入**：边 range 边增删会导致行为未定义（可能 panic 或漏遍历），需先收集 key 再改。',
          '- **并发读写**：map 非并发安全，并发写会直接 panic；读多写少用 `sync.RWMutex`，高并发用 `sync.Map`。',
          '',
          '## 动手自测',
          '',
          '```go',
          'if v, ok := m[key]; ok { /* 存在且有值 */ }',
          '// 集合去重：set := map[string]struct{}{}；set[x] = struct{}{}',
          '```',
          '',
          '## 面试视角',
          '',
          '- **map 为什么遍历无序？**（答：Go 刻意随机化起始位置，防止开发者依赖不保证的顺序）',
          '- **并发读写 map 会怎样？**（答：运行时检测到会直接 panic，需加锁或用 sync.Map）'
        ].join(NL)
      },
      {
        id: 'go-c10-s4', title: '排序、查找与算法范式',
        direction: '用 sort/slices 包，掌握二分、双指针与滑动窗口。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '## 心智模型',
          '',
          '算法范式是**“可复用的解题套路”**：**双指针**让两个下标相向或同向扫描，把 O(n²) 压到 O(n)；**滑动窗口**维护一段满足条件的区间，右端扩张、左端收缩，专治子串/子数组类问题；**二分**则把“找答案”变成“不断砍掉一半的猜”。先认出题型，再套范式，胜过背题。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **排序**：`sort.Slice(x, lessFn)` 通用排序（Go 1.22+ 推荐泛型版 `slices.Sort`），底层是 pdqsort，平均 O(n log n)、非稳定。[sort 包](https://pkg.go.dev/sort)',
          '- **二分查找**：`sort.Search(n, f)` 返回第一个使 `f(i)` 为 true 的下标，适用于已排序序列。[sort.Search](https://pkg.go.dev/sort#Search)',
          '- **范式匹配**：有序数组查找→二分；子串/连续区间→滑动窗口；两数和、回文→双指针；最优子结构→动态规划。',
          '',
          '## 常见坑',
          '',
          '- **对未排序数据二分**：结果完全不可信，二分的前提是单调性（有序或判定条件单调）。',
          '- **sort.Slice 的比较函数不满足严格弱序**：会导致结果不确定甚至 panic，必须保证 `less(a,a)==false` 且可传递。',
          '',
          '## 动手自测',
          '',
          '```go',
          'slices.Sort(nums)                       // 泛型排序',
          'i := sort.Search(len(a), func(i int) bool { return a[i] >= target })',
          '```',
          '',
          '## 面试视角',
          '',
          '- **什么时候用滑动窗口？**（答：求满足某条件的最长/最短连续子区间，且窗口扩张与收缩具有单调性）',
          '- **二分查找的边界怎么写才不出错？**（答：定义清晰的判定函数，用 sort.Search 找“第一个满足条件的下标”）'
        ].join(NL)
      }
    ]
  },
  {
    id: 'go-c11', subtrack: 'go', position: 117,
    title: 'Go 网络编程与 IO 模型',
    goal: '从 Socket 到 netpoller，理解 Go 高并发网络服务的底层机制。',
    sections: [
      {
        id: 'go-c11-s1', title: 'TCP/IP 与 Socket 编程',
        direction: '用 net 包建立连接，理解三次握手与粘包处理。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'Socket 是**“两台机器之间的电话线”**：服务端 `Listen` 占好号码、`Accept` 接听来电；客户端 `Dial` 拨号；双方各自持有一个可读写的文件描述符。TCP 保证顺序与可靠，但它只认字节流、不认“消息边界”——这就是粘包的根源，需要应用层自己定界。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **服务端**：`ln, _ := net.Listen("tcp", ":8080")`；`conn, _ := ln.Accept()`，每个连接交给一个 goroutine 处理。[net 包](https://pkg.go.dev/net)',
          '- **读写**：`conn.Read(buf)` / `conn.Write(b)`；用 `bufio.Scanner` 或 `io.ReadFull` 处理定界。',
          '- **粘包定界**：固定长度、分隔符（如 `\n`）、或“长度前缀 + 负载”（最通用）。',
          '',
          '## 常见坑',
          '',
          '- **假设一次 Read 就读满**：TCP 是字节流，一次 Read 可能只返回部分数据，必须循环读或按长度前缀读取。',
          '- **连接不关闭**：忘记 `defer conn.Close()` 会耗尽文件描述符，最终 `too many open files`。',
          '',
          '## 动手自测',
          '',
          '```go',
          'ln, _ := net.Listen("tcp", ":8080")',
          'for {',
          '    conn, err := ln.Accept(); if err != nil { continue }',
          '    go func(c net.Conn) { defer c.Close(); io.Copy(c, c) }(conn)  // echo',
          '}',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么 TCP 会粘包？**（答：TCP 是面向字节流的，不保留消息边界，需应用层定界）',
          '- **Go 里一个连接一个 goroutine 撑得住吗？**（答：可以，goroutine 轻量且阻塞时不占用 OS 线程）'
        ].join(NL)
      },
      {
        id: 'go-c11-s2', title: 'IO 多路复用与 netpoller',
        direction: '理解阻塞 IO 背后的网络轮询器，为什么同步写法能扛高并发。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'Go 的魔法是**“用同步的写法，跑异步的内核”**：你写 `conn.Read()` 看起来是阻塞的，但运行时底层把它挂到 netpoller（Linux 上是 epoll）上——goroutine 被挂起、M 让出去干别的；数据到达时 poller 唤醒对应 goroutine 继续执行。**写法是同步的，执行是事件驱动的**，这就是 Go 网络服务高并发又易读的原因。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **netpoller**：运行时内部封装 epoll（Linux）/kqueue（macOS）/IOCP（Windows），为网络 IO 提供就绪通知。[运行时网络轮询](https://go.dev/src/runtime/netpoll.go)',
          '- **goroutine 挂起**：网络 IO 未就绪时，goroutine 被 parked 并注册到 poller，不占用 M；就绪后由 poller 唤醒入队。',
          '- **与线程池对比**：传统“一连接一线程”在万级连接时线程切换与内存成本极高；Go 的 goroutine 初始栈仅 2KB，可轻松支撑十万连接。',
          '',
          '## 常见坑',
          '',
          '- **把 CPU 密集逻辑放进网络 goroutine**：长时间占用 P 会拖慢调度，应限制并发或交给专用 worker 池。',
          '- **文件 IO 不走 netpoller**：普通文件读写会占用 M（Go 不支持异步文件 IO），大量文件操作需另行控制并发。',
          '',
          '## 动手自测',
          '',
          '```bash',
          'GODEBUG=netpollbreak=0 go run main.go   # 观察网络轮询行为（调试用）',
          'runtime.NumGoroutine()                   # 观察连接数与协程数关系',
          '```',
          '',
          '## 面试视角',
          '',
          '- **Go 的阻塞 IO 为什么不会阻塞线程？**（答：运行时用 netpoller 接管，goroutine 挂起、M 释放去干别的）',
          '- **epoll 与 select/poll 的区别？**（答：epoll 无需每次重复传入 fd 集合、就绪列表由内核维护，复杂度 O(1) 而非 O(n)）'
        ].join(NL)
      },
      {
        id: 'go-c11-s3', title: 'HTTP 协议与 net/http 服务端',
        direction: '理解请求生命周期、Handler 与中间件链。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          '一次 HTTP 请求是**“信封的往返”**：请求行（方法+路径+版本）、请求头（元信息）、空行、请求体；服务端回状态行、响应头、响应体。`net/http` 把这个过程抽象成 `Handler`——任何实现 `ServeHTTP(w, r)` 的类型都能接活，中间件就是这个接口的层层包装。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **服务端**：`http.HandleFunc(path, fn)` 注册，`http.ListenAndServe(":8080", nil)` 启动；每个请求由独立 goroutine 处理。[net/http 包](https://pkg.go.dev/net/http)',
          '- **Handler 与中间件**：`func(next http.Handler) http.Handler` 的装饰器模式，依次串联日志、认证、限流。',
          '- **超时控制**：`http.Server{ReadTimeout, WriteTimeout, IdleTimeout}` 必须显式设置，否则默认无超时。',
          '',
          '## 常见坑',
          '',
          '- **用默认 Server 无超时**：慢客户端会长期占用连接，最终拖垮服务；务必显式配置三个超时。',
          '- **在 Handler 里起 goroutine 却用已返回的 request context**：请求返回后 context 被取消，异步任务需使用独立 context。',
          '',
          '## 动手自测',
          '',
          '```go',
          'srv := &http.Server{Addr: ":8080", ReadTimeout: 5*time.Second, WriteTimeout: 10*time.Second}',
          'http.HandleFunc("/ping", func(w http.ResponseWriter, r *http.Request) { fmt.Fprintln(w, "pong") })',
          'srv.ListenAndServe()',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么必须设置 HTTP 超时？**（答：防止慢连接长期占用资源导致服务不可用）',
          '- **中间件如何实现？**（答：用 `func(http.Handler) http.Handler` 装饰器层层包装 Handler）'
        ].join(NL)
      },
      {
        id: 'go-c11-s4', title: '高性能网络实践',
        direction: '用连接池、超时与背压控制保护服务稳定性。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方',
          '',
          '## 心智模型',
          '',
          '高性能网络服务的本质是**“把有限资源用在刀刃上，并在过载时优雅拒绝”**：连接池复用 TCP 连接省去握手开销；超时给每次调用划出止损线；背压（限流/信号量）在下游扛不住时主动降速，而不是让请求堆积到雪崩。**不接受无限流量**是稳定性设计的第一原则。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **连接池**：`http.Transport{MaxIdleConns, MaxIdleConnsPerHost, IdleConnTimeout}` 复用连接，客户端务必复用同一个 Transport。[Transport](https://pkg.go.dev/net/http#Transport)',
          '- **超时**：客户端 `http.Client{Timeout: 5s}`；服务端三件套 Read/Write/Idle 超时。',
          '- **背压**：用带缓冲 channel 或 `golang.org/x/sync/semaphore` 限制并发数，超限快速失败或降级。',
          '',
          '## 常见坑',
          '',
          '- **每次请求新建 http.Client**：导致连接无法复用，端口耗尽、延迟飙升。应全局复用。',
          '- **不读且关闭响应体**：`resp.Body` 未 Close 会导致连接无法归还池中，最终连接泄漏。',
          '',
          '## 动手自测',
          '',
          '```go',
          'tr := &http.Transport{MaxIdleConns: 100, MaxIdleConnsPerHost: 10}',
          'client := &http.Client{Transport: tr, Timeout: 5 * time.Second}',
          'resp, err := client.Get(u); if resp != nil { defer resp.Body.Close(); io.Copy(io.Discard, resp.Body) }',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么要复用连接池？**（答：省去 TCP 握手与 TLS 握手开销，降低延迟并减少端口消耗）',
          '- **服务扛不住时该怎么做？**（答：限流/背压快速失败并降级，避免请求堆积引发雪崩）'
        ].join(NL)
      }
    ]
  },
  {
    id: 'py-c9', subtrack: 'python', position: 118,
    title: 'Python 运行时与性能剖析',
    goal: '理解对象模型、内存管理与 GIL，会用剖析工具定位瓶颈。',
    sections: [
      {
        id: 'py-c9-s1', title: '对象模型与内存管理',
        direction: '理解一切皆对象、引用计数与分代回收的协作。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'Python 的内存管理是**“两套账本并行”**：主账本是**引用计数**——每个对象记录有多少人引用它，归零即刻回收（及时、可预测）；但它算不出循环引用（A 引用 B、B 又引用 A），于是配备**分代垃圾回收**做补充，专门清理这类“互相抱着不撒手”的孤岛。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **一切皆对象**：整数、字符串、函数都是对象，变量只是名字到对象的绑定（`a = 1` 是贴标签，不是装盒子）。',
          '- **引用计数**：`sys.getrefcount(obj)` 查看；`del` 或重新赋值使计数归零时立即释放。[gc 模块](https://docs.python.org/3/library/gc.html)',
          '- **分代回收**：对象按存活时间分三代，越“老”检查越稀疏；`gc.collect()` 可手动触发，处理循环引用。',
          '',
          '## 常见坑',
          '',
          '- **循环引用 + 自定义 __del__**：老版本 Python 中这类对象可能无法被回收，需显式打破引用或用 `weakref`。',
          '- **以为 del 就等于释放内存**：`del` 只删名字（解绑），对象是否释放取决于是否还有别的引用。',
          '',
          '## 动手自测',
          '',
          '```python',
          'import sys, gc',
          'a = []; print(sys.getrefcount(a))',
          'a.append(a)          # 制造循环引用',
          'del a; gc.collect()  # 需 gc 才能回收',
          '```',
          '',
          '## 面试视角',
          '',
          '- **有了引用计数为什么还需要 GC？**（答：引用计数无法解决循环引用，需分代 GC 补充）',
          '- **小整数 1 与 1000 的区别？**（答：Python 缓存 -5~256 的小整数对象，范围内同值共享同一对象）'
        ].join(NL)
      },
      {
        id: 'py-c9-s2', title: 'GIL 与并发模型选择',
        direction: '理解全局解释器锁的边界，据此选线程/进程/协程。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'GIL（全局解释器锁）是**“同一时刻只允许一个线程执行字节码”的门禁**。它不是 Python 语言特性，而是 CPython 解释器的实现选择。关键认知：**GIL 只在执行字节码时生效，IO 等待和部分 C 扩展（NumPy 等）会主动释放它**。所以 IO 密集型用多线程/协程照样并发，CPU 密集型才需要多进程绕开。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **影响范围**：GIL 保证同一进程内任一时刻只有一个线程执行 Python 字节码。[术语表 GIL](https://docs.python.org/3/glossary.html#term-global-interpreter-lock)',
          '- **IO 密集型**：`threading` 或 `asyncio` 都有效——IO 等待时释放 GIL，线程/协程可交替推进。',
          '- **CPU 密集型**：用 `multiprocessing`（每进程独立解释器与 GIL）或把热点交给释放 GIL 的 C 扩展（NumPy）。',
          '',
          '## 常见坑',
          '',
          '- **用多线程做 CPU 密集计算期待提速**：GIL 让它们只能轮流跑一个核，实际可能比单线程更慢（多了切换）。',
          '- **以为 asyncio 能绕过 GIL**：asyncio 解决的是等待的并发，不是并行计算；CPU 密集仍需进程池。',
          '',
          '## 动手自测',
          '',
          '```python',
          'from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor',
          '# CPU 密集 → 进程池；IO 密集 → 线程池/asyncio',
          'with ProcessPoolExecutor() as ex: list(ex.map(cpu_heavy, data))',
          '```',
          '',
          '## 面试视角',
          '',
          '- **GIL 是什么、为什么要它？**（答：CPython 的互斥锁，保护引用计数等内部状态，简化实现并保证线程安全）',
          '- **CPU 密集任务怎么提速？**（答：multiprocessing 多进程，或交给释放 GIL 的 C 扩展）'
        ].join(NL)
      },
      {
        id: 'py-c9-s3', title: '性能剖析与测量',
        direction: '用 timeit/cProfile 量化耗时，定位真实热点。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '## 心智模型',
          '',
          '性能剖析是**“先量后改”**：`timeit` 负责微基准（这段代码到底多快，多次运行取最优以抵消抖动）；`cProfile` 负责全局画像（整个程序的时间都花在哪些函数上）。**没有度量的优化都是猜测**——你以为的瓶颈，八成不是真的瓶颈。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **timeit**：`python -m timeit "s=[]; s.append(1)"`；模块内 `timeit.timeit(stmt, number=10000)`。[timeit](https://docs.python.org/3/library/timeit.html)',
          '- **cProfile**：`python -m cProfile -s cumtime app.py` 按累计耗时排序；`pstats` 可在代码内分析结果。[profile](https://docs.python.org/3/library/profile.html)',
          '- **逐行剖析**：`line_profiler`（第三方）给出每行耗时，适合定位到具体语句。',
          '',
          '## 常见坑',
          '',
          '- **只跑一次就下结论**：单次测量受调度抖动影响极大，timeit 默认多轮取最小值正是为此。',
          '- **在剖析模式下评估绝对性能**：cProfile 本身有显著开销，只能看相对占比。',
          '',
          '## 动手自测',
          '',
          '```bash',
          'python -m timeit -n 10000 "sum(range(100))"',
          'python -m cProfile -s cumtime app.py | head -20',
          '```',
          '',
          '## 面试视角',
          '',
          '- **timeit 与 cProfile 分别解决什么？**（答：前者测微基准、比写法优劣；后者做全局画像、找热点函数）',
          '- **为什么测量要多次取最优？**（答：消除系统调度与 GC 抖动，最小值最接近代码真实开销）'
        ].join(NL)
      },
      {
        id: 'py-c9-s4', title: '优化策略与常见陷阱',
        direction: '用向量化、生成器与合适容器替换低效写法。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'Python 优化的第一原则是**“把活从 Python 层挪走”**：能用内置函数/C 扩展（如 NumPy 向量化）就别写 Python 循环；能延迟计算（生成器）就别一次性构造全量列表；能 O(1) 查找（`set`/`dict`）就别 O(n) 扫描。**换数据结构与换层级，收益远大于抠语法细节**。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **生成器**：`yield` 惰性产出，省内存；`(x for x in ...)` 生成器表达式同理。[生成器](https://docs.python.org/3/tutorial/classes.html#generators)',
          '- **容器选择**：`in` 判断用 `set`/`dict`（O(1)）而非 `list`（O(n)）；两端频繁增删用 `collections.deque`（O(1)）而非 `list`（头部插入 O(n)）。',
          '- **字符串拼接**：循环内 `+=` 会产生大量中间对象，应收集到列表后 `str.join()`。',
          '',
          '## 常见坑',
          '',
          '- **为微优化牺牲可读性**：`sum()`、列表推导式已经很快，可读性优先，除非剖析证明这里是瓶颈。',
          '- **生成器的单次消费**：生成器只能遍历一次，需要多次使用应转成列表或重新构造。',
          '',
          '## 动手自测',
          '',
          '```python',
          '# 慢：循环拼接 + 列表 in 判断',
          's = ""; for part in parts: s += part',
          '# 快：join + set 判断',
          's = "".join(parts); seen = set(items)',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么循环内字符串 += 慢？**（答：每轮产生新字符串对象并拷贝，O(n²)；join 一次性分配）',
          '- **list 与 set 做成员判断的差别？**（答：list 是 O(n) 线性扫描，set 是 O(1) 哈希查找）'
        ].join(NL)
      }
    ]
  },
  {
    id: 'py-c10', subtrack: 'python', position: 119,
    title: 'Python 数据结构与算法',
    goal: '掌握内置容器的时间复杂度与实现原理，能选择合适的结构解题。',
    sections: [
      {
        id: 'py-c10-s1', title: '复杂度与容器时间开销',
        direction: '背下常用操作的时间复杂度，避免写出隐性 O(n²)。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '## 心智模型',
          '',
          '写 Python 时真正决定性能的，往往不是语法细节而是**容器的选择**：同样一句 `if x in c`，`c` 是 list 就是 O(n) 扫描，改成 set 就是 O(1) 哈希。把这个“复杂度直觉”装进脑子，就能在写代码的第一时间避开大部分性能坑。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **list**：按下标访问 O(1)；`append` 均摊 O(1)；`insert(0, x)` 与 `x in list` 均为 O(n)。[时间复杂度表](https://wiki.python.org/moin/TimeComplexity)',
          '- **dict/set**：查找、插入、删除平均 O(1)，最坏 O(n)（哈希冲突极端情况）；遍历 O(n) 且保持插入顺序（Python 3.7+）。',
          '- **deque**：两端 append/pop 均 O(1)，中间访问 O(n)。',
          '',
          '## 常见坑',
          '',
          '- **用 list 做去重或频繁成员判断**：数据量一大立刻 O(n²)，应改 set。',
          '- **在循环里对 list 做头部插入**：`insert(0, x)` 会整体搬移元素，改 deque 或先 append 后 reverse。',
          '',
          '## 动手自测',
          '',
          '```python',
          'from collections import deque',
          'seen = set(); dup = [x for x in items if x in seen or seen.add(x)]  # 去重保序',
          'q = deque(maxlen=1000)   # 定长队列，自动丢弃最旧元素',
          '```',
          '',
          '## 面试视角',
          '',
          '- **list 的 append 为什么是均摊 O(1)？**（答：底层按倍扩容，偶尔一次 O(n) 拷贝被均摊掉）',
          '- **dict 在 Python 3.7+ 有什么变化？**（答：正式保证保持插入顺序）'
        ].join(NL)
      },
      {
        id: 'py-c10-s2', title: '线性结构与 collections',
        direction: '用 deque、Counter、defaultdict 简化常见结构实现。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '## 心智模型',
          '',
          '`collections` 是**“标准库替你写好的常用结构”**：`deque` 是双端队列（两端进出都 O(1)），`Counter` 是“数数器”（统计频次一行搞定），`defaultdict` 让“键不存在时自动给个默认值”不再需要手写 `if k not in d`。**先查标准库，再自己造轮子**。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **deque**：`appendleft/popleft/append/pop` 全 O(1)，适合队列与栈；`maxlen` 可做滑动窗口。[collections](https://docs.python.org/3/library/collections.html)',
          '- **Counter**：`Counter(items).most_common(k)` 直接求 Top-K 频次，内部基于 dict。',
          '- **defaultdict**：`defaultdict(list)` 后可直接 `d[k].append(v)`，免去存在性判断。',
          '',
          '## 常见坑',
          '',
          '- **defaultdict 的默认值工厂会“无中生有”**：仅访问不存在的键也会创建条目，可能污染后续遍历结果。',
          '- **queue.Queue 与 deque 混用**：前者是线程安全队列（带阻塞语义），后者非线程安全但更快；单线程场景用 deque。',
          '',
          '## 动手自测',
          '',
          '```python',
          'from collections import deque, Counter, defaultdict',
          'w = deque(maxlen=3); w.extend([1,2,3]); w.append(4)   # 滑动窗口 [2,3,4]',
          'Counter(words).most_common(3)                          # 词频 Top-3',
          'g = defaultdict(list); g[k].append(v)                  # 分组',
          '```',
          '',
          '## 面试视角',
          '',
          '- **如何实现固定大小的滑动窗口？**（答：`deque(maxlen=n)`，超长自动丢弃最旧元素）',
          '- **Counter 与手写 dict 计数相比好在哪？**（答：API 语义清晰，most_common 等高频操作开箱即用）'
        ].join(NL)
      },
      {
        id: 'py-c10-s3', title: '哈希结构：dict 与 set 原理',
        direction: '理解开放寻址、扩容与键的可哈希要求。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'dict 是**“用哈希直接定位的抽屉柜”**：对 key 算哈希值、取模定位到槽位；若槽位被占（哈希冲突），用**开放寻址**按特定探测序列找下一个空位。当装载率超过约 2/3 就扩容重建，把冲突概率压回去。代价是**键必须可哈希**（不可变且实现 `__hash__`）——list、dict、set 都不能当 key。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **开放寻址**：冲突时探测下一个槽位，而非挂链表；因此删除需标记"已删除"而非真清空。[dict 实现说明](https://docs.python.org/3/faq/design.html#how-are-dictionaries-implemented)',
          '- **可哈希要求**：对象需实现 `__hash__` 且生命周期内不变；`tuple` 仅当所有元素可哈希时才可哈希。',
          '- **set**：本质是只有 key 的 dict，因此同样要求元素可哈希，同样 O(1) 查找。',
          '',
          '## 常见坑',
          '',
          '- **用 list 当 dict 的键**：直接 `TypeError: unhashable type`，需转成 tuple。',
          '- **自定义类未实现 __eq__/__hash__ 一致性**：相等的对象必须有相同哈希值，否则 dict 查找行为错乱。',
          '',
          '## 动手自测',
          '',
          '```python',
          'd = {}; d[(1, 2)] = "ok"        # tuple 可作键',
          'd[[1, 2]] = "bad"               # TypeError: unhashable type: list',
          'class P:',
          '    def __init__(self, x): self.x = x',
          '    def __hash__(self): return hash(self.x)',
          '    def __eq__(self, o): return self.x == o.x',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么 list 不能作为 dict 的键？**（答：list 可变、不可哈希，无法保证哈希值稳定）',
          '- **dict 如何处理哈希冲突？**（答：开放寻址，按探测序列找下一个可用槽位）'
        ].join(NL)
      },
      {
        id: 'py-c10-s4', title: '排序、堆与二分',
        direction: '用 sorted/key、heapq 与 bisect 解决高频算法问题。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'Python 把最常用的三类算法都做成了开箱即用的工具：**排序**用 `sorted(key=...)`（Timsort，稳定且对部分有序数据极快）；**Top-K** 用 `heapq`（小顶堆，内存只留 K 个）；**有序序列查找**用 `bisect`（二分定位插入点）。认出题型、调对应工具，比手写实现更稳更快。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **排序**：`sorted(iterable, key=f, reverse=True)` 返回新列表，`list.sort()` 就地排序；**稳定**（相等元素保持原顺序），可多级排序。[排序指南](https://docs.python.org/3/howto/sorting.html)',
          '- **heapq**：小顶堆，`heappush/heapop/nlargest/nsmallest`；求 Top-K 维护大小 K 的堆，O(n log k)。[heapq](https://docs.python.org/3/library/heapq.html)',
          '- **bisect**：`bisect_left(a, x)` 返回插入位置，用于二分查找与范围统计，前提是序列已排序。',
          '',
          '## 常见坑',
          '',
          '- **heapq 求最大 Top-K 时手动取负**：标准库只提供小顶堆，需在入堆时对数值取负，出堆时再取负。',
          '- **对未排序序列用 bisect**：结果完全不可靠，二分的前提是序列有序。',
          '',
          '## 动手自测',
          '',
          '```python',
          'import heapq, bisect',
          'top = heapq.nlargest(3, nums)              # Top-3 最大值',
          'h = []; [heapq.heappush(h, -x) for x in nums]; -h[0]   # 手写小顶堆求最大',
          'i = bisect.bisect_left(a, target)           # 第一个 >= target 的位置',
          '```',
          '',
          '## 面试视角',
          '',
          '- **Python 的排序稳定吗？**（答：稳定，Timsort 保证相等元素保持原有相对顺序）',
          '- **求 Top-K 用什么？**（答：heapq 维护 K 大小堆，O(n log k)；K 很小时优于全排序的 O(n log n)）'
        ].join(NL)
      }
    ]
  },
  {
    id: 'py-c11', subtrack: 'python', position: 120,
    title: 'Python 网络编程与 IO 模型',
    goal: '从 Socket 到 asyncio 事件循环，理解 Python 高并发 IO 的实现方式。',
    sections: [
      {
        id: 'py-c11-s1', title: 'Socket 编程与 TCP 基础',
        direction: '用 socket 模块建立连接，理解监听与接受的区别。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          '服务端 Socket 有**两个分工不同的套接字**：监听 socket 负责"占号码、接电话"（`bind`+`listen`+`accept`，每次 accept 产出一个新 socket 代表这条连接）；连接 socket 负责"通话"（`recv`/`send`）。混淆这两者是初学者的经典错误——监听 socket 永远不收发数据。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **服务端**：`s = socket.socket(); s.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1); s.bind(("0.0.0.0", 8000)); s.listen(128)`；`conn, addr = s.accept()`。[socket 编程指南](https://docs.python.org/3/howto/sockets.html)',
          '- **客户端**：`c = socket.create_connection(("host", 8000))`；`c.sendall(b"data")`；`c.recv(4096)`。',
          '- **消息定界**：TCP 是字节流，`recv` 返回的是"至多 n 字节"而非"一条消息"，需长度前缀或分隔符定界。',
          '',
          '## 常见坑',
          '',
          '- **以为一次 recv 就是一条完整消息**：必须循环接收至收满足够字节或遇到分隔符。',
          '- **未设 SO_REUSEADDR**：服务重启时端口处于 TIME_WAIT，会报"地址已在使用"。',
          '',
          '## 动手自测',
          '',
          '```python',
          'import socket',
          's = socket.socket(socket.AF_INET, socket.SOCK_STREAM)',
          's.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)',
          's.bind(("0.0.0.0", 8000)); s.listen(128)',
          'conn, addr = s.accept(); data = conn.recv(4096); conn.sendall(b"pong"); conn.close()',
          '```',
          '',
          '## 面试视角',
          '',
          '- **listen 的 backlog 参数是什么意思？**（答：已完成握手但尚未被 accept 的连接队列长度）',
          '- **为什么需要 SO_REUSEADDR？**（答：允许重用处于 TIME_WAIT 的地址，便于服务快速重启）'
        ].join(NL)
      },
      {
        id: 'py-c11-s2', title: 'IO 多路复用与 selectors',
        direction: '理解 select/epoll 差异，用 selectors 编写单线程并发服务。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'IO 多路复用是**"一个服务员盯多桌客人"**：不用为每桌配一个服务员（线程），而是由一个循环统一问内核"哪几桌已经点好菜了（数据就绪）"，然后只处理就绪的那些。内核负责监视，应用程序只在真有活干时才动手——这就是单线程扛住成千连接的关键。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **select 与 epoll**：select 每次调用都要把 fd 集合从用户态拷到内核态并线性扫描，复杂度 O(n) 且有 fd 数量上限；epoll 由内核维护就绪列表，直接返回就绪 fd，复杂度 O(1) 且无上限。',
          '- **selectors**：标准库对 select/epoll/kqueue 的统一封装，自动选择当前平台最优实现。[selectors](https://docs.python.org/3/library/selectors.html)',
          '- **非阻塞配合**：多路复用通常搭配 `sock.setblocking(False)`，避免单个慢连接卡住整个循环。',
          '',
          '## 常见坑',
          '',
          '- **在就绪回调里做阻塞操作**：会卡住整个事件循环，所有连接一起变慢。',
          '- **忘记处理 EAGAIN/BlockingIOError**：非阻塞 socket 在暂无数据时抛异常而非阻塞，需捕获并跳过。',
          '',
          '## 动手自测',
          '',
          '```python',
          'import selectors, socket',
          'sel = selectors.DefaultSelector()',
          'sel.register(sock, selectors.EVENT_READ, accept_handler)',
          'while True:',
          '    for key, mask in sel.select(timeout=1):   # 阻塞直到有 fd 就绪',
          '        key.data(key.fileobj, mask)',
          '```',
          '',
          '## 面试视角',
          '',
          '- **select/poll/epoll 的核心区别？**（答：epoll 由内核维护就绪队列、返回就绪 fd，O(1) 且无数量限制；select 需重复传参并线性扫描，O(n)）',
          '- **多路复用解决的是什么问题？**（答：用少量线程管理大量连接，避免"一连接一线程"的资源与切换开销）'
        ].join(NL)
      },
      {
        id: 'py-c11-s3', title: 'asyncio 事件循环',
        direction: '理解协程、事件循环与 await 的协作机制。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'asyncio 是**"协作式排班表"**：每个协程是一段可以主动让出执行权的任务，遇到 IO 就 `await` 把控制权交还事件循环，循环趁这段时间去跑别的协程；IO 完成后再排回来继续。**单线程、协作式**——一个协程不主动让出（比如跑 CPU 密集循环），整条线上的其他协程都得干等。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **协程与任务**：`async def` 定义协程；`asyncio.create_task(coro)` 把它排入循环并发执行；`await` 等待并让出控制权。[asyncio 文档](https://docs.python.org/3/library/asyncio.html)',
          '- **启动**：`asyncio.run(main())` 创建并驱动事件循环，是推荐的顶层入口。',
          '- **并发聚合**：`asyncio.gather(*coros)` 并发等待多个协程；`asyncio.wait_for(coro, timeout)` 加超时。',
          '',
          '## 常见坑',
          '',
          '- **在协程里调用同步阻塞函数**：`time.sleep()`、`requests.get()` 会卡死整个事件循环，必须换成 `asyncio.sleep()` / `httpx.AsyncClient`。',
          '- **CPU 密集任务放进事件循环**：应交给 `loop.run_in_executor()` 或进程池，避免阻塞循环。',
          '',
          '## 动手自测',
          '',
          '```python',
          'import asyncio',
          'async def fetch(i):',
          '    await asyncio.sleep(0.1)      # 模拟 IO，让出控制权',
          '    return i',
          'async def main():',
          '    return await asyncio.gather(*(fetch(i) for i in range(100)))',
          'asyncio.run(main())',
          '```',
          '',
          '## 面试视角',
          '',
          '- **asyncio 是多线程吗？**（答：不是，单线程协作式并发，靠 await 让出控制权实现切换）',
          '- **asyncio 适合什么场景？**（答：IO 密集型高并发；CPU 密集需交还给进程池/线程池执行）'
        ].join(NL)
      },
      {
        id: 'py-c11-s4', title: 'HTTP 客户端与连接池',
        direction: '用 httpx 的同步/异步客户端，配置超时与连接复用。',
        content: [
          '> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方',
          '',
          '## 心智模型',
          '',
          'HTTP 客户端的性能关键在两点：**连接复用**（握手很贵，能复用就别重建）和**超时兜底**（下游挂了不能把你拖死）。`httpx` 用同一个 `Client` 实例自动维护连接池，用 `AsyncClient` 在 asyncio 里并发；两者都要求**显式设置超时**——默认是无限等待，生产环境必须覆盖。',
          '',
          '## 核心知识点（锚定官方）',
          '',
          '- **连接池**：`httpx.Client(limits=httpx.Limits(max_connections=100, max_keepalive_connections=20))`；复用同一 Client 实例。[httpx 高级用法](https://www.python-httpx.org/advanced/)',
          '- **超时**：`httpx.Client(timeout=5.0)` 或细分 `httpx.Timeout(connect=5, read=10)`。',
          '- **异步**：`async with httpx.AsyncClient() as c: await c.get(url)`，在协程里并发多个请求。',
          '',
          '## 常见坑',
          '',
          '- **每次请求新建 Client**：连接池失效、TCP/TLS 反复握手，延迟与端口消耗激增。应全局复用或用 `with` 块。',
          '- **依赖默认超时**：httpx 默认会等待很久，下游故障时请求堆积最终拖垮服务。',
          '',
          '## 动手自测',
          '',
          '```python',
          'import httpx',
          'limits = httpx.Limits(max_connections=100, max_keepalive_connections=20)',
          'with httpx.Client(limits=limits, timeout=httpx.Timeout(5.0, read=10.0)) as c:',
          '    r = c.get("https://api.example.com/items")',
          '    r.raise_for_status(); data = r.json()',
          '```',
          '',
          '## 面试视角',
          '',
          '- **为什么要复用 Client 实例？**（答：复用连接池，省去 TCP/TLS 握手开销，降低延迟与资源消耗）',
          '- **异步客户端相比同步的优势？**（答：等待期间让出控制权，单线程即可并发成百上千请求）'
        ].join(NL)
      }
    ]
  }
]
