// 一次性执行器：为 be-web 赛道补齐 Go(Gin) / Python(FastAPI) 内容，最终 be-web → java/go/python 三子主题。
// 内容零虚构：全部锚定官方文档（go.dev / gin-gonic.com / docs.python.org / fastapi.tiangolo.com），
// 结构对齐既有 Java 章节（header + 心智模型 + 核心知识点(锚定官方) + 常见坑 + 动手自测 + 面试视角）。
// 分批执行：本脚本按 BATCH 常量控制本批生成的章节，幂等可重跑（已存在章节跳过，DB 用 INSERT OR IGNORE）。
// 双写 data/seed-content.json（真源）+ data/devmentor.db。支持 --dry-run。
import fs from 'node:fs'
import Database from 'better-sqlite3'

const SEED_PATH = './data/seed-content.json'
const DB_PATH = './data/devmentor.db'
const DRY = process.argv.includes('--dry-run')

// 本批生成 4 章：go-c1/go-c2 (Go+Gin) + py-c1/py-c2 (Python+FastAPI)
// position 从 backend 模块当前 MAX+1 起顺序分配
const CHAPTERS = [
  {
    id: 'go-c1', subtrack: 'go', position: 99,
    title: 'Go 基础与并发模型',
    goal: '掌握 Go 的语法基础与 goroutine/channel 并发模型，能编写并发安全的 Go 程序。',
    sections: [
      { id: 'go-c1-s1', title: '语言入门与开发环境', direction: '能安装 Go 工具链、配置 GOPATH/GOPROXY 并运行第一个程序。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n把 Go 工具链想成**一套自带电池的厨具**：`go` 命令既是“切菜机”（`go build` 编译）也是“炒锅”（`go run` 直接运行），而 `GOPATH`/`GOMODCACHE` 是**食材仓库**——所有下载的第三方包都放在这里。`GOPROXY` 则是**采购渠道**，告诉 `go` 去哪个镜像（如 `https://proxy.golang.org`）拉依赖，国内常配 `https://goproxy.cn`。\n\n## 核心知识点（锚定官方）\n\n- **安装与版本**：从 [Go 官方下载页](https://go.dev/dl/) 安装后，`go version` 验证。Go 1.21+ 推荐使用 `go install` 管理工具链。[Go 安装指南](https://go.dev/doc/install)\n- **GOPATH 与模块**：Go 1.11 引入 Go Modules 后不再强依赖 `GOPATH` 写业务代码；项目根目录 `go.mod` 声明模块路径与 Go 版本。`go env GOPATH` 查看当前值，默认 `~/go`。[Go Modules 参考](https://go.dev/ref/mod)\n- **GOPROXY 配置**：`go env -w GOPROXY=https://goproxy.cn,direct` 设置国内镜像，`direct` 表示镜像失败时回源。[代理配置文档](https://go.dev/ref/mod#environment-variables)\n- **最小程序**：`package main` + `func main()` 是入口；`go run main.go` 直接编译运行，`go build` 产出二进制。[Go 教程](https://go.dev/doc/tutorial/getting-started)\n\n## 常见坑\n\n- **未初始化模块**：在空目录直接 `go run` 报错 `go.mod file not found`——先 `go mod init <module>`。\n- **GOPROXY 未设导致拉不下来**：公司网络下 `go get` 超时，需配 `GOPROXY` 与 `GOSUMDB=off`（仅内网可信场景）。\n- **`main` 包缺失**：非 `package main` 的文件 `go run` 找不到入口，报 `no Go files in ...`。\n\n## 动手自测\n\n```bash\n# 1. 初始化模块\ngo mod init example/hello\n# 2. 编写 main.go\n# 3. 运行\ngo run .   # 或 go run main.go\n# 4. 编译二进制\ngo build -o hello .\n```\n\n## 面试视角\n\n- **GOPATH 与 Go Modules 的区别？**（答：GOPATH 是全局单仓库模式，Modules 是项目级依赖声明，解决版本与多项目隔离）\n- **GOPROXY 的作用？**（答：指定模块代理以提升拉取速度与可用性，避免直连 github 超时）" },
      { id: 'go-c1-s2', title: '变量、类型与零值', direction: '理解 Go 的静态类型、零值约定与简洁声明语法。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nGo 的类型像**贴了标签的盒子**：声明时盒子的“形状”（类型）就固定了，往里放错形状的东西编译器直接拒绝。未显式初始化的盒子会自动装入**零值**（数字=0、字符串=\"\"、指针/切片/map=nil）——这是 Go“显式优于隐式”哲学的体现，没有 Java 那种“未初始化局部变量编译报错”的约束，但零值是确定且安全的。\n\n## 核心知识点（锚定官方）\n\n- **声明与短声明**：`var x int = 10` 显式声明；函数内 `x := 10` 用类型推断（短声明），仅限函数内部。[变量声明](https://go.dev/ref/spec#Variable_declarations)\n- **零值**：`var s []int` 得到 nil 切片而非报错；`var m map[string]int` 为 nil，**直接赋值会 panic**，须 `make` 或字面量初始化。[零值规范](https://go.dev/ref/spec#The_zero_value)\n- **基础类型**：`int/int64`、`float64`、`string`（不可变）、`bool`、`rune`（Unicode 码点）、`byte`(=uint8)。[基础类型](https://go.dev/ref/spec#Numeric_types)\n- **`new` vs `make`**：`new(T)` 返回 `*T`（零值指针）；`make` 仅用于 slice/map/channel，返回已初始化的**非指针**对象。[内置函数](https://go.dev/ref/spec#Allocation)\n\n## 常见坑\n\n- **nil map 写入 panic**：`var m map[string]int; m[\"a\"]=1` 运行时 panic，应 `m := make(map[string]int)`。\n- **短声明作用域陷阱**：`if x := f(); x>0 { }` 中 `x` 仅在该块可见；与外层同名变量混用易出错。\n- **`int` 长度依赖平台**：32 位系统 `int`=32 位，网络/文件协议需显式 `int64` 避免截断。\n\n## 动手自测\n\n```go\npackage main\nimport \"fmt\"\nfunc main() {\n    var s []int            // 零值 nil\n    fmt.Println(s == nil)  // true\n    m := make(map[string]int)\n    m[\"a\"] = 1\n    x := 10               // 短声明\n    fmt.Println(x, m)\n}\n```\n\n## 面试视角\n\n- **Go 的零值设计解决了什么问题？**（答：消除“未初始化变量”的不确定性，所有变量都有确定初值，减少空指针类 bug）\n- **`new` 和 `make` 的区别？**（答：`new` 分配零值并返回指针；`make` 初始化 slice/map/channel 的运行时结构并返回对象）" },
      { id: 'go-c1-s3', title: '结构体与方法', direction: '用结构体建模领域对象，并理解值/指针接收者的区别。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nGo 没有“类”与“继承”，只有**结构体（盒子）+ 方法（贴在盒子上的函数）**。方法通过“接收者”绑定到类型：`func (u User) Name()` 是值接收者（操作副本），`func (u *User) SetName()` 是指针接收者（操作原身）。组合（把结构体嵌入另一个结构体）替代继承，实现代码复用——这是 Go“组合优于继承”的设计取舍。\n\n## 核心知识点（锚定官方）\n\n- **结构体字面量**：`User{Name:\"a\"}` 字段名显式初始化，顺序可乱；`User{\"a\",1}` 必须按定义顺序。[结构体类型](https://go.dev/ref/spec#Struct_types)\n- **方法接收者**：值接收者 `(u User)` 接收副本，适合小型不可变数据；指针接收者 `(u *User)` 可修改原对象，且避免大对象拷贝。[方法声明](https://go.dev/ref/spec#Method_declarations)\n- **匿名字段/嵌入**：`type Admin struct { User; Level int }` 嵌入 `User`，`Admin` 直接拥有 `User` 的字段与方法（提升），实现组合复用。[嵌入](https://go.dev/ref/spec#Embedded_field)\n- **`struct{}` 空结构体**：不占内存，常用于 set（map[string]struct{}）或 channel 信号量。[内存布局](https://go.dev/wiki/CompilerOptimizations)\n\n## 常见坑\n\n- **值接收者误改字段**：`func (u User) Set() { u.Name=\"x\" }` 改的是副本，原对象不变——需用指针接收者。\n- **大写即导出**：字段/方法首字母大写才对包外可见，小写是包内私有，常因忘大写导致序列化丢字段。\n- **比较含 slice/map 的结构体**：含不可比较字段的结构体不能用 `==`，会编译报错。\n\n## 动手自测\n\n```go\ntype User struct{ Name string; Age int }\nfunc (u *User) Grow() { u.Age++ }   // 指针接收者改原身\nfunc main() {\n    u := &User{Name:\"a\", Age:1}\n    u.Grow()\n    fmt.Println(u.Age) // 2\n}\n```\n\n## 面试视角\n\n- **何时用指针接收者？**（答：需修改接收者、结构体较大避免拷贝、或需一致性——同一类型的其他方法已用指针时统一用指针）\n- **Go 如何实现“继承”？**（答：用结构体嵌入做组合，而非传统继承）" },
      { id: 'go-c1-s4', title: 'Goroutine 与 Channel', direction: '用 goroutine + channel 编写并发程序，理解“不要通过共享内存通信”原则。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\ngoroutine 是**轻量到极致的工人**（初始栈仅 2KB，由 runtime 调度到 OS 线程上），`go func()` 一句话就能雇一个。但多个工人抢同一份数据会出乱子——Go 的箴言是：**“不要通过共享内存来通信，而要通过通信来共享内存”**。channel 就是工人之间传递数据的**传送带**，谁要用数据就从传送带上取，天然避免了锁。\n\n## 核心知识点（锚定官方）\n\n- **启动 goroutine**：`go doWork()` 异步执行，主协程退出则全部退出，需用 `sync.WaitGroup` 或 channel 等待。[Go 并发教程](https://go.dev/doc/tutorial/golang-with-google)\n- **Channel 基础**：`ch := make(chan int)` 无缓冲（同步）；`make(chan int, 3)` 有缓冲（异步到容量）。`ch <- v` 发送，`v := <-ch` 接收，`close(ch)` 关闭。[Channel 类型](https://go.dev/ref/spec#Channel_types)\n- **`select` 多路复用**：`select { case v:=<-ch1: ...; case ch2<-x: ...; default: }` 等待多个 channel，类似 IO 多路复用。[select 语句](https://go.dev/ref/spec#Select_statements)\n- **`sync.WaitGroup`**：`Add/Done/Wait` 等待一组 goroutine 结束；`sync.Mutex` 用于必须共享内存时的互斥。[sync 包](https://pkg.go.dev/sync)\n\n## 常见坑\n\n- **主协程提前退出**：忘了 `WaitGroup`，goroutine 还没跑完程序就结束了。\n- **向已关闭 channel 发送 panic**：`close` 后还 `<- ch` 取值是安全的（返回零值+false），但 `ch <- x` 会 panic。\n- **goroutine 泄漏**：channel 无人接收且无人关闭，goroutine 永久阻塞。\n\n## 动手自测\n\n```go\nfunc main() {\n    ch := make(chan int, 2)\n    go func() { ch <- 1; ch <- 2; close(ch) }()\n    for v := range ch { fmt.Println(v) } // 1 2\n}\n```\n\n## 面试视角\n\n- **goroutine 与线程的区别？**（答：goroutine 由 Go runtime 调度、栈动态增长、创建成本极低，可轻松起数十万；线程由 OS 调度、栈固定 MB 级）\n- **channel 缓冲与否的语义差异？**（答：无缓冲是同步交接，发送接收双方必须同时就绪；有缓冲在未满/未空时可异步）" }
    ]
  },
  {
    id: 'go-c2', subtrack: 'go', position: 100,
    title: 'Gin Web 框架核心',
    goal: '使用 Gin 构建 RESTful API，掌握路由、中间件、参数绑定与统一错误处理。',
    sections: [
      { id: 'go-c2-s1', title: '路由与请求处理', direction: '用 Gin 注册路由、读取路径/查询/JSON 参数并返回响应。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nGin 的 `Engine` 像**一个带智能分拣台的快递中心**：`router.GET(\"/users/:id\", h)` 给不同“地址”（路由）挂上对应的“处理员”（handler）。请求进来后，分拣台按路径把包裹（请求）送到正确处理员手里；`:id` 是路径里的**可变格口**，处理员用 `c.Param(\"id\")` 从格口取件。\n\n## 核心知识点（锚定官方）\n\n- **快速起步**：`r := gin.Default(); r.GET(\"/ping\", func(c *gin.Context){ c.JSON(200, gin.H{\"msg\":\"pong\"}) }); r.Run(\":8080\")`。[Gin README](https://github.com/gin-gonic/gin)\n- **路由与参数**：`c.Param(\"id\")` 取路径参数；`c.Query(\"page\")` 取查询参数；`c.PostForm(\"name\")` 取表单。[API 示例](https://gin-gonic.com/docs/examples/)\n- **路由组**：`api := r.Group(\"/api\"); api.GET(\"/users\", ...)` 统一起前缀，便于版本化与中间件挂载。[分组路由](https://gin-gonic.com/docs/examples/grouping-routes/)\n- **JSON 绑定与校验**：`c.ShouldBindJSON(&req)` 将 body 反序列化为结构体，配合 `binding:\"required\"` 标签做校验。[绑定文档](https://gin-gonic.com/docs/examples/binding-and-validation/)\n\n## 常见坑\n\n- **`ShouldBind` vs `ShouldBindJSON`**：`ShouldBind` 按 Content-Type 选策略，表单请求会被误当 JSON；明确场景直接用 `ShouldBindJSON`/`ShouldBindQuery` 更安全。\n- **`c.JSON` 后忘记 return**：handler 里校验失败 `c.JSON(400,...)` 后若继续执行会二次写响应，panic。\n- **通配路由与冲突**：`/users/*action` 与 `/users/:id` 共存时匹配规则易混淆，注意注册顺序。\n\n## 动手自测\n\n```go\nfunc main() {\n    r := gin.Default()\n    r.GET(\"/users/:id\", func(c *gin.Context) {\n        id := c.Param(\"id\")\n        c.JSON(200, gin.H{\"id\": id})\n    })\n    r.Run(\":8080\")\n}\n```\n\n## 面试视角\n\n- **Gin 的 `Context` 为什么用指针接收？**（答：Context 内含请求/响应与内部状态，handler 共享同一实例，指针避免拷贝且可修改）\n- **路由冲突如何排查？**（答：Gin 基于 httprouter 的 radix 树，静态/参数/通配节点互斥，检查是否同一层级注册了冲突模式）" },
      { id: 'go-c2-s2', title: '中间件机制', direction: '理解 Gin 中间件的洋葱模型，能编写鉴权/日志/Recovery 中间件。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n中间件是**包裹在 handler 外的洋葱层**：请求从外向内穿过每层（日志→鉴权→…），到达核心 handler 后再由原路返回。每层可在“进入时”做事（如校验 token），也可在“返回时”做事（如记录耗时）。`c.Next()` 就是“放行进入下一层”的开关——调用它之前是前置逻辑，之后是后置逻辑。\n\n## 核心知识点（锚定官方）\n\n- **全局与路由组中间件**：`r.Use(gin.Logger(), gin.Recovery())` 全局注册；`g := r.Group(\"/api\", authMw)` 仅该组生效。[中间件示例](https://gin-gonic.com/docs/examples/using-middleware/)\n- **编写中间件**：`func auth() gin.HandlerFunc { return func(c *gin.Context){ token:=c.GetHeader(\"Authorization\"); if token==\"\" { c.AbortWithStatusJSON(401,...) ; return }; c.Next() } }`。[自定义中间件](https://gin-gonic.com/docs/examples/custom-middleware/)\n- **`Abort` 系列**：`c.Abort()` / `c.AbortWithStatusJSON(...)` 终止后续 handler 与中间件，用于鉴权失败立即返回。\n- **`c.Set`/`c.Get`**：在中间件存取值（如解析出的用户），后续 handler 取用，实现请求上下文传递。\n\n## 常见坑\n\n- **忘了 `c.Next()`**：在需要继续流程的中间件里漏掉 `Next()`，请求会卡住不进入 handler。\n- **`Abort` 后仍写响应**：`AbortWithStatusJSON` 已写响应，后面别再 `c.JSON` 造成重复写。\n- **`Recovery` 缺失导致 panic 宕机**：生产环境务必 `r.Use(gin.Recovery())`，否则未捕获 panic 会击垮进程。\n\n## 动手自测\n\n```go\nfunc Logger() gin.HandlerFunc {\n    return func(c *gin.Context) {\n        start := time.Now()\n        c.Next()\n        log.Printf(\"%s %s %v\", c.Request.Method, c.Request.URL.Path, time.Since(start))\n    }\n}\n```\n\n## 面试视角\n\n- **Gin 中间件的执行顺序？**（答：注册顺序即洋葱层顺序，请求进、响应出的双向穿过；`Next()` 划分前置/后置）\n- **`Abort` 之后中间件还会执行吗？**（答：当前中间件 `Next()` 之后的代码仍执行，但后续 handler 不再执行）" },
      { id: 'go-c2-s3', title: '参数绑定与校验', direction: '用结构体标签做请求体/查询参数绑定与业务校验。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n绑定是把“散落的请求数据”（JSON body、query、表单）**按一张结构图纸（struct + tag）自动归位**的过程。tag 上的 `binding:\"required,email\"` 是图纸上的“验收标准”——Gin 在归位后逐条核对，不合格直接报错，省去手写 `if x==\"\"` 的样板。\n\n## 核心知识点（锚定官方）\n\n- **绑定方法**：`ShouldBindJSON`(body)、`ShouldBindQuery`(query)、`ShouldBindUri`(path)、`ShouldBind`(按 Content-Type)。[绑定文档](https://gin-gonic.com/docs/examples/binding-and-validation/)\n- **校验标签**：`binding:\"required\"` 必填；`binding:\"required,email\"` 邮箱格式；`binding:\"gte=0,lte=120\"` 数值范围。[校验示例](https://gin-gonic.com/docs/examples/binding-and-validation/)\n- **自定义校验**：实现 `validator.Func` 并通过 `binding.Validator.Engine().(*validator.Validate).RegisterValidation(\"skill\", fn)` 注册自定义规则。\n- **错误响应**：`if err := c.ShouldBindJSON(&req); err != nil { c.JSON(400, gin.H{\"error\": err.Error()}); return }`。\n\n## 常见坑\n\n- **`ShouldBind` 对表单误判**：Content-Type 为 form 时 `ShouldBind` 走表单策略，body JSON 解析失败——明确用 `ShouldBindJSON`。\n- **时间/枚举字段零值**：`required` 对 `0`、空字符串、false 都视为“未填”，若业务允许零值需用指针或 `omitempty`。\n- **错误信息暴露内部细节**：直接 `err.Error()` 返回可能泄露结构，生产应映射为友好提示。\n\n## 动手自测\n\n```go\ntype Req struct {\n    Name  string `json:\"name\" binding:\"required\"`\n    Email string `json:\"email\" binding:\"required,email\"`\n}\nr.POST(\"/u\", func(c *gin.Context){\n    var req Req\n    if err := c.ShouldBindJSON(&req); err != nil {\n        c.JSON(400, gin.H{\"error\": err.Error()}); return\n    }\n    c.JSON(200, req)\n})\n```\n\n## 面试视角\n\n- **为什么用标签校验而非手写 if？**（答：声明式、集中、可复用，且与 OpenAPI/文档生成可联动）\n- **`required` 对零值的处理？**（答：零值（0/\"\"/false）会被判为未提供，允许零值需 `omitempty` 或指针类型）" },
      { id: 'go-c2-s4', title: '统一错误处理与响应', direction: '封装统一响应结构与全局错误恢复，提升 API 一致性。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\n把 API 响应想象成**统一的快递单格式**：无论包裹内容是成功数据还是错误说明，都贴同一张单子（固定字段 `code/message/data`）。这样前端永远按同一套规则拆包，不必每个接口猜结构。全局 `Recovery` 中间件则是“兜底保险”——任何 handler 意外 panic 都被它接住，转成 500 单子返回，绝不裸奔崩溃。\n\n## 核心知识点（锚定官方）\n\n- **统一响应封装**：定义 `type Resp struct{ Code int `json:\"code\"`; Msg string `json:\"msg\"`; Data any `json:\"data\"` }`，提供 `OK(c,data)` / `Fail(c,code,msg)` 辅助函数。[JSON 渲染](https://gin-gonic.com/docs/examples/json-rendering/)\n- **全局 Recovery**：`r.Use(gin.Recovery())` 捕获 panic 并返回 500，避免进程退出。\n- **自定义 Recovery**：`r.Use(gin.CustomRecovery(func(c *gin.Context, err any){ c.JSON(500, Resp{Code:500, Msg:\"internal\"}) }))` 定制错误体。\n- **业务错误码**：用 `errors.New`/自定义 error 类型承载领域错误（如 `ErrNotFound`），handler 翻译为对应 code。\n\n## 常见坑\n\n- **每个 handler 各自返回结构**：缺少封装导致前端拆包逻辑碎片化，应统一 `Resp`。\n- **`Recovery` 未注册**：生产环境遗漏则单点 panic 拖垮整个服务。\n- **敏感错误外泄**：把底层 DB 报错原文返回，可能泄露表结构——应转译为通用提示并记录日志。\n\n## 动手自测\n\n```go\nfunc OK(c *gin.Context, data any) { c.JSON(200, Resp{Code:0, Msg:\"ok\", Data:data}) }\nfunc Fail(c *gin.Context, code int, msg string) { c.JSON(200, Resp{Code:code, Msg:msg}) }\nr.Use(gin.Recovery())\n```\n\n## 面试视角\n\n- **为什么需要统一响应结构？**（答：前后端契约一致，前端可写通用拦截器，降低耦合与维护成本）\n- **`Recovery` 中间件的作用边界？**（答：只兜住 panic 转 500，业务错误仍需在 handler 显式处理，不可依赖它做正常流程控制）" }
    ]
  },
  {
    id: 'py-c1', subtrack: 'python', position: 101,
    title: 'Python 基础与异步',
    goal: '掌握 Python 虚拟环境、类型标注与 asyncio 异步模型，能编写可维护的 Python 服务。',
    sections: [
      { id: 'py-c1-s1', title: '环境管理与虚拟环境', direction: '用 venv/pyenv 隔离依赖，理解包管理与可复现环境。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n虚拟环境是**给每个项目单独配的“工具箱”**：`python -m venv .venv` 在项目里造一个独立 Python 副本与 `site-packages`，`source .venv/bin/activate`（Windows 为 `.venv\\Scripts\\activate`）把当前 shell 的 `python`/`pip` 指向它。这样 A 项目要 Django 4、B 项目要 Django 3，互不打架。`requirements.txt`/`pyproject.toml` 则是**工具箱清单**，一键复现。\n\n## 核心知识点（锚定官方）\n\n- **venv 创建与激活**：`python -m venv .venv`；激活后 `pip install` 仅装进该环境。[venv 文档](https://docs.python.org/3/library/venv.html)\n- **依赖记录**：`pip freeze > requirements.txt` 导出锁定版本；`pip install -r requirements.txt` 复现。[pip 文档](https://pip.pypa.io/en/stable/)\n- **pyproject.toml**：现代项目用 `[project]` 声明依赖与构建，配合 `pip`/`uv`/`poetry` 管理，逐步取代 setup.py。[打包指南](https://packaging.python.org/en/latest/)\n- **pyenv（多版本）**：在同一机器切换 Python 版本，解决系统 Python 不可随意升级的问题。\n\n## 常见坑\n\n- **装到系统 Python**：忘了激活 venv，`pip install` 污染全局，导致权限错误或影响系统工具。\n- **Windows 激活路径**：必须用 `.venv\\Scripts\\activate`（PowerShell 还需设执行策略），直接运行 activate 脚本报错。\n- **`python` 指向错版本**：系统有多 Python 时，`python`/`python3` 混用致装 A 跑 B，建议用 venv 内的解释器。\n\n## 动手自测\n\n```bash\npython -m venv .venv\nsource .venv/bin/activate   # Windows: .venv\\Scripts\\activate\npython -m pip install --upgrade pip\npip install fastapi\npip freeze > requirements.txt\n```\n\n## 面试视角\n\n- **为什么需要虚拟环境？**（答：隔离项目依赖，避免版本冲突，保证可复现与可部署）\n- **`requirements.txt` 与 `pyproject.toml` 的区别？**（答：前者是扁平依赖锁定，后者是 PEP 517/621 现代项目元数据，含构建与依赖声明）" },
      { id: 'py-c1-s2', title: '类型标注与 dataclass', direction: '用类型标注与 dataclass 提升代码可读性与可维护性。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n类型标注是**给变量贴“成分标签”**：Python 运行时仍动态，但标签让 IDE/类型检查器（mypy）像静态语言一样在写代码时就抓出“把字符串当整数加”的低级错。运行时它们不强制——是“建议”而非“铁律”。`dataclass` 则像**自动打包机**：你声明字段，`@dataclass` 自动生成 `__init__`/`__repr__`/`__eq__`，省掉样板。\n\n## 核心知识点（锚定官方）\n\n- **基础标注**：`name: str = \"\"`、`def add(a: int, b: int) -> int: ...`。[类型标注规范](https://docs.python.org/3/library/typing.html)\n- **dataclass**：`@dataclass` 自动生成构造/比较/打印；`field(default=...)` 设默认值，`order=True` 支持排序。[dataclasses 文档](https://docs.python.org/3/library/dataclasses.html)\n- ** typing 常用**：`List`/`Dict`/`Optional`/`Union`；Python 3.9+ 也可用内置 `list[int]`/`dict[str,int]`。[typing 参考](https://docs.python.org/3/library/typing.html)\n- **mypy 检查**：`pip install mypy && mypy app.py` 做静态类型检查，CI 中常作为质量门禁。\n\n## 常见坑\n\n- **可变默认值的陷阱**：`@dataclass` 中 `items: list = []` 会被所有实例共享，必须用 `field(default_factory=list)`。\n- **标注不强制**：运行时 `x: int = \"str\"` 不报错，类型检查需 mypy 等工具，别把标注当运行时校验。\n- **Python 版本差异**：`list[int]` 语法需 3.9+，老版本需用 `typing.List`。\n\n## 动手自测\n\n```python\nfrom dataclasses import dataclass, field\nfrom typing import List\n\n@dataclass\nclass User:\n    name: str\n    tags: List[str] = field(default_factory=list)\n\nu = User(name=\"a\", tags=[\"x\"])\nprint(u)  # User(name='a', tags=['x'])\n```\n\n## 面试视角\n\n- **类型标注在运行时生效吗？**（答：不生效，仅辅助静态分析与 IDE；强制校验需 mypy 或 pydantic 在运行时解析）\n- **为什么推荐 dataclass？**（答：减少样板代码、默认生成常用方法、可读性高，适合建模纯数据对象）" },
      { id: 'py-c1-s3', title: 'asyncio 异步模型', direction: '理解事件循环、协程与 await，能编写高并发 IO 程序。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\nasyncio 像**一个单线程里的“超级服务员”**：他在事件循环（event loop）这台旋转餐台上不断转圈，遇到 `await` 的“等菜”操作（网络 IO）就把当前客人暂时放下、去服务别人，菜好了再回来继续。单线程并发靠“不阻塞地切换”实现高吞吐——适合大量 IO 等待，而非 CPU 密集计算。\n\n## 核心知识点（锚定官方）\n\n- **协程与 await**：`async def` 定义协程，`await` 挂起等待可等待对象（coroutine/Task/Future）。[asyncio 文档](https://docs.python.org/3/library/asyncio.html)\n- **事件循环**：`asyncio.run(main())` 创建并运行循环直到完成；`asyncio.create_task(coro)` 并发调度协程。\n- **`asyncio.gather`**：`await asyncio.gather(a(), b())` 并发运行多个协程并收集结果。\n- **与同步库混用**：阻塞调用（如 `requests.get`）会卡住整个循环，IO 场景应换 `aiohttp`/`httpx.AsyncClient` 等异步库。\n\n## 常见坑\n\n- **在协程里调同步阻塞函数**：`time.sleep`/`requests` 阻塞事件循环，应 `await asyncio.sleep` 或用线程池 `loop.run_in_executor`。\n- **忘了 `await`**：`asyncio.create_task(coro)` 后若从未 `await`，任务可能不执行或被取消。\n- **循环已关闭再 run**：`asyncio.run` 不能嵌套，重复调用报“事件循环已关闭”。\n\n## 动手自测\n\n```python\nimport asyncio\nasync def fetch(n):\n    await asyncio.sleep(1)\n    return n\nasync def main():\n    res = await asyncio.gather(fetch(1), fetch(2))\n    print(res)  # [1, 2]\nasyncio.run(main())\n```\n\n## 面试视角\n\n- **协程为什么比线程轻？**（答：协程在单线程内由 runtime 调度，无上下文切换与锁开销，适合 IO 密集；CPU 密集仍需多进程）\n- **`await` 到底做了什么？**（答：挂起当前协程，把控制权交还事件循环去跑别的任务，IO 完成后恢复）" },
      { id: 'py-c1-s4', title: '项目结构与模块组织', direction: '用包/模块组织代码，理解导入机制与循环依赖规避。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nPython 的包（目录 + `__init__.py`）像**带门牌号的抽屉柜**，模块（`.py` 文件）是抽屉。导入（`import`）就是“按门牌号取抽屉里的工具”。`__init__.py` 决定这个柜子对外暴露什么（可放公开 API）。循环依赖（A 导入 B、B 又导入 A）像**两个抽屉互相锁死**，需在函数内延迟导入或抽出公共模块打破。\n\n## 核心知识点（锚定官方）\n\n- **包与 `__init__.py`**：目录含 `__init__.py` 即为包；可在此聚合公开接口。[导入系统](https://docs.python.org/3/reference/import.html)\n- **绝对 vs 相对导入**：`from mypkg.sub import x`（绝对）清晰；`from .sub import x`（相对，仅包内）避免硬编码。[相对导入](https://docs.python.org/3/reference/import.html#package-relative-imports)\n- **`if __name__ == '__main__'`**：模块被直接运行 vs 被导入时分支处理，避免导入即触发副作用。\n- **循环依赖**：把共享类型抽到第三模块，或在函数体内局部 `import` 延迟解析。\n\n## 常见坑\n\n- **相对导入在脚本直接运行报错**：`python app.py` 直接跑含相对导入的包会报 `ImportError: attempted relative import with no known parent package`，应以模块方式运行（`python -m app`）。\n- **同名遮蔽**：本地文件命名与标准库冲突（如 `email.py`）导致导入错库。\n- **`__init__.py` 重活**：在其中 import 过多子模块拖慢导入，应延迟到使用处。\n\n## 动手自测\n\n```\n# 推荐的服务项目结构\n# myapi/\n#   main.py        # 入口\n#   app/\n#     __init__.py\n#     routes.py    # 路由\n#     models.py    # 数据模型\n#     deps.py      # 依赖（抽公共以破循环）\n```\n\n## 面试视角\n\n- **绝对导入与相对导入怎么选？**（答：库代码优先相对导入减少重构成本；应用入口用绝对导入更清晰）\n- **如何破除循环依赖？**（答：抽公共依赖到独立模块、改为函数内局部导入、或用依赖注入反转方向）" }
    ]
  },
  {
    id: 'py-c2', subtrack: 'python', position: 102,
    title: 'FastAPI Web 框架核心',
    goal: '用 FastAPI 构建类型安全的异步 API，掌握路由、依赖注入、Pydantic 校验与中间件。',
    sections: [
      { id: 'py-c2-s1', title: '路由与请求处理', direction: '用 FastAPI 定义路径/查询参数与请求体，返回 JSON 响应。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nFastAPI 把“函数签名”当成**接口契约**：你在 `def read(id: int, q: str = None)` 上标好参数类型，框架自动从路径/查询里取值、做类型转换与校验，还能据此生成 OpenAPI 文档与交互式 Swagger UI。类型标注在这里**不再是建议，而是运行时的验收规则**。\n\n## 核心知识点（锚定官方）\n\n- **快速起步**：`app = FastAPI()`；`@app.get(\"/items/{item_id}\")` 定义路由；`uvicorn main:app --reload` 运行。[FastAPI 第一教程](https://fastapi.tiangolo.com/tutorial/first-steps/)\n- **路径与查询参数**：路径参数 `item_id: int` 自动转换；查询参数 `q: str = None` 可选；`required: bool` 必填。[路径参数](https://fastapi.tiangolo.com/tutorial/path-params/)\n- **请求体**：定义 `class Item(BaseModel)`，handler 参数声明 `item: Item`，FastAPI 自动解析 JSON 并校验。[请求体](https://fastapi.tiangolo.com/tutorial/body/)\n- **自动文档**：访问 `/docs`（Swagger UI）与 `/redoc` 自动生成交互式 API 文档，无需手写。\n\n## 常见坑\n\n- **查询参数被误当路径**：`/items/{id}` 只取路径，额外参数需作为函数普通参数（自动归为 query）。\n- **Pydantic 模型字段名与 JSON 不一致**：用 `Field(alias=...)` + `populate_by_name` 处理前端不同命名。\n- **`None` 默认值陷阱**：`q: str = None` 与 `q: Optional[str] = None` 行为不同（后者类型更严谨），建议显式 `Optional`。\n\n## 动手自测\n\n```python\nfrom fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI()\nclass Item(BaseModel):\n    name: str\n    price: float\n\n@app.get(\"/items/{item_id}\")\ndef read(item_id: int, q: str = None):\n    return {\"item_id\": item_id, \"q\": q}\n\n@app.post(\"/items\")\ndef create(item: Item):\n    return item\n# uvicorn main:app --reload\n```\n\n## 面试视角\n\n- **FastAPI 为什么快且类型安全？**（答：基于 Starlette 异步 + Pydantic 数据校验，类型标注驱动自动校验与文档生成）\n- **路径参数与查询参数的区别？**（答：路径参数在 URL 路径中必填且参与路由匹配；查询参数在 `?` 后，可选、不参与匹配）" },
      { id: 'py-c2-s2', title: '依赖注入系统', direction: '用 Depends 复用鉴权/数据库连接等逻辑，理解可组合依赖。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\n依赖注入（DI）像**乐高卡扣**：你声明“这个接口需要先拿到当前用户（`Depends(get_current_user)`）”，框架在调用前自动把依赖组装好、像扣上卡扣一样传进来。依赖还能**嵌套依赖**（获取 DB 连接 → 基于连接获取用户），框架递归解析整张依赖图，复用与测试都更轻松。\n\n## 核心知识点（锚定官方）\n\n- **`Depends` 基础**：`def get_db(): ...; @app.get('/x') def h(db = Depends(get_db))` 自动调用并注入。[依赖注入](https://fastapi.tiangolo.com/tutorial/dependencies/)\n- **类作为依赖**：依赖可是一个类，`Depends(Class)` 会被实例化并注入，常用于共享配置/状态。\n- **子依赖**：`get_current_user(db: Session = Depends(get_db))`——依赖本身也能声明依赖，框架递归解析。\n- **`Security` 与 `OAuth2`**：`fastapi.security` 提供 `OAuth2PasswordBearer` 等，与 `Depends` 结合做鉴权。[安全教程](https://fastapi.tiangolo.com/tutorial/security/)\n\n## 常见坑\n\n- **依赖里做重活**：依赖每次请求都执行，放 DB 连接池获取没问题，但放昂贵计算要缓存（`lru_cache`/请求级缓存）。\n- **循环依赖**：A 依赖 B、B 依赖 A 会栈溢出，应抽公共依赖或改用参数传递。\n- **`yield` 依赖的资源释放**：用 `yield` 的依赖（如 DB session）需在 `try/finally` 或 `finally` 后关闭，异常时也能回收。\n\n## 动手自测\n\n```python\nfrom fastapi import Depends\n\ndef get_token(x_token: str = Header(None)):\n    if not x_token: raise HTTPException(401)\n    return x_token\n\n@app.get(\"/me\")\ndef me(tok: str = Depends(get_token)):\n    return {\"token\": tok}\n```\n\n## 面试视角\n\n- **依赖注入解决了什么问题？**（答：解耦依赖创建与使用，提升复用、可测试性与可读性）\n- **`Depends` 与普通函数调用的区别？**（答：`Depends` 由框架在请求生命周期内解析、可嵌套、可共享，且参与 OpenAPI 描述）" },
      { id: 'py-c2-s3', title: 'Pydantic 数据校验', direction: '用 Pydantic 模型做请求/响应校验与序列化，理解字段约束。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nPydantic 像**带门禁的转换器**：你定义 `class User(BaseModel)`，它就在“原始 JSON”进门时做类型转换（字符串→整数）、按 `Field` 规则验收（长度/范围/正则），不合格直接拦在门外（抛出清晰错误）。出门时（响应）再把 Python 对象序列化为 JSON。数据进出门都有人管。\n\n## 核心知识点（锚定官方）\n\n- **模型定义**：`class Item(BaseModel): name: str; price: float = Field(gt=0)`。[Pydantic 文档](https://docs.pydantic.dev/latest/)\n- **字段约束**：`Field(gt=0, le=100, max_length=50, pattern=r'^\\w+$')` 表达数值/长度/正则规则。\n- **嵌套与列表**：模型字段可为另一模型或 `List[SubModel]`，自动递归校验。\n- **`ConfigDict`**：`model_config = ConfigDict(from_attributes=True)` 支持从 ORM 对象加载（响应模型常用）。\n\n## 常见坑\n\n- **`gt=0` 与 `ge=0` 混淆**：价格用 `gt=0`（不含 0），数量用 `ge=0`（含 0），语义不同。\n- **datetime 解析**：ISO8601 字符串自动转 `datetime`，但时区缺失会按 naive 处理，跨时区需显式 `tzinfo`。\n- **`None` 与 `Optional`**：必填字段不可给 `None`，需显式 `Optional[X] = None`。\n\n## 动手自测\n\n```python\nfrom pydantic import BaseModel, Field\nclass Item(BaseModel):\n    name: str = Field(max_length=50)\n    price: float = Field(gt=0)\n# Item(name=\"a\", price=9.9) -> ok\n# Item(name=\"a\", price=-1) -> ValidationError\n```\n\n## 面试视角\n\n- **Pydantic v1 与 v2 的主要差异？**（答：v2 用 Rust 核心提速、校验 API 调整、`ConfigDict` 取代 `Config` 内部类，迁移需注意 `parse_obj` 等弃用）\n- **为什么用 Pydantic 而非手写校验？**（答：声明式、自动类型转换、错误清晰、与 FastAPI 深度集成生成文档）" },
      { id: 'py-c2-s4', title: '中间件与异常处理', direction: '用中间件做跨切面逻辑，统一异常响应与 CORS。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\n中间件是**横在请求路上的安检门**：每个请求进出都要过这道门——进来时记日志/校验，出去时加 CORS 头/统一错误体。FastAPI 基于 ASGI，中间件是异步的（`async def`），与 Starlette 的 `BaseHTTPMiddleware` 一致。异常处理则把“散落的 try/except”集中成**统一急诊室**：某类异常（如 `ItemNotFound`）全局捕获并转成标准错误响应。\n\n## 核心知识点（锚定官方）\n\n- **自定义中间件**：`@app.middleware(\"http\")` + `async def mw(request, call_next): resp = await call_next(request); return resp`。[中间件](https://fastapi.tiangolo.com/tutorial/middleware/)\n- **CORS**：`from fastapi.middleware.cors import CORSMiddleware; app.add_middleware(CORSMiddleware, allow_origins=[...])` 配置跨域。[CORS 文档](https://fastapi.tiangolo.com/tutorial/cors/)\n- **异常处理器**：`@app.exception_handler(ItemNotFound) def h(req, exc): return JSONResponse(status_code=404, content={...})` 统一响应。[异常处理](https://fastapi.tiangolo.com/tutorial/handling-errors/)\n- **统一响应**：结合 Pydantic 响应模型 `response_model=Resp` 保证出参结构一致。\n\n## 常见坑\n\n- **中间件是异步的**：在里面用同步阻塞调用会卡事件循环，需 `run_in_executor` 或异步库。\n- **CORS 配置过宽**：`allow_origins=['*']` 配合 `allow_credentials=True` 在浏览器被禁，生产应白名单具体域名。\n- **异常处理器与响应模型冲突**：异常返回的字段若未走 `response_model`，需直接返回 `JSONResponse` 绕开校验。\n\n## 动手自测\n\n```python\nfrom fastapi.middleware.cors import CORSMiddleware\napp.add_middleware(CORSMiddleware,\n    allow_origins=[\"https://app.example.com\"],\n    allow_methods=[\"*\"], allow_headers=[\"*\"])\n@app.exception_handler(ValueError)\ndef ve_handler(request, exc):\n    return JSONResponse(400, {\"msg\": str(exc)})\n```\n\n## 面试视角\n\n- **FastAPI 中间件与依赖注入的分工？**（答：中间件处理全局横切（日志/CORS/错误包装），依赖注入处理请求内的可组合逻辑（鉴权/DB），职责不同）\n- **为什么 CORS 不能 `*` + credentials？**（答：浏览器安全策略禁止“任意源 + 带凭证”，需显式列出受信源）" }
    ]
  }
]

function applySeed() {
  const raw = fs.readFileSync(SEED_PATH, 'utf-8')
  const content = JSON.parse(raw)
  const mod = content.modules.find((m) => m.id === 'backend')
  if (!mod) throw new Error('backend module not found')
  let added = 0
  for (const ch of CHAPTERS) {
    if (mod.chapters.some((c) => c.id === ch.id)) {
      console.log(`[seed] 跳过已存在 ${ch.id}`)
      continue
    }
    mod.chapters.push({
      id: ch.id, title: ch.title, goal: ch.goal, subtrack: ch.subtrack, sections: ch.sections
    })
    added++
  }
  if (added > 0) fs.writeFileSync(SEED_PATH, JSON.stringify(content))
  return added
}

function applyDb() {
  const db = new Database(DB_PATH)
  db.pragma('journal_mode = WAL')
  const insCh = db.prepare('INSERT OR IGNORE INTO chapters (id,module_id,title,goal,position,subtrack) VALUES (?,?,?,?,?,?)')
  const insSec = db.prepare('INSERT OR IGNORE INTO sections (id,chapter_id,title,direction,content,position) VALUES (?,?,?,?,?,?)')
  const tx = db.transaction(() => {
    for (const ch of CHAPTERS) {
      insCh.run(ch.id, 'backend', ch.title, ch.goal, ch.position, ch.subtrack)
      ch.sections.forEach((s, i) => insSec.run(s.id, ch.id, s.title, s.direction ?? null, s.content, i))
    }
  })
  tx()
  db.close()
}

if (DRY) {
  console.log('[dry-run] 将新增章节:')
  for (const ch of CHAPTERS) console.log(`  ${ch.id} [${ch.subtrack}] pos=${ch.position} | ${ch.title} (${ch.sections.length} 节)`)
  console.log('[dry-run] 未做任何修改')
} else {
  const added = applySeed()
  console.log(`[seed] 新增 ${added} 章`)
  applyDb()
  console.log(`[db] 已写入 ${CHAPTERS.length} 章（INSERT OR IGNORE，已存在则跳过）`)
  console.log('完成 Batch 1：go-c1/go-c2 (Go+Gin) + py-c1/py-c2 (Python+FastAPI)。')
}
