// 一次性执行器：为 be-web 赛道补齐 Go(Gin) / Python(FastAPI) 内容，最终 be-web → java/go/python 三子主题。
// 内容零虚构：全部锚定官方文档（go.dev / gin-gonic.com / docs.python.org / fastapi.tiangolo.com），
// 结构对齐既有 Java 章节（header + 心智模型 + 核心知识点(锚定官方) + 常见坑 + 动手自测 + 面试视角）。
// 分批执行：本脚本按 BATCH 常量控制本批生成的章节，幂等可重跑（已存在章节跳过，DB 用 INSERT OR IGNORE）。
// 双写 data/seed-content.json（真源）+ data/devmentor.db。支持 --dry-run。
import fs from 'node:fs'
import Database from 'better-sqlite3'
import { BATCH3 } from './beweb-batch3.mjs'

const SEED_PATH = './data/seed-content.json'
const DB_PATH = './data/devmentor.db'
const DRY = process.argv.includes('--dry-run')

// 本批生成 4 章：go-c1/go-c2 (Go+Gin) + py-c1/py-c2 (Python+FastAPI)
// position 从 backend 模块当前 MAX+1 起顺序分配
const CHAPTERS = [
  {
    id: 'go-c1', subtrack: 'go', position: 99,
    title: 'Go 基础与并发模型',
    goal: '掌握 Go 的语法基础与 goroutine/channel 并发模型，能编写并发安全的 Go 程序。',
    sections: [
      { id: 'go-c1-s1', title: '语言入门与开发环境', direction: '能安装 Go 工具链、配置 GOPATH/GOPROXY 并运行第一个程序。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n把 Go 工具链想成**一套自带电池的厨具**：`go` 命令既是“切菜机”（`go build` 编译）也是“炒锅”（`go run` 直接运行），而 `GOPATH`/`GOMODCACHE` 是**食材仓库**——所有下载的第三方包都放在这里。`GOPROXY` 则是**采购渠道**，告诉 `go` 去哪个镜像（如 `https://proxy.golang.org`）拉依赖，国内常配 `https://goproxy.cn`。\n\n## 核心知识点（锚定官方）\n\n- **安装与版本**：从 [Go 官方下载页](https://go.dev/dl/) 安装后，`go version` 验证。Go 1.21+ 推荐使用 `go install` 管理工具链。[Go 安装指南](https://go.dev/doc/install)\n- **GOPATH 与模块**：Go 1.11 引入 Go Modules 后不再强依赖 `GOPATH` 写业务代码；项目根目录 `go.mod` 声明模块路径与 Go 版本。`go env GOPATH` 查看当前值，默认 `~/go`。[Go Modules 参考](https://go.dev/ref/mod)\n- **GOPROXY 配置**：`go env -w GOPROXY=https://goproxy.cn,direct` 设置国内镜像，`direct` 表示镜像失败时回源。[代理配置文档](https://go.dev/ref/mod#environment-variables)\n- **最小程序**：`package main` + `func main()` 是入口；`go run main.go` 直接编译运行，`go build` 产出二进制。[Go 教程](https://go.dev/doc/tutorial/getting-started)\n\n## 常见坑\n\n- **未初始化模块**：在空目录直接 `go run` 报错 `go.mod file not found`——先 `go mod init <module>`。\n- **GOPROXY 未设导致拉不下来**：公司网络下 `go get` 超时，需配 `GOPROXY` 与 `GOSUMDB=off`（仅内网可信场景）。\n- **`main` 包缺失**：非 `package main` 的文件 `go run` 找不到入口，报 `no Go files in ...`。\n\n## 动手自测\n\n```bash\n# 1. 初始化模块\ngo mod init example/hello\n# 2. 编写 main.go\n# 3. 运行\ngo run .   # 或 go run main.go\n# 4. 编译二进制\ngo build -o hello .\n```\n\n## 面试视角\n\n- **GOPATH 与 Go Modules 的区别？**（答：GOPATH 是全局单仓库模式，Modules 是项目级依赖声明，解决版本与多项目隔离）\n- **GOPROXY 的作用？**（答：指定模块代理以提升拉取速度与可用性，避免直连 github 超时）" },
      { id: 'go-c1-s2', title: '变量、类型与零值', direction: '理解 Go 的静态类型、零值约定与简洁声明语法。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nGo 的类型像**贴了标签的盒子**：声明时盒子的“形状”（类型）就固定了，往里放错形状的东西编译器直接拒绝。未显式初始化的盒子会自动装入**零值**（数字=0、字符串=\"\"、指针/切片/map=nil）——这是 Go“显式优于隐式”哲学的体现，没有 Java 那种“未初始化局部变量编译报错”的约束，但零值是确定且安全的。\n\n## 核心知识点（锚定官方）\n\n- **声明与短声明**：`var x int = 10` 显式声明；函数内 `x := 10` 用类型推断（短声明），仅限函数内部。[变量声明](https://go.dev/ref/spec#Variable_declarations)\n- **零值**：`var s []int` 得到 nil 切片而非报错；`var m map[string]int` 为 nil，**直接赋值会 panic**，须 `make` 或字面量初始化。[零值规范](https://go.dev/ref/spec#The_zero_value)\n- **基础类型**：`int/int64`、`float64`、`string`（不可变）、`bool`、`rune`（Unicode 码点）、`byte`(=uint8)。[基础类型](https://go.dev/ref/spec#Numeric_types)\n- **`new` vs `make`**：`new(T)` 返回 `*T`（零值指针）；`make` 仅用于 slice/map/channel，返回已初始化的**非指针**对象。[内置函数](https://go.dev/ref/spec#Allocation)\n\n## 常见坑\n\n- **nil map 写入 panic**：`var m map[string]int; m[\"a\"]=1` 运行时 panic，应 `m := make(map[string]int)`。\n- **短声明作用域陷阱**：`if x := f(); x>0 { }` 中 `x` 仅在该块可见；与外层同名变量混用易出错。\n- **`int` 长度依赖平台**：32 位系统 `int`=32 位，网络/文件协议需显式 `int64` 避免截断。\n\n## 动手自测\n\n```go\npackage main\nimport \"fmt\"\nfunc main() {\n    var s []int            // 零值 nil\n    fmt.Println(s == nil)  // true\n    m := make(map[string]int)\n    m[\"a\"] = 1\n    x := 10               // 短声明\n    fmt.Println(x, m)\n}\n```\n\n## 面试视角\n\n- **Go 的零值设计解决了什么问题？**（答：消除“未初始化变量”的不确定性，所有变量都有确定初值，减少空指针类 bug）\n- **`new` 和 `make` 的区别？**（答：`new` 分配零值并返回指针；`make` 初始化 slice/map/channel 的运行时结构并返回对象）" },
      { id: 'go-c1-s3', title: '结构体与方法', direction: '用结构体建模领域对象，并理解值/指针接收者的区别。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nGo 没有“类”与“继承”，只有**结构体（盒子）+ 方法（贴在盒子上的函数）**。方法通过“接收者”绑定到类型：`func (u User) Name()` 是值接收者（操作副本），`func (u *User) SetName()` 是指针接收者（操作原身）。组合（把结构体嵌入另一个结构体）替代继承，实现代码复用——这是 Go“组合优于继承”的设计取舍。\n\n## 核心知识点（锚定官方）\n\n- **结构体字面量**：`User{Name:\"a\"}` 字段名显式初始化，顺序可乱；`User{\"a\",1}` 必须按定义顺序。[结构体类型](https://go.dev/ref/spec#Struct_types)\n- **方法接收者**：值接收者 `(u User)` 接收副本，适合小型不可变数据；指针接收者 `(u *User)` 可修改原对象，且避免大对象拷贝。[方法声明](https://go.dev/ref/spec#Method_declarations)\n- **匿名字段/嵌入**：`type Admin struct { User; Level int }` 嵌入 `User`，`Admin` 直接拥有 `User` 的字段与方法（提升），实现组合复用。[嵌入](https://go.dev/ref/spec#Embedded_field)\n- **`struct{}` 空结构体**：不占内存，常用于 set（map[string]struct{}）或 channel 信号量。[内存布局](https://go.dev/wiki/CompilerOptimizations)\n\n## 常见坑\n\n- **值接收者误改字段**：`func (u User) Set() { u.Name=\"x\" }` 改的是副本，原对象不变——需用指针接收者。\n- **大写即导出**：字段/方法首字母大写才对包外可见，小写是包内私有，常因忘大写导致序列化丢字段。\n- **比较含 slice/map 的结构体**：含不可比较字段的结构体不能用 `==`，会编译报错。\n\n## 动手自测\n\n```go\ntype User struct{ Name string; Age int }\nfunc (u *User) Grow() { u.Age++ }   // 指针接收者改原身\nfunc main() {\n    u := &User{Name:\"a\", Age:1}\n    u.Grow()\n    fmt.Println(u.Age) // 2\n}\n```\n\n## 面试视角\n\n- **何时用指针接收者？**（答：需修改接收者、结构体较大避免拷贝、或需一致性——同一类型的其他方法已用指针时统一用指针）\n- **Go 如何实现“继承”？**（答：用结构体嵌入做组合，而非传统继承）" },
      { id: 'go-c1-s4', title: 'Goroutine 与 Channel', direction: '用 goroutine + channel 编写并发程序，理解“不要通过共享内存通信”原则。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\ngoroutine 是**轻量到极致的工人**（初始栈仅 2KB，由 runtime 调度到 OS 线程上），`go func()` 一句话就能雇一个。但多个工人抢同一份数据会出乱子——Go 的箴言是：**“不要通过共享内存来通信，而要通过通信来共享内存”**。channel 就是工人之间传递数据的**传送带**，谁要用数据就从传送带上取，天然避免了锁。\n\n## 核心知识点（锚定官方）\n\n- **启动 goroutine**：`go doWork()` 异步执行，主协程退出则全部退出，需用 `sync.WaitGroup` 或 channel 等待。[Go 并发教程](https://go.dev/doc/tutorial/golang-with-google)\n- **Channel 基础**：`ch := make(chan int)` 无缓冲（同步）；`make(chan int, 3)` 有缓冲（异步到容量）。`ch <- v` 发送，`v := <-ch` 接收，`close(ch)` 关闭。[Channel 类型](https://go.dev/ref/spec#Channel_types)\n- **`select` 多路复用**：`select { case v:=<-ch1: ...; case ch2<-x: ...; default: }` 等待多个 channel，类似 IO 多路复用。[select 语句](https://go.dev/ref/spec#Select_statements)\n- **`sync.WaitGroup`**：`Add/Done/Wait` 等待一组 goroutine 结束；`sync.Mutex` 用于必须共享内存时的互斥。[sync 包](https://pkg.go.dev/sync)\n\n## 常见坑\n\n- **主协程提前退出**：忘了 `WaitGroup`，goroutine 还没跑完程序就结束了。\n- **向已关闭 channel 发送 panic**：`close` 后还 `<- ch` 取值是安全的（返回零值+false），但 `ch <- x` 会 panic。\n- **goroutine 泄漏**：channel 无人接收且无人关闭，goroutine 永久阻塞。\n\n## 动手自测\n\n```go\nfunc main() {\n    ch := make(chan int, 2)\n    go func() { ch <- 1; ch <- 2; close(ch) }()\n    for v := range ch { fmt.Println(v) } // 1 2\n}\n```\n\n## 面试视角\n\n- **goroutine 与线程的区别？**（答：goroutine 由 Go runtime 调度、栈动态增长、创建成本极低，可轻松起数十万；线程由 OS 调度、栈固定 MB 级）\n- **channel 缓冲与否的语义差异？**（答：无缓冲是同步交接，发送接收双方必须同时就绪；有缓冲在未满/未空时可异步）" }
    ]
  },
  {
    id: 'go-c2', subtrack: 'go', position: 100,
    title: 'Gin Web 框架核心',
    goal: '使用 Gin 构建 RESTful API，掌握路由、中间件、参数绑定与统一错误处理。',
    sections: [
      { id: 'go-c2-s1', title: '路由与请求处理', direction: '用 Gin 注册路由、读取路径/查询/JSON 参数并返回响应。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nGin 的 `Engine` 像**一个带智能分拣台的快递中心**：`router.GET(\"/users/:id\", h)` 给不同“地址”（路由）挂上对应的“处理员”（handler）。请求进来后，分拣台按路径把包裹（请求）送到正确处理员手里；`:id` 是路径里的**可变格口**，处理员用 `c.Param(\"id\")` 从格口取件。\n\n## 核心知识点（锚定官方）\n\n- **快速起步**：`r := gin.Default(); r.GET(\"/ping\", func(c *gin.Context){ c.JSON(200, gin.H{\"msg\":\"pong\"}) }); r.Run(\":8080\")`。[Gin README](https://github.com/gin-gonic/gin)\n- **路由与参数**：`c.Param(\"id\")` 取路径参数；`c.Query(\"page\")` 取查询参数；`c.PostForm(\"name\")` 取表单。[API 示例](https://gin-gonic.com/docs/examples/)\n- **路由组**：`api := r.Group(\"/api\"); api.GET(\"/users\", ...)` 统一起前缀，便于版本化与中间件挂载。[分组路由](https://gin-gonic.com/docs/examples/grouping-routes/)\n- **JSON 绑定与校验**：`c.ShouldBindJSON(&req)` 将 body 反序列化为结构体，配合 `binding:\"required\"` 标签做校验。[绑定文档](https://gin-gonic.com/docs/examples/binding-and-validation/)\n\n## 常见坑\n\n- **`ShouldBind` vs `ShouldBindJSON`**：`ShouldBind` 按 Content-Type 选策略，表单请求会被误当 JSON；明确场景直接用 `ShouldBindJSON`/`ShouldBindQuery` 更安全。\n- **`c.JSON` 后忘记 return**：handler 里校验失败 `c.JSON(400,...)` 后若继续执行会二次写响应，panic。\n- **通配路由与冲突**：`/users/*action` 与 `/users/:id` 共存时匹配规则易混淆，注意注册顺序。\n\n## 动手自测\n\n```go\nfunc main() {\n    r := gin.Default()\n    r.GET(\"/users/:id\", func(c *gin.Context) {\n        id := c.Param(\"id\")\n        c.JSON(200, gin.H{\"id\": id})\n    })\n    r.Run(\":8080\")\n}\n```\n\n## 面试视角\n\n- **Gin 的 `Context` 为什么用指针接收？**（答：Context 内含请求/响应与内部状态，handler 共享同一实例，指针避免拷贝且可修改）\n- **路由冲突如何排查？**（答：Gin 基于 httprouter 的 radix 树，静态/参数/通配节点互斥，检查是否同一层级注册了冲突模式）" },
      { id: 'go-c2-s2', title: '中间件机制', direction: '理解 Gin 中间件的洋葱模型，能编写鉴权/日志/Recovery 中间件。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n中间件是**包裹在 handler 外的洋葱层**：请求从外向内穿过每层（日志→鉴权→…），到达核心 handler 后再由原路返回。每层可在“进入时”做事（如校验 token），也可在“返回时”做事（如记录耗时）。`c.Next()` 就是“放行进入下一层”的开关——调用它之前是前置逻辑，之后是后置逻辑。\n\n## 核心知识点（锚定官方）\n\n- **全局与路由组中间件**：`r.Use(gin.Logger(), gin.Recovery())` 全局注册；`g := r.Group(\"/api\", authMw)` 仅该组生效。[中间件示例](https://gin-gonic.com/docs/examples/using-middleware/)\n- **编写中间件**：`func auth() gin.HandlerFunc { return func(c *gin.Context){ token:=c.GetHeader(\"Authorization\"); if token==\"\" { c.AbortWithStatusJSON(401,...) ; return }; c.Next() } }`。[自定义中间件](https://gin-gonic.com/docs/examples/custom-middleware/)\n- **`Abort` 系列**：`c.Abort()` / `c.AbortWithStatusJSON(...)` 终止后续 handler 与中间件，用于鉴权失败立即返回。\n- **`c.Set`/`c.Get`**：在中间件存取值（如解析出的用户），后续 handler 取用，实现请求上下文传递。\n\n## 常见坑\n\n- **忘了 `c.Next()`**：在需要继续流程的中间件里漏掉 `Next()`，请求会卡住不进入 handler。\n- **`Abort` 后仍写响应**：`AbortWithStatusJSON` 已写响应，后面别再 `c.JSON` 造成重复写。\n- **`Recovery` 缺失导致 panic 宕机**：生产环境务必 `r.Use(gin.Recovery())`，否则未捕获 panic 会击垮进程。\n\n## 动手自测\n\n```go\nfunc Logger() gin.HandlerFunc {\n    return func(c *gin.Context) {\n        start := time.Now()\n        c.Next()\n        log.Printf(\"%s %s %v\", c.Request.Method, c.Request.URL.Path, time.Since(start))\n    }\n}\n```\n\n## 面试视角\n\n- **Gin 中间件的执行顺序？**（答：注册顺序即洋葱层顺序，请求进、响应出的双向穿过；`Next()` 划分前置/后置）\n- **`Abort` 之后中间件还会执行吗？**（答：当前中间件 `Next()` 之后的代码仍执行，但后续 handler 不再执行）" },
      { id: 'go-c2-s3', title: '参数绑定与校验', direction: '用结构体标签做请求体/查询参数绑定与业务校验。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n绑定是把“散落的请求数据”（JSON body、query、表单）**按一张结构图纸（struct + tag）自动归位**的过程。tag 上的 `binding:\"required,email\"` 是图纸上的“验收标准”——Gin 在归位后逐条核对，不合格直接报错，省去手写 `if x==\"\"` 的样板。\n\n## 核心知识点（锚定官方）\n\n- **绑定方法**：`ShouldBindJSON`(body)、`ShouldBindQuery`(query)、`ShouldBindUri`(path)、`ShouldBind`(按 Content-Type)。[绑定文档](https://gin-gonic.com/docs/examples/binding-and-validation/)\n- **校验标签**：`binding:\"required\"` 必填；`binding:\"required,email\"` 邮箱格式；`binding:\"gte=0,lte=120\"` 数值范围。[校验示例](https://gin-gonic.com/docs/examples/binding-and-validation/)\n- **自定义校验**：实现 `validator.Func` 并通过 `binding.Validator.Engine().(*validator.Validate).RegisterValidation(\"skill\", fn)` 注册自定义规则。\n- **错误响应**：`if err := c.ShouldBindJSON(&req); err != nil { c.JSON(400, gin.H{\"error\": err.Error()}); return }`。\n\n## 常见坑\n\n- **`ShouldBind` 对表单误判**：Content-Type 为 form 时 `ShouldBind` 走表单策略，body JSON 解析失败——明确用 `ShouldBindJSON`。\n- **时间/枚举字段零值**：`required` 对 `0`、空字符串、false 都视为“未填”，若业务允许零值需用指针或 `omitempty`。\n- **错误信息暴露内部细节**：直接 `err.Error()` 返回可能泄露结构，生产应映射为友好提示。\n\n## 动手自测\n\n```go\ntype Req struct {\n    Name  string `json:\"name\" binding:\"required\"`\n    Email string `json:\"email\" binding:\"required,email\"`\n}\nr.POST(\"/u\", func(c *gin.Context){\n    var req Req\n    if err := c.ShouldBindJSON(&req); err != nil {\n        c.JSON(400, gin.H{\"error\": err.Error()}); return\n    }\n    c.JSON(200, req)\n})\n```\n\n## 面试视角\n\n- **为什么用标签校验而非手写 if？**（答：声明式、集中、可复用，且与 OpenAPI/文档生成可联动）\n- **`required` 对零值的处理？**（答：零值（0/\"\"/false）会被判为未提供，允许零值需 `omitempty` 或指针类型）" },
      { id: 'go-c2-s4', title: '统一错误处理与响应', direction: '封装统一响应结构与全局错误恢复，提升 API 一致性。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\n把 API 响应想象成**统一的快递单格式**：无论包裹内容是成功数据还是错误说明，都贴同一张单子（固定字段 `code/message/data`）。这样前端永远按同一套规则拆包，不必每个接口猜结构。全局 `Recovery` 中间件则是“兜底保险”——任何 handler 意外 panic 都被它接住，转成 500 单子返回，绝不裸奔崩溃。\n\n## 核心知识点（锚定官方）\n\n- **统一响应封装**：定义 `type Resp struct{ Code int `json:\"code\"`; Msg string `json:\"msg\"`; Data any `json:\"data\"` }`，提供 `OK(c,data)` / `Fail(c,code,msg)` 辅助函数。[JSON 渲染](https://gin-gonic.com/docs/examples/json-rendering/)\n- **全局 Recovery**：`r.Use(gin.Recovery())` 捕获 panic 并返回 500，避免进程退出。\n- **自定义 Recovery**：`r.Use(gin.CustomRecovery(func(c *gin.Context, err any){ c.JSON(500, Resp{Code:500, Msg:\"internal\"}) }))` 定制错误体。\n- **业务错误码**：用 `errors.New`/自定义 error 类型承载领域错误（如 `ErrNotFound`），handler 翻译为对应 code。\n\n## 常见坑\n\n- **每个 handler 各自返回结构**：缺少封装导致前端拆包逻辑碎片化，应统一 `Resp`。\n- **`Recovery` 未注册**：生产环境遗漏则单点 panic 拖垮整个服务。\n- **敏感错误外泄**：把底层 DB 报错原文返回，可能泄露表结构——应转译为通用提示并记录日志。\n\n## 动手自测\n\n```go\nfunc OK(c *gin.Context, data any) { c.JSON(200, Resp{Code:0, Msg:\"ok\", Data:data}) }\nfunc Fail(c *gin.Context, code int, msg string) { c.JSON(200, Resp{Code:code, Msg:msg}) }\nr.Use(gin.Recovery())\n```\n\n## 面试视角\n\n- **为什么需要统一响应结构？**（答：前后端契约一致，前端可写通用拦截器，降低耦合与维护成本）\n- **`Recovery` 中间件的作用边界？**（答：只兜住 panic 转 500，业务错误仍需在 handler 显式处理，不可依赖它做正常流程控制）" }
    ]
  },
  {
    id: 'py-c1', subtrack: 'python', position: 101,
    title: 'Python 基础与异步',
    goal: '掌握 Python 虚拟环境、类型标注与 asyncio 异步模型，能编写可维护的 Python 服务。',
    sections: [
      { id: 'py-c1-s1', title: '环境管理与虚拟环境', direction: '用 venv/pyenv 隔离依赖，理解包管理与可复现环境。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n虚拟环境是**给每个项目单独配的“工具箱”**：`python -m venv .venv` 在项目里造一个独立 Python 副本与 `site-packages`，`source .venv/bin/activate`（Windows 为 `.venv\\Scripts\\activate`）把当前 shell 的 `python`/`pip` 指向它。这样 A 项目要 Django 4、B 项目要 Django 3，互不打架。`requirements.txt`/`pyproject.toml` 则是**工具箱清单**，一键复现。\n\n## 核心知识点（锚定官方）\n\n- **venv 创建与激活**：`python -m venv .venv`；激活后 `pip install` 仅装进该环境。[venv 文档](https://docs.python.org/3/library/venv.html)\n- **依赖记录**：`pip freeze > requirements.txt` 导出锁定版本；`pip install -r requirements.txt` 复现。[pip 文档](https://pip.pypa.io/en/stable/)\n- **pyproject.toml**：现代项目用 `[project]` 声明依赖与构建，配合 `pip`/`uv`/`poetry` 管理，逐步取代 setup.py。[打包指南](https://packaging.python.org/en/latest/)\n- **pyenv（多版本）**：在同一机器切换 Python 版本，解决系统 Python 不可随意升级的问题。\n\n## 常见坑\n\n- **装到系统 Python**：忘了激活 venv，`pip install` 污染全局，导致权限错误或影响系统工具。\n- **Windows 激活路径**：必须用 `.venv\\Scripts\\activate`（PowerShell 还需设执行策略），直接运行 activate 脚本报错。\n- **`python` 指向错版本**：系统有多 Python 时，`python`/`python3` 混用致装 A 跑 B，建议用 venv 内的解释器。\n\n## 动手自测\n\n```bash\npython -m venv .venv\nsource .venv/bin/activate   # Windows: .venv\\Scripts\\activate\npython -m pip install --upgrade pip\npip install fastapi\npip freeze > requirements.txt\n```\n\n## 面试视角\n\n- **为什么需要虚拟环境？**（答：隔离项目依赖，避免版本冲突，保证可复现与可部署）\n- **`requirements.txt` 与 `pyproject.toml` 的区别？**（答：前者是扁平依赖锁定，后者是 PEP 517/621 现代项目元数据，含构建与依赖声明）" },
      { id: 'py-c1-s2', title: '类型标注与 dataclass', direction: '用类型标注与 dataclass 提升代码可读性与可维护性。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n类型标注是**给变量贴“成分标签”**：Python 运行时仍动态，但标签让 IDE/类型检查器（mypy）像静态语言一样在写代码时就抓出“把字符串当整数加”的低级错。运行时它们不强制——是“建议”而非“铁律”。`dataclass` 则像**自动打包机**：你声明字段，`@dataclass` 自动生成 `__init__`/`__repr__`/`__eq__`，省掉样板。\n\n## 核心知识点（锚定官方）\n\n- **基础标注**：`name: str = \"\"`、`def add(a: int, b: int) -> int: ...`。[类型标注规范](https://docs.python.org/3/library/typing.html)\n- **dataclass**：`@dataclass` 自动生成构造/比较/打印；`field(default=...)` 设默认值，`order=True` 支持排序。[dataclasses 文档](https://docs.python.org/3/library/dataclasses.html)\n- ** typing 常用**：`List`/`Dict`/`Optional`/`Union`；Python 3.9+ 也可用内置 `list[int]`/`dict[str,int]`。[typing 参考](https://docs.python.org/3/library/typing.html)\n- **mypy 检查**：`pip install mypy && mypy app.py` 做静态类型检查，CI 中常作为质量门禁。\n\n## 常见坑\n\n- **可变默认值的陷阱**：`@dataclass` 中 `items: list = []` 会被所有实例共享，必须用 `field(default_factory=list)`。\n- **标注不强制**：运行时 `x: int = \"str\"` 不报错，类型检查需 mypy 等工具，别把标注当运行时校验。\n- **Python 版本差异**：`list[int]` 语法需 3.9+，老版本需用 `typing.List`。\n\n## 动手自测\n\n```python\nfrom dataclasses import dataclass, field\nfrom typing import List\n\n@dataclass\nclass User:\n    name: str\n    tags: List[str] = field(default_factory=list)\n\nu = User(name=\"a\", tags=[\"x\"])\nprint(u)  # User(name='a', tags=['x'])\n```\n\n## 面试视角\n\n- **类型标注在运行时生效吗？**（答：不生效，仅辅助静态分析与 IDE；强制校验需 mypy 或 pydantic 在运行时解析）\n- **为什么推荐 dataclass？**（答：减少样板代码、默认生成常用方法、可读性高，适合建模纯数据对象）" },
      { id: 'py-c1-s3', title: 'asyncio 异步模型', direction: '理解事件循环、协程与 await，能编写高并发 IO 程序。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\nasyncio 像**一个单线程里的“超级服务员”**：他在事件循环（event loop）这台旋转餐台上不断转圈，遇到 `await` 的“等菜”操作（网络 IO）就把当前客人暂时放下、去服务别人，菜好了再回来继续。单线程并发靠“不阻塞地切换”实现高吞吐——适合大量 IO 等待，而非 CPU 密集计算。\n\n## 核心知识点（锚定官方）\n\n- **协程与 await**：`async def` 定义协程，`await` 挂起等待可等待对象（coroutine/Task/Future）。[asyncio 文档](https://docs.python.org/3/library/asyncio.html)\n- **事件循环**：`asyncio.run(main())` 创建并运行循环直到完成；`asyncio.create_task(coro)` 并发调度协程。\n- **`asyncio.gather`**：`await asyncio.gather(a(), b())` 并发运行多个协程并收集结果。\n- **与同步库混用**：阻塞调用（如 `requests.get`）会卡住整个循环，IO 场景应换 `aiohttp`/`httpx.AsyncClient` 等异步库。\n\n## 常见坑\n\n- **在协程里调同步阻塞函数**：`time.sleep`/`requests` 阻塞事件循环，应 `await asyncio.sleep` 或用线程池 `loop.run_in_executor`。\n- **忘了 `await`**：`asyncio.create_task(coro)` 后若从未 `await`，任务可能不执行或被取消。\n- **循环已关闭再 run**：`asyncio.run` 不能嵌套，重复调用报“事件循环已关闭”。\n\n## 动手自测\n\n```python\nimport asyncio\nasync def fetch(n):\n    await asyncio.sleep(1)\n    return n\nasync def main():\n    res = await asyncio.gather(fetch(1), fetch(2))\n    print(res)  # [1, 2]\nasyncio.run(main())\n```\n\n## 面试视角\n\n- **协程为什么比线程轻？**（答：协程在单线程内由 runtime 调度，无上下文切换与锁开销，适合 IO 密集；CPU 密集仍需多进程）\n- **`await` 到底做了什么？**（答：挂起当前协程，把控制权交还事件循环去跑别的任务，IO 完成后恢复）" },
      { id: 'py-c1-s4', title: '项目结构与模块组织', direction: '用包/模块组织代码，理解导入机制与循环依赖规避。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nPython 的包（目录 + `__init__.py`）像**带门牌号的抽屉柜**，模块（`.py` 文件）是抽屉。导入（`import`）就是“按门牌号取抽屉里的工具”。`__init__.py` 决定这个柜子对外暴露什么（可放公开 API）。循环依赖（A 导入 B、B 又导入 A）像**两个抽屉互相锁死**，需在函数内延迟导入或抽出公共模块打破。\n\n## 核心知识点（锚定官方）\n\n- **包与 `__init__.py`**：目录含 `__init__.py` 即为包；可在此聚合公开接口。[导入系统](https://docs.python.org/3/reference/import.html)\n- **绝对 vs 相对导入**：`from mypkg.sub import x`（绝对）清晰；`from .sub import x`（相对，仅包内）避免硬编码。[相对导入](https://docs.python.org/3/reference/import.html#package-relative-imports)\n- **`if __name__ == '__main__'`**：模块被直接运行 vs 被导入时分支处理，避免导入即触发副作用。\n- **循环依赖**：把共享类型抽到第三模块，或在函数体内局部 `import` 延迟解析。\n\n## 常见坑\n\n- **相对导入在脚本直接运行报错**：`python app.py` 直接跑含相对导入的包会报 `ImportError: attempted relative import with no known parent package`，应以模块方式运行（`python -m app`）。\n- **同名遮蔽**：本地文件命名与标准库冲突（如 `email.py`）导致导入错库。\n- **`__init__.py` 重活**：在其中 import 过多子模块拖慢导入，应延迟到使用处。\n\n## 动手自测\n\n```\n# 推荐的服务项目结构\n# myapi/\n#   main.py        # 入口\n#   app/\n#     __init__.py\n#     routes.py    # 路由\n#     models.py    # 数据模型\n#     deps.py      # 依赖（抽公共以破循环）\n```\n\n## 面试视角\n\n- **绝对导入与相对导入怎么选？**（答：库代码优先相对导入减少重构成本；应用入口用绝对导入更清晰）\n- **如何破除循环依赖？**（答：抽公共依赖到独立模块、改为函数内局部导入、或用依赖注入反转方向）" }
    ]
  },
  {
    id: 'py-c2', subtrack: 'python', position: 102,
    title: 'FastAPI Web 框架核心',
    goal: '用 FastAPI 构建类型安全的异步 API，掌握路由、依赖注入、Pydantic 校验与中间件。',
    sections: [
      { id: 'py-c2-s1', title: '路由与请求处理', direction: '用 FastAPI 定义路径/查询参数与请求体，返回 JSON 响应。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nFastAPI 把“函数签名”当成**接口契约**：你在 `def read(id: int, q: str = None)` 上标好参数类型，框架自动从路径/查询里取值、做类型转换与校验，还能据此生成 OpenAPI 文档与交互式 Swagger UI。类型标注在这里**不再是建议，而是运行时的验收规则**。\n\n## 核心知识点（锚定官方）\n\n- **快速起步**：`app = FastAPI()`；`@app.get(\"/items/{item_id}\")` 定义路由；`uvicorn main:app --reload` 运行。[FastAPI 第一教程](https://fastapi.tiangolo.com/tutorial/first-steps/)\n- **路径与查询参数**：路径参数 `item_id: int` 自动转换；查询参数 `q: str = None` 可选；`required: bool` 必填。[路径参数](https://fastapi.tiangolo.com/tutorial/path-params/)\n- **请求体**：定义 `class Item(BaseModel)`，handler 参数声明 `item: Item`，FastAPI 自动解析 JSON 并校验。[请求体](https://fastapi.tiangolo.com/tutorial/body/)\n- **自动文档**：访问 `/docs`（Swagger UI）与 `/redoc` 自动生成交互式 API 文档，无需手写。\n\n## 常见坑\n\n- **查询参数被误当路径**：`/items/{id}` 只取路径，额外参数需作为函数普通参数（自动归为 query）。\n- **Pydantic 模型字段名与 JSON 不一致**：用 `Field(alias=...)` + `populate_by_name` 处理前端不同命名。\n- **`None` 默认值陷阱**：`q: str = None` 与 `q: Optional[str] = None` 行为不同（后者类型更严谨），建议显式 `Optional`。\n\n## 动手自测\n\n```python\nfrom fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI()\nclass Item(BaseModel):\n    name: str\n    price: float\n\n@app.get(\"/items/{item_id}\")\ndef read(item_id: int, q: str = None):\n    return {\"item_id\": item_id, \"q\": q}\n\n@app.post(\"/items\")\ndef create(item: Item):\n    return item\n# uvicorn main:app --reload\n```\n\n## 面试视角\n\n- **FastAPI 为什么快且类型安全？**（答：基于 Starlette 异步 + Pydantic 数据校验，类型标注驱动自动校验与文档生成）\n- **路径参数与查询参数的区别？**（答：路径参数在 URL 路径中必填且参与路由匹配；查询参数在 `?` 后，可选、不参与匹配）" },
      { id: 'py-c2-s2', title: '依赖注入系统', direction: '用 Depends 复用鉴权/数据库连接等逻辑，理解可组合依赖。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\n依赖注入（DI）像**乐高卡扣**：你声明“这个接口需要先拿到当前用户（`Depends(get_current_user)`）”，框架在调用前自动把依赖组装好、像扣上卡扣一样传进来。依赖还能**嵌套依赖**（获取 DB 连接 → 基于连接获取用户），框架递归解析整张依赖图，复用与测试都更轻松。\n\n## 核心知识点（锚定官方）\n\n- **`Depends` 基础**：`def get_db(): ...; @app.get('/x') def h(db = Depends(get_db))` 自动调用并注入。[依赖注入](https://fastapi.tiangolo.com/tutorial/dependencies/)\n- **类作为依赖**：依赖可是一个类，`Depends(Class)` 会被实例化并注入，常用于共享配置/状态。\n- **子依赖**：`get_current_user(db: Session = Depends(get_db))`——依赖本身也能声明依赖，框架递归解析。\n- **`Security` 与 `OAuth2`**：`fastapi.security` 提供 `OAuth2PasswordBearer` 等，与 `Depends` 结合做鉴权。[安全教程](https://fastapi.tiangolo.com/tutorial/security/)\n\n## 常见坑\n\n- **依赖里做重活**：依赖每次请求都执行，放 DB 连接池获取没问题，但放昂贵计算要缓存（`lru_cache`/请求级缓存）。\n- **循环依赖**：A 依赖 B、B 依赖 A 会栈溢出，应抽公共依赖或改用参数传递。\n- **`yield` 依赖的资源释放**：用 `yield` 的依赖（如 DB session）需在 `try/finally` 或 `finally` 后关闭，异常时也能回收。\n\n## 动手自测\n\n```python\nfrom fastapi import Depends\n\ndef get_token(x_token: str = Header(None)):\n    if not x_token: raise HTTPException(401)\n    return x_token\n\n@app.get(\"/me\")\ndef me(tok: str = Depends(get_token)):\n    return {\"token\": tok}\n```\n\n## 面试视角\n\n- **依赖注入解决了什么问题？**（答：解耦依赖创建与使用，提升复用、可测试性与可读性）\n- **`Depends` 与普通函数调用的区别？**（答：`Depends` 由框架在请求生命周期内解析、可嵌套、可共享，且参与 OpenAPI 描述）" },
      { id: 'py-c2-s3', title: 'Pydantic 数据校验', direction: '用 Pydantic 模型做请求/响应校验与序列化，理解字段约束。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nPydantic 像**带门禁的转换器**：你定义 `class User(BaseModel)`，它就在“原始 JSON”进门时做类型转换（字符串→整数）、按 `Field` 规则验收（长度/范围/正则），不合格直接拦在门外（抛出清晰错误）。出门时（响应）再把 Python 对象序列化为 JSON。数据进出门都有人管。\n\n## 核心知识点（锚定官方）\n\n- **模型定义**：`class Item(BaseModel): name: str; price: float = Field(gt=0)`。[Pydantic 文档](https://docs.pydantic.dev/latest/)\n- **字段约束**：`Field(gt=0, le=100, max_length=50, pattern=r'^\\w+$')` 表达数值/长度/正则规则。\n- **嵌套与列表**：模型字段可为另一模型或 `List[SubModel]`，自动递归校验。\n- **`ConfigDict`**：`model_config = ConfigDict(from_attributes=True)` 支持从 ORM 对象加载（响应模型常用）。\n\n## 常见坑\n\n- **`gt=0` 与 `ge=0` 混淆**：价格用 `gt=0`（不含 0），数量用 `ge=0`（含 0），语义不同。\n- **datetime 解析**：ISO8601 字符串自动转 `datetime`，但时区缺失会按 naive 处理，跨时区需显式 `tzinfo`。\n- **`None` 与 `Optional`**：必填字段不可给 `None`，需显式 `Optional[X] = None`。\n\n## 动手自测\n\n```python\nfrom pydantic import BaseModel, Field\nclass Item(BaseModel):\n    name: str = Field(max_length=50)\n    price: float = Field(gt=0)\n# Item(name=\"a\", price=9.9) -> ok\n# Item(name=\"a\", price=-1) -> ValidationError\n```\n\n## 面试视角\n\n- **Pydantic v1 与 v2 的主要差异？**（答：v2 用 Rust 核心提速、校验 API 调整、`ConfigDict` 取代 `Config` 内部类，迁移需注意 `parse_obj` 等弃用）\n- **为什么用 Pydantic 而非手写校验？**（答：声明式、自动类型转换、错误清晰、与 FastAPI 深度集成生成文档）" },
      { id: 'py-c2-s4', title: '中间件与异常处理', direction: '用中间件做跨切面逻辑，统一异常响应与 CORS。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\n中间件是**横在请求路上的安检门**：每个请求进出都要过这道门——进来时记日志/校验，出去时加 CORS 头/统一错误体。FastAPI 基于 ASGI，中间件是异步的（`async def`），与 Starlette 的 `BaseHTTPMiddleware` 一致。异常处理则把“散落的 try/except”集中成**统一急诊室**：某类异常（如 `ItemNotFound`）全局捕获并转成标准错误响应。\n\n## 核心知识点（锚定官方）\n\n- **自定义中间件**：`@app.middleware(\"http\")` + `async def mw(request, call_next): resp = await call_next(request); return resp`。[中间件](https://fastapi.tiangolo.com/tutorial/middleware/)\n- **CORS**：`from fastapi.middleware.cors import CORSMiddleware; app.add_middleware(CORSMiddleware, allow_origins=[...])` 配置跨域。[CORS 文档](https://fastapi.tiangolo.com/tutorial/cors/)\n- **异常处理器**：`@app.exception_handler(ItemNotFound) def h(req, exc): return JSONResponse(status_code=404, content={...})` 统一响应。[异常处理](https://fastapi.tiangolo.com/tutorial/handling-errors/)\n- **统一响应**：结合 Pydantic 响应模型 `response_model=Resp` 保证出参结构一致。\n\n## 常见坑\n\n- **中间件是异步的**：在里面用同步阻塞调用会卡事件循环，需 `run_in_executor` 或异步库。\n- **CORS 配置过宽**：`allow_origins=['*']` 配合 `allow_credentials=True` 在浏览器被禁，生产应白名单具体域名。\n- **异常处理器与响应模型冲突**：异常返回的字段若未走 `response_model`，需直接返回 `JSONResponse` 绕开校验。\n\n## 动手自测\n\n```python\nfrom fastapi.middleware.cors import CORSMiddleware\napp.add_middleware(CORSMiddleware,\n    allow_origins=[\"https://app.example.com\"],\n    allow_methods=[\"*\"], allow_headers=[\"*\"])\n@app.exception_handler(ValueError)\ndef ve_handler(request, exc):\n    return JSONResponse(400, {\"msg\": str(exc)})\n```\n\n## 面试视角\n\n- **FastAPI 中间件与依赖注入的分工？**（答：中间件处理全局横切（日志/CORS/错误包装），依赖注入处理请求内的可组合逻辑（鉴权/DB），职责不同）\n- **为什么 CORS 不能 `*` + credentials？**（答：浏览器安全策略禁止“任意源 + 带凭证”，需显式列出受信源）" }
    ]
  },
  {
    id: 'go-c3', subtrack: 'go', position: 103,
    title: 'Go 并发实战与模式',
    goal: '掌握 context 取消传播、sync 同步原语与常见并发模式，能编写正确且高效的生产级并发代码。',
    sections: [
      { id: 'go-c3-s1', title: 'Context 与取消传播', direction: '用 context 在请求生命周期内传递截止时间、取消信号与值。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n`context.Context` 像**一根贯穿调用链的“取消导线”**：最顶层（如 HTTP handler）按下开关（超时/手动取消），这根导线会把“别干了”的信号一路传到最底层的数据库查询、RPC 调用。谁拿着这根导线，谁就能在任务被放弃时及时收手，释放资源。\n\n## 核心知识点（锚定官方）\n\n- **创建与派生**：`ctx, cancel := context.WithCancel(parent)` 手动取消；`context.WithTimeout(parent, d)` / `WithDeadline` 超时取消；`defer cancel()` 防止泄漏。[Context 包](https://pkg.go.dev/context)\n- **传递而非存储**：Context 作为函数第一个参数 `ctx` 显式传递，不要存进结构体；不要传 `nil`，用 `context.Background()` / `context.TODO()` 起头。[Context 使用规范](https://go.dev/blog/context-values)\n- **取值与携带**：`ctx.Value(key)` 传递请求域值（如 traceID），key 应用自定义类型避免冲突。\n- **与标准库协作**：`net/http`、`database/sql`、`os/exec` 等都接受 ctx 参数以响应取消。\n\n## 常见坑\n\n- **忘记 defer cancel()**：`WithCancel/WithTimeout` 返回的 cancel 必须调用，否则定时器/goroutine 泄漏。\n- **用 Value 传可选参数**：Value 仅用于请求域元数据，业务参数应显式传参，否则隐式难追踪。\n- **派生链断裂**：中间层吞掉 ctx 改用 `context.Background()`，取消信号传不到底。\n\n## 动手自测\n\n```go\nfunc handler(w http.ResponseWriter, r *http.Request) {\n    ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)\n    defer cancel()\n    rows, err := db.QueryContext(ctx, \"SELECT ...\")\n    _ = rows; _ = err\n}\n```\n\n## 面试视角\n\n- **为什么 Context 能取消底层 IO？**（答：标准库在阻塞调用前 select 监听 `ctx.Done()` 通道，收到关闭即返回 `context.Canceled`）\n- **Context.Value 的 key 为什么要用自定义类型？**（答：避免不同包用相同字符串 key 互相覆盖，类型安全且私有防止外部篡改）" },
      { id: 'go-c3-s2', title: 'sync 同步原语', direction: '理解 Mutex/RWMutex、WaitGroup、Once、原子操作与对象池的适用场景。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\nsync 包是**并发安全的工具箱**：`Mutex` 是“单人洗手间”锁（一次只进一个）；`RWMutex` 是“读写分离阅览室”（多读可并发、写独占）；`WaitGroup` 是“婚礼签到墙”（等所有人到齐再开席）；`Once` 是“只点一次火”；`atomic` 是“无锁计数器”（对单个整数/指针的原子读写）。选哪个取决于**读多写少 / 一次性 / 单变量**等场景。\n\n## 核心知识点（锚定官方）\n\n- **Mutex/RWMutex**：`mu.Lock()/Unlock()` 保护临界区；`RWMutex.RLock()` 允许多读并发，写时独占。[sync 包](https://pkg.go.dev/sync)\n- **WaitGroup**：`wg.Add(n)`、`wg.Done()`、`wg.Wait()` 等待一组 goroutine；`Add` 必须在 `go` 前调用避免竞态。[WaitGroup](https://pkg.go.dev/sync#WaitGroup)\n- **Once**：`once.Do(f)` 保证 f 仅执行一次，常用于单例/懒初始化。[Once](https://pkg.go.dev/sync#Once)\n- **原子操作**：`atomic.AddInt64`、`atomic.Load/Store` 对单一变量无锁安全；并发热点计数器首选，避免锁开销。[atomic 包](https://pkg.go.dev/sync/atomic)\n- **Pool**：`sync.Pool` 复用临时对象，缓解 GC 压力（如 bytes.Buffer 缓冲池）。[Pool](https://pkg.go.dev/sync#Pool)\n\n## 常见坑\n\n- **Copy 含锁结构体**：含 `sync.Mutex` 的结构体被值拷贝会导致锁失效，应传指针。\n- **WaitGroup 计数变负**：`Add` 传负值或 `Done` 多调用会 panic。\n- **RWMutex 写饥饿**：大量读请求持续占用，写可能长时间拿不到锁，需评估读写比。\n\n## 动手自测\n\n```go\ntype Counter struct{ mu sync.RWMutex; n int }\nfunc (c *Counter) Inc() { c.mu.Lock(); defer c.mu.Unlock(); c.n++ }\nfunc (c *Counter) Get() int { c.mu.RLock(); defer c.mu.RUnlock(); return c.n }\n```\n\n## 面试视角\n\n- **RWMutex 与 Mutex 怎么选？**（答：读远多于写且读操作耗时、不修改状态时用 RWMutex 提升并发；写频繁则 Mutex 更简单）\n- **什么场景用 atomic 而不是 Mutex？**（答：仅对单一整型/指针的读改写、无复合临界区时，atomic 开销更低且无死锁风险）" },
      { id: 'go-c3-s3', title: '并发模式', direction: '掌握 Worker Pool、Fan-out/Fan-in、errgroup 等可复用并发模式。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\n并发模式是把“多工人协作”抽象成可复用的蓝图：**Worker Pool** 是“固定工位的流水线”（用带缓冲 channel 当任务队列，N 个工人从队列取活）；**Fan-out/Fan-in** 是“一摊活分给多人做、再把结果汇回一处”；**errgroup** 是“小组作业”——任一人出错全组即停，并统一等待。\n\n## 核心知识点（锚定官方）\n\n- **Worker Pool**：`tasks := make(chan Job, N)`；起 `k` 个 `go worker(tasks, results)`；主协程派发任务后 `close(tasks)`。[Go 并发模式](https://go.dev/blog/pipelines)\n- **Fan-out/Fan-in**：多个 goroutine 消费同一 channel（fan-out），再用一个 goroutine 合并结果（fan-in）。\n- **errgroup**：`g, ctx := errgroup.WithContext(ctx)`；`g.Go(func() error {...})`；`g.Wait()` 等全部完成并返回首个错误，任一失败 `ctx` 取消其余。[errgroup](https://pkg.go.dev/golang.org/x/sync/errgroup)\n- **select + default**：非阻塞收发、超时控制（`case <-time.After(d):`）。\n\n## 常见坑\n\n- **channel 未关闭导致 range 卡死**：fan-in 合并前需 `close`，否则 `for v := range ch` 永久阻塞。\n- **worker 数过多反而变慢**：超过 CPU/IO 瓶颈后，调度与上下文切换开销抵消收益。\n- **errgroup 吞掉非首错**：`Wait` 只返回第一个错误，需自行收集全部（如用独立 error channel）。\n\n## 动手自测\n\n```go\njobs := make(chan int, 10)\nfor w := 0; w < 3; w++ {\n    go func() { for j := range jobs { fmt.Println(j) } }()\n}\nfor i := 0; i < 10; i++ { jobs <- i }\nclose(jobs)\ntime.Sleep(time.Millisecond) // 真实场景用 WaitGroup/errgroup 等待\n```\n\n## 面试视角\n\n- **errgroup 相比 WaitGroup 的优势？**（答：自动传播取消、统一返回首个错误、避免半完成状态，代码更简洁）\n- **如何优雅限制并发数？**（答：带缓冲 channel 作信号量，或固定 worker 数的 pool，而非无限 `go`）" },
      { id: 'go-c3-s4', title: '并发安全与竞态检测', direction: '理解 data race 成因，会用 -race 检测并选择合适的同步策略。',
        content: "> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方\n\n## 心智模型\n\ndata race 是**两个工人同时改同一张表、且无人加锁**，最终结果取决于谁先谁后——不确定且难复现。`go build -race` 是“监控探头”，在运行时记录每次内存访问的 happens-before 关系，发现竞争即报警。通道 vs 锁的选择好比“传纸条（channel）还是轮流用笔（锁）”——Go 哲学倾向前者，但热点计数等场景锁更直白。\n\n## 核心知识点（锚定官方）\n\n- **竞态条件**：对共享变量无同步的并发读写，行为未定义。[Go 内存模型](https://go.dev/ref/mem)\n- **-race 检测器**：`go test -race` / `go run -race` 启用，CI 中必开，开销约 2-10 倍但能抓隐蔽 bug。[Race 检测器](https://go.dev/doc/articles/race_detector)\n- **channel 所有权**：通过 channel 传递数据所有权（发方不再持有），避免共享，符合“不要通过共享内存通信”。\n- **互斥 vs 原子**：复合操作（如“读-改-写”多字段）必须用锁；单字段可用 atomic。\n\n## 常见坑\n\n- **map 并发读写 panic**：Go 原生 map 非并发安全，并发需 `sync.RWMutex` 或 `sync.Map`。\n- **仅保护部分字段**：临界区漏掉某个共享字段，仍会 race。\n- **依赖 sleep 掩盖竞态**：测试里 `time.Sleep` 降低了 race 触发概率而非消除，必须用 `-race` 验证。\n\n## 动手自测\n\n```go\n// 错误：并发写同一变量\nvar n int\nfor i := 0; i < 100; i++ { go func() { n++ }() } // race\n// 正确\nvar mu sync.Mutex\nfor i := 0; i < 100; i++ { go func() { mu.Lock(); n++; mu.Unlock() }() }\n```\n\n## 面试视角\n\n- **Go 的 map 为什么并发不安全？**（答：map 在扩容/桶搬迁时结构会变，并发写可能读到半更新状态甚至崩溃，需外部同步）\n- **-race 的原理简述？**（答：插桩记录每次访问的 goroutine 与锁/通道同步的边，构建 happens-before 图，发现无同步的并发访问对即报 race）" }
    ]
  },
  {
    id: 'go-c4', subtrack: 'go', position: 104,
    title: 'GORM 数据库访问',
    goal: '用 GORM 完成数据库连接、模型定义、CRUD 与事务，掌握生产可用的数据访问层写法。',
    sections: [
      { id: 'go-c4-s1', title: '连接与连接池', direction: '配置 GORM 与底层数据库驱动，调优连接池参数。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\nGORM 是**盖在 `database/sql` 之上的“对象搬运工”**：你给它一个 Go 结构体，它自动生成 SQL、把行映射成对象、把对象写回表。底层的真正连接池由 `database/sql` 管理——`SetMaxOpenConns` 是“最多同时开几个水龙头”，`SetMaxIdleConns` 是“空闲时留几个备用”，`SetConnMaxLifetime` 是“水龙头用多久就换”，三者决定高并发下的稳定性。\n\n## 核心知识点（锚定官方）\n\n- **打开连接**：`db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})`；`sqlDB, _ := db.DB()` 取出底层池调整参数。[GORM 连接](https://gorm.io/docs/connecting_to_the_database.html)\n- **连接池**：`sqlDB.SetMaxOpenConns(100)`、`SetMaxIdleConns(10)`、`SetConnMaxLifetime(time.Hour)` 防止云数据库踢掉长连接。[数据库/SQL 池](https://pkg.go.dev/database/sql)\n- **多数据库**：`db.Use()` 或为不同库开多个 `*gorm.DB` 实例。\n- **驱动**：MySQL 用 `gorm.io/driver/mysql`、Postgres 用 `gorm.io/driver/postgres`。\n\n## 常见坑\n\n- **连接池过小导致排队**：默认 `SetMaxOpenConns(0)` 不限，但某些驱动默认低；高并发需显式调大。\n- **ConnMaxLifetime 超过数据库 wait_timeout**：连接被服务端关闭后客户端仍用，报 `invalid connection`，应设小于服务端超时。\n- **defer db.Close() 缺失**：进程退出时连接未释放，长驻服务需在关闭钩子里关闭。\n\n## 动手自测\n\n```go\ndsn := \"user:pass@tcp(127.0.0.1:3306)/db?charset=utf8mb4&parseTime=True\"\ndb, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})\nsqlDB, _ := db.DB()\nsqlDB.SetMaxOpenConns(50)\nsqlDB.SetConnMaxLifetime(time.Hour)\n```\n\n## 面试视角\n\n- **为什么需要连接池？**（答：每次建连开销大且数据库有连接上限，池复用连接、削峰填谷）\n- **ConnMaxLifetime 设多大合适？**（答：小于数据库服务端空闲超时，通常 30m-1h，避免用到已被回收的连接）" },
      { id: 'go-c4-s2', title: '模型定义与自动迁移', direction: '用结构体标签声明表结构，理解 GORM 约定与迁移。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nGORM 模型是**“结构即表”的映射清单**：结构体字段用 `gorm:\"column:..;type:..;primaryKey\"` 这样的标签告诉搬运工“这一栏叫什么、什么类型、是不是主键”。`AutoMigrate` 则像“按清单自动补建仓库货架”——缺表建表、缺列加列（但**不删列、不改类型**，避免误删数据）。\n\n## 核心知识点（锚定官方）\n\n- **模型标签**：`gorm:\"primaryKey\"`、`column:name`、`type:varchar(100)`、`not null`、`default:0`；`autoIncrement`。[模型定义](https://gorm.io/docs/models.html)\n- **约定**：表名默认结构体复数蛇形（`User`→`users`），可用 `TableName()` 自定义；字段 `ID` 默认主键。\n- **自动迁移**：`db.AutoMigrate(&User{}, &Order{})` 创建/更新表结构，生产应评估与迁移工具（如 golang-migrate）的配合。[迁移](https://gorm.io/docs/migration.html)\n- **嵌入**：`gorm.Model` 提供 `ID/CreatedAt/UpdatedAt/DeletedAt`（软删除）。\n\n## 常见坑\n\n- **自动迁移误删风险**：`AutoMigrate` 不会删列，但结构大幅变更时仍建议用版本化迁移工具而非依赖它。\n- **软删除陷阱**：含 `DeletedAt` 的模型查询默认带 `WHERE deleted_at IS NULL`，误以为“查不到”其实是被软删。\n- **字段名约定冲突**：未显式 `column` 时 GORM 按蛇形推断，与已有表列名不符会映射错。\n\n## 动手自测\n\n```go\ntype User struct {\n    gorm.Model\n    Name  string `gorm:\"size:100;not null\"`\n    Email string `gorm:\"uniqueIndex;size:191\"`\n}\ndb.AutoMigrate(&User{})\n```\n\n## 面试视角\n\n- **AutoMigrate 适合生产直接跑吗？**（答：开发可用，生产建议用 golang-migrate 等做版本化、可回滚迁移，AutoMigrate 仅补齐不删改）\n- **GORM 软删除怎么实现的？**（答：模型含 `DeletedAt` 时，删除改时间戳，查询自动加 `deleted_at IS NULL` 过滤）" },
      { id: 'go-c4-s3', title: 'CRUD 与查询', direction: '掌握 Create/Read/Update/Delete 与链式查询、预加载。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nCRUD 就是**搬运工的四个动作**：`Create`（入库）、`First/Find`（取货）、`Save/Updates`（改标签）、`Delete`（下架）。查询条件像“在货架上贴筛选贴纸”——`Where(\"age > ?\", 18)` 是手写贴纸，`db.Where(&User{Name:\"a\"})` 是“按样本比对”的贴纸。关联数据用 `Preload` 提前一并搬来，避免 N+1 多次往返。\n\n## 核心知识点（锚定官方）\n\n- **创建**：`db.Create(&user)`；批量 `db.Create(&users)`。[CRUD](https://gorm.io/docs/create.html)\n- **读取**：`db.First(&u, 1)`（主键）、`db.Where(\"name = ?\", \"a\").Find(&us)`；`Select` 指定列。[查询](https://gorm.io/docs/query.html)\n- **更新**：`db.Model(&u).Updates(User{Name:\"x\"})` 零值字段会被忽略，需用 `Select` 或 `map` 显式更新。[更新](https://gorm.io/docs/update.html)\n- **删除**：`db.Delete(&u, 1)`；软删除模型打时间戳。[删除](https://gorm.io/docs/delete.html)\n- **预加载**：`db.Preload(\"Orders\").Find(&users)` 一次性加载关联，规避 N+1。[预加载](https://gorm.io/docs/preload.html)\n\n## 常见坑\n\n- **Updates 零值不生效**：`Updates(User{Age:0})` 中 0 被当作“未设”跳过，须 `Select(\"Age\")` 或传 `map[string]interface{}`。\n- **First 查不到返回 ErrRecordNotFound**：需 `errors.Is(err, gorm.ErrRecordNotFound)` 区分“真错误”与“无记录”。\n- **N+1 查询**：循环里逐条 `Preload` 关联会爆量 SQL，应一次性 `Preload`。\n\n## 动手自测\n\n```go\nvar u User\ndb.Preload(\"Orders\").Where(\"age >= ?\", 18).Find(&u)\ndb.Model(&u).Select(\"Age\").Updates(map[string]interface{}{\"Age\": 0})\n```\n\n## 面试视角\n\n- **GORM 怎么避免 N+1？**（答：用 `Preload` / `Joins` 一次性加载关联，避免循环内逐条查询）\n- **Updates 为什么跳过零值，怎么解决？**（答：GORM 用 struct 时忽略零值，需用 `Select` 列出字段或传 `map` 明确更新）" },
      { id: 'go-c4-s4', title: '事务与关联', direction: '理解事务边界、关联定义与级联约束。',
        content: "> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方\n\n## 心智模型\n\n事务是**“要么全成、要么全退”的原子包裹**：转账时“扣 A + 加 B”必须在一个包裹里，中途崩了就整体回滚，绝不允许只扣不加。Go 里用闭包 `db.Transaction(func(tx *gorm.DB) error {...})` 表达——返回 `nil` 提交、返回 `error` 自动回滚。关联（`Has One`/`Has Many`/`Many2Many`）则像“货架间的连接标签”，告诉搬运工两张表怎么对上。\n\n## 核心知识点（锚定官方）\n\n- **事务**：`db.Transaction(func(tx *gorm.DB) error { ...; return nil })`；手动 `tx.Begin()/Commit()/Rollback()`。[事务](https://gorm.io/docs/transactions.html)\n- **保存点**：`tx.SavePoint(\"sp1\")` / `RollbackTo(\"sp1\")` 部分回滚。\n- **关联定义**：`gorm:\"foreignKey:UserID\"`；`Has Many` / `Belongs To` / `Many2Many`。[关联](https://gorm.io/docs/associations.html)\n- **关联操作**：`tx.Preload(\"Orders\").Create(&u)` / `Association(\"Orders\").Append(...)` / `Clear()`。\n\n## 常见坑\n\n- **事务过长持锁**：事务内做网络调用会长时间持锁，拖垮并发，应只包必要 DB 操作。\n- **在事务里用 db 而非 tx**：必须用传入的 `tx`，否则操作在事务外、不受回滚保护。\n- **嵌套事务误区**：GORM 嵌套 `Transaction` 默认禁用 savepoint（除非开启），外层回滚会带走内层。\n\n## 动手自测\n\n```go\nerr := db.Transaction(func(tx *gorm.DB) error {\n    if err := tx.Create(&order).Error; err != nil { return err }\n    if err := tx.Model(&acc).Update(\"balance\", gorm.Expr(\"balance - ?\", 100)).Error; err != nil { return err }\n    return nil\n})\n```\n\n## 面试视角\n\n- **事务里为什么不能做远程调用？**（答：会长时间持锁/占连接，增加死锁与超时风险，应把 DB 操作压缩到最小）\n- **GORM 关联 Many2Many 怎么落地？**（答：定义连接表，模型用 `gorm:\"many2many:user_roles\"` 标签，GORM 自动维护中间表）" }
    ]
  },
  {
    id: 'go-c5', subtrack: 'go', position: 105,
    title: 'Go Web 安全与认证',
    goal: '为 Gin 服务实现 JWT 认证、密码哈希与 CORS 防护，建立生产级安全基线。',
    sections: [
      { id: 'go-c5-s1', title: 'JWT 认证中间件', direction: '签发与校验 JWT，用 Gin 中间件保护路由。',
        content: "> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方\n\n## 心智模型\n\nJWT 是**“盖了章的通行证”**：登录成功后服务端用密钥在令牌上签名，之后客户端每次请求都带上它，服务端只用密钥验章、不必查库就能信任“这是谁”。中间件像“门卫”，在每个请求进门时验章，章有效才放进里屋（handler），并把解析出的用户塞进 `c.Set` 供后续使用。\n\n## 核心知识点（锚定官方）\n\n- **签发**：`token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{\"sub\": uid, \"exp\": time.Now().Add(time.Hour).Unix()})`；`signed, _ := token.SignedString([]byte(secret))`。[jwt 包](https://pkg.go.dev/github.com/golang-jwt/jwt/v5)\n- **校验**：`parse, err := jwt.Parse(tokenStr, func(t *jwt.Token) (interface{}, error) { return []byte(secret), nil })`；检查 `err == nil` 与 `token.Valid`。\n- **中间件保护**：`authMw` 取 `Authorization: Bearer <token>` 头，验签失败 `c.AbortWithStatusJSON(401, ...)`。\n- **claims 取值**：`claims[\"sub\"].(float64)` 取用户 ID（JSON 数字解析为 float64）。\n\n## 常见坑\n\n- **密钥硬编码/入库**：secret 必须走环境变量/密钥管理，严禁提交源码。\n- **不设过期或过长**：无 `exp` 的令牌永久有效，泄露即长期失陷；建议 15m-2h 并配刷新令牌。\n- **验签忽略 alg**：务必在 keyFunc 中校验 `t.Method.Alg()` 为预期算法，防止 `alg=none` 绕过签名攻击。\n\n## 动手自测\n\n```go\nfunc authMw(secret string) gin.HandlerFunc {\n  return func(c *gin.Context) {\n    h := c.GetHeader(\"Authorization\")\n    t := strings.TrimPrefix(h, \"Bearer \")\n    if _, err := jwt.Parse(t, func(tk *jwt.Token) (interface{}, error) {\n      if tk.Method.Alg() != jwt.SigningMethodHS256.Alg() { return nil, errors.New(\"bad alg\") }\n      return []byte(secret), nil\n    }); err != nil { c.AbortWithStatusJSON(401, gin.H{\"error\": \"unauthorized\"}); return }\n    c.Next()\n  }\n}\n```\n\n## 面试视角\n\n- **JWT 为什么需要刷新令牌？**（答：访问令牌短效降低泄露风险，刷新令牌长期但存服务端可吊销，平衡安全与体验）\n- **alg=none 攻击是什么？**（答：攻击者把 JWT 算法改为 none 绕过签名，服务端必须白名单校验算法）" },
      { id: 'go-c5-s2', title: '密码哈希与登录', direction: '用 bcrypt 做密码哈希与比对，避免明文存储。',
        content: "> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方\n\n## 心智模型\n\nbcrypt 是**“带盐的单向研磨机”**：同样的密码每次研磨得到的密文都不同（因为随机加盐），且故意磨得慢（cost 因子）让暴力破解成本极高。验证时不“解密”（哈希不可逆），而是把输入的密码用同一盐再磨一遍，比对两杯粉末是否一致。绝不要存明文密码——那等于把保险柜钥匙贴在门上。\n\n## 核心知识点（锚定官方）\n\n- **生成哈希**：`hash, err := bcrypt.GenerateFromPassword([]byte(pwd), bcrypt.DefaultCost)`。[bcrypt 包](https://pkg.go.dev/golang.org/x/crypto/bcrypt)\n- **比对**：`err := bcrypt.CompareHashAndPassword(hash, []byte(input))`；`err == nil` 表示匹配。\n- **cost 因子**：默认 10-12；越高越慢越安全，但登录延迟增大，需按机器性能权衡。\n- **迁移升级**：旧哈希 cost 过低时，登录成功后可重新以更高 cost 哈希存储。\n\n## 常见坑\n\n- **明文比较 ==**：用 `pwd == stored` 比较密码是严重漏洞，必须哈希后 `CompareHashAndPassword`。\n- **哈希当唯一标识**：bcrypt 每次结果不同，不能用哈希值做幂等 key。\n- **cost 过高拖垮登录**：生产需压测定价，避免登录接口成为瓶颈。\n\n## 动手自测\n\n```go\nhash, _ := bcrypt.GenerateFromPassword([]byte(\"secret\"), bcrypt.DefaultCost)\n// 存储 hash...\nif err := bcrypt.CompareHashAndPassword(hash, []byte(input)); err != nil {\n    c.JSON(401, gin.H{\"error\": \"bad credentials\"}); return\n}\n```\n\n## 面试视角\n\n- **为什么不能自己写哈希（如 md5+盐）？**（答：md5/sha 太快易被 GPU 暴力破解，bcrypt/scrypt/argon2 专为密码设计、可调慢因子）\n- **bcrypt 为什么不可逆？**（答：基于 Blowfish 的单向哈希，设计上无法从密文还原明文，验证靠重算比对）" },
      { id: 'go-c5-s3', title: 'CORS 与基础防护', direction: '理解跨域机制，配置安全的 CORS 与基础头防护。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\nCORS 是**浏览器设的“跨店限购”规则**：前端 A 店要向 B 店要数据，浏览器先替 B 店问“你允许 A 店来拿吗？”——B 店在响应头（`Access-Control-Allow-Origin`）写明允许的源。复杂请求（带自定义头/非简单方法）浏览器还会先发一个 `OPTIONS` “预检”探路。配置过宽等于把店门对所有人敞开。\n\n## 核心知识点（锚定官方）\n\n- **Gin CORS 中间件**：`cors.New(cors.Config{AllowOrigins: []string{\"https://app.example.com\"}, AllowMethods: []string{\"GET\",\"POST\"}, AllowHeaders: []string{\"Authorization\"}})`。[gin-contrib/cors](https://github.com/gin-contrib/cors)\n- **预检 OPTIONS**：复杂请求浏览器先 `OPTIONS`，中间件需正确响应 `204` 与 Allow 头。\n- **凭证模式**：带 cookie/`Authorization` 时前端须 `withCredentials`，服务端 `AllowCredentials=true` 且**不可** `AllowOrigins=*`。\n- **基础头**：生产加 `X-Content-Type-Options: nosniff`、`X-Frame-Options` 等降低注入/点击劫持风险。\n\n## 常见坑\n\n- **`*` + credentials 被禁**：浏览器拒绝“任意源 + 带凭证”组合，必须显式列出受信源。\n- **AllowOrigins 含尾斜杠/协议不符**：`http://a.com/` 与请求源 `http://a.com` 不匹配，需精确。\n- **预检被业务中间件拦截**：`OPTIONS` 请求在到达 CORS 前被鉴权中间件 `Abort`，需让 OPTIONS 跳过鉴权。\n\n## 动手自测\n\n```go\nr.Use(cors.New(cors.Config{\n  AllowOrigins: []string{\"https://app.example.com\"},\n  AllowMethods: []string{\"GET\", \"POST\", \"PUT\", \"DELETE\"},\n  AllowHeaders: []string{\"Origin\", \"Content-Type\", \"Authorization\"},\n}))\n```\n\n## 面试视角\n\n- **简单请求与预检请求的区别？**（答：简单请求（GET/HEAD/POST + 有限头）直接发；带自定义头或非简单方法先发 OPTIONS 预检）\n- **为什么 CORS 不能防 CSRF？**（答：CORS 管浏览器跨域读响应，CSRF 利用的是已认证会话自动带 cookie 发请求，需 CSRF Token/同站策略防护）" },
      { id: 'go-c5-s4', title: '限流与输入防护', direction: '为接口加限流与严格校验，抵御滥用与注入。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\n限流是**“门口的闸机”**：每个客户端（按 IP/用户）单位时间只放 N 个请求，超出直接拒之门外，保护后端不被刷爆。输入防护则是“收货验视”——所有外部数据（路径参数、JSON body、查询串）都按规则严格校验后再用，绝不让“带针管的包裹”进库（SQL 注入/XSS）。GORM 参数化查询与 Pydantic 式绑定天然阻断大部分注入。\n\n## 核心知识点（锚定官方）\n\n- **令牌桶限流**：用 `golang.org/x/time/rate` 的 `rate.Limiter` 在中间件里 `Allow()` 放行；或按 IP 用 `sync.Map` 计数滑动窗口。\n- **参数化查询**：GORM 默认用占位符 `?` 参数化，杜绝拼接 SQL；绝不用 `fmt.Sprintf` 拼 SQL 字符串。\n- **输入校验**：复用 `go-c2` 的 `binding` 标签，对长度/格式/范围做边界约束。\n- **错误脱敏**：对外只返回通用错误，底层 DB 报错记日志不回显，防信息泄露。\n\n## 常见坑\n\n- **按 IP 限流遇代理失效**：前置反向代理时客户端 IP 是代理 IP，需取 `X-Forwarded-For` / `X-Real-IP` 真实源（注意伪造）。\n- **限流只在单实例**：多副本部署时本地计数不共享，需用 Redis 等集中式限流。\n- **只验前端不验后端**：前端校验仅为体验，后端必须独立校验，否则被绕过。\n\n## 动手自测\n\n```go\nimport \"golang.org/x/time/rate\"\nvar limiter = rate.NewLimiter(rate.Every(time.Second), 5) // 每秒5个\nfunc rateLimit(c *gin.Context) {\n    if !limiter.Allow() { c.AbortWithStatusJSON(429, gin.H{\"error\": \"too many requests\"}); return }\n    c.Next()\n}\n```\n\n## 面试视角\n\n- **限流算法有哪些？各自的取舍？**（答：固定窗口简单但有临界突刺；滑动窗口平滑；令牌桶允许短时突发；漏桶恒定输出——按场景选）\n- **参数化查询为什么能防 SQL 注入？**（答：参数与 SQL 分开发送，数据库把参数当数据而非可执行代码，结构上杜绝拼接执行）" }
    ]
  },
  {
    id: 'py-c3', subtrack: 'python', position: 106,
    title: 'Python 并发实战',
    goal: '深入 asyncio 任务调度、异步 IO 与线程/进程并行，写出正确的高并发 Python 服务。',
    sections: [
      { id: 'py-c3-s1', title: 'asyncio 进阶：任务与超时', direction: '用 create_task / gather / wait_for 编排并发，处理取消与超时。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\n`asyncio.create_task` 是把协程**“贴上运行时刻表”**：它立刻开始调度，返回一个 `Task` 句柄，你可以之后 `await` 它拿结果。`gather` 是“发令枪”——同时起跑多个协程并等全部到终点；`wait_for` 是“加个秒表”——超时就吹哨取消。任务取消像“召回外勤”：发 `cancel()`，对方在下一个 `await` 处抛 `CancelledError` 收工。\n\n## 核心知识点（锚定官方）\n\n- **Task 调度**：`task = asyncio.create_task(coro())`；`await task` 取结果，未 await 的任务在事件循环结束前可能被取消。[asyncio 任务](https://docs.python.org/3/library/asyncio-task.html)\n- **并发收集**：`await asyncio.gather(a(), b(), return_exceptions=True)` 并发并收集异常而非中断。\n- **超时**：`await asyncio.wait_for(coro(), timeout=2)` 超时抛 `TimeoutError` 并取消内部任务。\n- **取消与屏蔽**：`task.cancel()`；`asyncio.shield()` 保护子任务不被外部取消。\n\n## 常见坑\n\n- **gather 一个异常全崩**：不传 `return_exceptions=True` 时任一协程抛错会取消其余并冒泡，需按场景决定。\n- **await 忘记导致任务未跑**：`create_task` 后从不 await/事件循环关闭，任务可能被丢弃。\n- **屏蔽取消误用**：`shield` 内任务仍可被自身 cancel 取消，只是外层取消传不进去。\n\n## 动手自测\n\n```python\nimport asyncio\nasync def main():\n    t1 = asyncio.create_task(fetch(1))\n    t2 = asyncio.create_task(fetch(2))\n    try:\n        r = await asyncio.wait_for(t1, timeout=1)\n    except asyncio.TimeoutError:\n        print(\"t1 timeout\")\n    print(await t2)\nasyncio.run(main())\n```\n\n## 面试视角\n\n- **gather 与 wait 的区别？**（答：`gather` 高层封装、按提交顺序返回结果；`wait` 返回 done/pending 集合更灵活，可配 FIRST_COMPLETED 等）\n- **return_exceptions=True 的意义？**（答：让 gather 不因单个异常中断其余任务，把所有结果/异常一并返回便于处理）" },
      { id: 'py-c3-s2', title: '异步 HTTP 与数据库', direction: '用 aiohttp / async 驱动访问外部服务，避免阻塞事件循环。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\n异步客户端是**“预约取餐”模式**：同步 `requests.get` 是“站在窗口干等出餐”，期间整个事件循环（餐厅）都被你霸占；`aiohttp` / `httpx.AsyncClient` 是“扫码下单后去旁边等叫号”，把等待时间让给别的客人（协程）。数据库同理——必须用 async 驱动（`asyncpg`/`aiomysql`），否则一次 `execute` 的 IO 等待照样阻塞全局。\n\n## 核心知识点（锚定官方）\n\n- **aiohttp 客户端**：`async with aiohttp.ClientSession() as s: async with s.get(url) as r: data = await r.json()`。[aiohttp 文档](https://docs.aiohttp.org/en/stable/)\n- **httpx 异步**：`async with httpx.AsyncClient() as c: r = await c.get(url)`。[httpx 文档](https://www.python-httpx.org/)\n- **异步数据库**：`asyncpg`（`await conn.fetch`）、`aiomysql`、SQLAlchemy 1.4+ `AsyncSession`。[asyncpg](https://magicstack.github.io/asyncpg/current/)\n- **Session 复用**：客户端/Session 应复用而非每请求新建，避免握手开销。\n\n## 常见坑\n\n- **在 async 里调同步阻塞库**：`requests`/`pymysql` 阻塞循环，必须换 async 版或丢进线程池。\n- **Session 不关闭**：`async with` 确保释放连接，否则连接泄漏。\n- **连接数爆炸**：高并发下未限制并发请求数，可能打满对端或本地文件描述符。\n\n## 动手自测\n\n```python\nimport aiohttp, asyncio\nasync def fetch(url):\n    async with aiohttp.ClientSession() as s:\n        async with s.get(url) as r:\n            return await r.json()\nasync def main():\n    return await asyncio.gather(fetch(u) for u in urls)\nasyncio.run(main())\n```\n\n## 面试视角\n\n- **为什么 async 项目里不能用 requests？**（答：requests 是同步阻塞，会卡住整个事件循环，使并发失效，必须用 aiohttp/httpx.AsyncClient）\n- **async 数据库驱动相比同步的优势？**（答：IO 等待期间让出事件循环服务其他请求，单进程即可扛更高并发连接）" },
      { id: 'py-c3-s3', title: '线程池与多进程', direction: '理解 GIL 限制，用 run_in_executor / ProcessPoolExecutor 做并行计算。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\nGIL（全局解释器锁）是**“单人理发椅”**：同一时刻只有一个线程能执行 Python 字节码，所以多线程**算不动 CPU 密集任务**（线程们轮着坐那把椅子）。破局两招：① 把重活丢给**线程池**（适合 IO 阻塞，让出 GIL 时别的能跑）；② 用**多进程**开多个独立解释器（每把椅子各干各的，真并行）。`run_in_executor` 是“把同步重活塞进后台工位，腾出事件循环”。\n\n## 核心知识点（锚定官方）\n\n- **GIL 真相**：CPython 单进程内多线程无法并行执行字节码，CPU 密集仍被串行化。[GIL 说明](https://wiki.python.org/moin/GlobalInterpreterLock)\n- **线程池**：`loop.run_in_executor(None, blocking_fn, arg)` 在线程池跑阻塞函数，事件循环不卡。[并发执行器](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor)\n- **多进程**：`concurrent.futures.ProcessPoolExecutor` 跑 CPU 密集，绕过 GIL 真正并行。[ProcessPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#processpoolexecutor)\n- **选型**：IO 密集→asyncio/线程；CPU 密集→多进程。\n\n## 常见坑\n\n- **多进程传闭包/lambda**：`ProcessPoolExecutor` 需可 pickle 的目标函数，闭包/lambda 常不可序列化。\n- **进程间状态不共享**：多进程各自内存独立，需用 Queue/Manager/外部存储通信。\n- **线程池过大**：线程创建有成本，无限提交导致调度恶化，应设固定 `max_workers`。\n\n## 动手自测\n\n```python\nimport asyncio, concurrent.futures\nasync def main():\n    loop = asyncio.get_running_loop()\n    with concurrent.futures.ProcessPoolExecutor() as p:\n        res = await loop.run_in_executor(p, cpu_heavy, data)\n    return res\n```\n\n## 面试视角\n\n- **什么时候多线程有用、什么时候没用？**（答：IO 等待时线程让出 GIL，多线程提升吞吐；CPU 密集因 GIL 无法并行，需用多进程）\n- **asyncio 和多线程能混用吗？**（答：能，用 `run_in_executor` 把阻塞同步代码放进线程池，避免阻塞事件循环）" },
      { id: 'py-c3-s4', title: '并发安全与队列', direction: '用 asyncio 锁/队列保护共享状态，规避竞态。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\nasyncio 里的“共享变量”像**一块公共白板**：多个协程都来写，若不在 `await` 边界处加保护，交错写入会乱套。asyncio 的 `Lock` 是“协程专用的排队笔”——同一时刻只放一个协程写；`asyncio.Queue` 则是“异步安全的传送带”，生产者 `put`、消费者 `get`，天然解耦且无需手动加锁。\n\n## 核心知识点（锚定官方）\n\n- **asyncio.Lock**：`async with lock: shared += 1` 在临界区排斥其他协程。[asyncio 同步原语](https://docs.python.org/3/library/asyncio-sync.html)\n- **Queue**：`q = asyncio.Queue(maxsize=10)`；`await q.put(x)` / `x = await q.get()`；`q.task_done()` 配合 `q.join()` 等待清空。[asyncio Queue](https://docs.python.org/3/library/asyncio-queue.html)\n- **Event/Event**：`event.set()` / `await event.wait()` 做协程间信号通知。\n- **注意**：asyncio 无 GIL 干扰问题，但**仍非线程安全**——跨线程需 `threading.Lock`。\n\n## 常见坑\n\n- **用 threading.Lock 保护协程**：`threading.Lock` 阻塞线程、不配合事件循环，协程场景必须用 `asyncio.Lock`。\n- **忘记 task_done**：`Queue.join()` 永远等不到完成，消费者需 `task_done()`。\n- **在临界区 await 其他锁**：嵌套锁可能死锁，需固定加锁顺序。\n\n## 动手自测\n\n```python\nimport asyncio\nlock = asyncio.Lock()\ncounter = 0\nasync def inc():\n    global counter\n    async with lock:\n        counter += 1\nasync def main():\n    await asyncio.gather(*(inc() for _ in range(100)))\nasyncio.run(main())\nprint(counter)\n```\n\n## 面试视角\n\n- **asyncio.Lock 和 threading.Lock 区别？**（答：前者在单线程事件循环内协程间互斥、不阻塞线程；后者跨线程、会阻塞操作系统线程）\n- **为什么 asyncio 程序也可能需要锁？**（答：虽无 GIL 竞争，但多个协程交错写同一变量仍会产生逻辑竞态，需临界区保护）" }
    ]
  },
  {
    id: 'py-c4', subtrack: 'python', position: 107,
    title: 'SQLAlchemy ORM',
    goal: '用 SQLAlchemy 2.0 风格完成引擎、会话、模型映射与查询，掌握生产数据访问层。',
    sections: [
      { id: 'py-c4-s1', title: '引擎与会话', direction: '创建引擎与 Session，理解连接池与生命周期。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\nSQLAlchemy 分两层：**Engine** 是“数据库连接池管理员”，掌管一组到数据库的水龙头；**Session** 是“一次对话的便签本”——你往里 add 对象、最后 commit 一次性把便签上的改动刷进库。对话结束（`session.close()`）便签清空，但池里的水龙头（连接）回收复用，不真正断开。\n\n## 核心知识点（锚定官方）\n\n- **引擎**：`engine = create_engine(\"postgresql+psycopg://u:p@h/db\", pool_size=10, max_overflow=20)`。[Engine 配置](https://docs.sqlalchemy.org/en/20/core/engines.html)\n- **Session**：`Session(engine)` 或 `sessionmaker(bind=engine)`；`with Session(engine) as s:` 自动关闭。[会话](https://docs.sqlalchemy.org/en/20/orm/session.html)\n- **连接池**：`pool_size` 常驻连接数、`max_overflow` 峰值溢出、`pool_pre_ping=True` 防用断连。\n- **2.0 风格**：`engine.connect()` 用 `text()` 执行原生 SQL；`future=True` 默认开启。\n\n## 常见坑\n\n- **Session 不关闭泄漏**：长驻服务须 `close()` 或 `with`，否则连接耗尽。\n- **跨线程用同一 Session**：Session 非线程安全，每个线程/请求用独立实例（FastAPI 用依赖注入 per-request 创建）。\n- **pool_pre_ping 缺失**：MySQL 8h 空闲断连后拿到死连接报 `MySQL server has gone away`。\n\n## 动手自测\n\n```python\nfrom sqlalchemy import create_engine\nfrom sqlalchemy.orm import sessionmaker, Session\nengine = create_engine(\"sqlite:///app.db\", pool_pre_ping=True)\nSessionLocal = sessionmaker(bind=engine, expire_on_commit=False)\nwith SessionLocal() as s:\n    rows = s.execute(text(\"SELECT 1\")).fetchall()\n```\n\n## 面试视角\n\n- **Session 为什么不线程安全？**（答：它缓存身份映射与待刷状态，跨线程共享会互相污染，应每请求新建）\n- **pool_pre_ping 解决什么问题？**（答：每次取连接先发探活 SQL，避免使用已被服务端回收的死连接）" },
      { id: 'py-c4-s2', title: '模型与映射', direction: '用 DeclarativeBase 定义表结构，理解类型与约束。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\nSQLAlchemy 模型是**“类即表、属性即列”的契约**：写一个继承 `DeclarativeBase` 的类，`__tablename__` 指定表名，`mapped_column` 声明每列的 Python 类型与数据库约束。ORM 在背后把对象属性和 SQL 行列互译——你操作对象，它生成 SQL。\n\n## 核心知识点（锚定官方）\n\n- **基类**：`class Base(DeclarativeBase): pass`；模型继承 `Base`。[映射定义](https://docs.sqlalchemy.org/en/20/orm/declarative_config.html)\n- **列声明**：`id: Mapped[int] = mapped_column(primary_key=True)`；`name: Mapped[str] = mapped_column(String(100), nullable=False)`。[类型注解映射](https://docs.sqlalchemy.org/en/20/orm/declarative_tables.html)\n- **约束**：`unique=True`、`index=True`、`default`、`server_default`、`ForeignKey(\"users.id\")`。\n- **元数据创建**：`Base.metadata.create_all(engine)` 建表（生产建议用 Alembic 迁移而非此）。\n\n## 常见坑\n\n- **类型注解缺失**：2.0 风格下 `Mapped[...]` 注解驱动映射，漏注解得不到列。\n- **String 不设长度**：MySQL 要求 `VARCHAR` 有长度，不设会报错或默认过大。\n- **create_all 与迁移工具混用**：生产用 Alembic 做版本化迁移，`create_all` 仅开发便利。\n\n## 动手自测\n\n```python\nfrom sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column\nclass Base(DeclarativeBase): pass\nclass User(Base):\n    __tablename__ = \"users\"\n    id: Mapped[int] = mapped_column(primary_key=True)\n    name: Mapped[str] = mapped_column(String(100), nullable=False)\nBase.metadata.create_all(engine)\n```\n\n## 面试视角\n\n- **SQLAlchemy 1.x 与 2.0 风格的主要差异？**（答：2.0 用 `Mapped`/`mapped_column` 类型注解驱动、query 改 `select()` 表达式、统一 future 引擎）\n- **为什么生产用 Alembic 而不是 create_all？**（答：Alembic 做可版本化、可回滚迁移，create_all 只建不删改、无历史记录）" },
      { id: 'py-c4-s3', title: 'CRUD 与查询', direction: '用 select() 表达式与 Session API 完成增删改查。',
        content: "> 时效 | 核验=2026-09-05 | 风险=低 | 来源=官方\n\n## 心智模型\n\n2.0 的查询像**“先写好一张取货单（`select(User).where(...)`），再交给 Session 去库里照单取货”**。相比旧版 `session.query(User)`，新风格用标准 SQL 表达式构造，类型更安全、可与 `asyncio` 驱动配合。增（`add`）是“把货放上便签”，`commit` 才“结账入库”。\n\n## 核心知识点（锚定官方）\n\n- **查询**：`stmt = select(User).where(User.name == \"a\"); res = s.execute(stmt).scalars().all()`。[查询指南](https://docs.sqlalchemy.org/en/20/orm/queryguide.html)\n- **插入**：`s.add(user); s.commit()`；批量 `s.add_all([...])`。\n- **更新**：查出来改属性再 `commit`；或 `s.execute(update(User).where(...).values(...))`。\n- **删除**：`s.delete(user)` / `s.execute(delete(User).where(...))`。\n- **过滤/排序/分页**：`.where()`、`.order_by()`、`.limit().offset()`。\n\n## 常见坑\n\n- **commit 后对象过期**：默认 `expire_on_commit=True` 使属性在 commit 后失效，取属性触发重新查询；可设 `expire_on_commit=False`。\n- **N+1 查询**：访问关联属性逐条触发 SQL，用 `selectinload(User.orders)` 预加载。\n- **scalars() vs all()**：`execute().all()` 返回 Row 元组，`scalars()` 直接取实体，易混。\n\n## 动手自测\n\n```python\nfrom sqlalchemy import select, update\nstmt = select(User).where(User.name == \"a\").order_by(User.id).limit(10)\nusers = s.execute(stmt).scalars().all()\ns.execute(update(User).where(User.id == 1).values(name=\"b\"))\ns.commit()\n```\n\n## 面试视角\n\n- **怎么避免 SQLAlchemy 的 N+1？**（答：用 `selectinload`/`joinedload` 预加载关联，控制 `lazy` 策略）\n- **2.0 的 select() 相比 query() 好处？**（答：统一表达式 API、类型推导更友好、可配合 async 驱动、贴近标准 SQL）" },
      { id: 'py-c4-s4', title: '关系与事务', direction: '定义关联与事务边界，理解级联与外键约束。',
        content: "> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方\n\n## 心智模型\n\n关系是**“两张表之间的连线标签”**：`relationship()` 在 Python 侧把两个模型“牵手”，ORM 自动按外键生成 JOIN 查询。`ForeignKey` 是“物理连线”（数据库约束），`relationship` 是“逻辑握手”（对象导航）。事务则是“一批便签改动要么一起结账、要么全撤”，靠 `commit`/`rollback` 控制。\n\n## 核心知识点（锚定官方）\n\n- **外键**：`user_id: Mapped[int] = mapped_column(ForeignKey(\"users.id\"))`。[关系](https://docs.sqlalchemy.org/en/20/orm/relationship_api.html)\n- **relationship**：`orders: Mapped[list[\"Order\"]] = relationship(back_populates=\"user\")`；一侧改自动同步另一侧。\n- **级联**：`cascade=\"all, delete-orphan\"` 控制删除父时子表行为。\n- **事务**：`with Session(engine) as s: ...; s.commit()`；异常 `s.rollback()` 回滚。`begin()` 可嵌套。\n\n## 常见坑\n\n- **双向 relationship 缺 back_populates**：两边不同步，导航属性为空。\n- **级联误删**：`delete-orphan` 在无父引用时自动删子行，需确认是否符合业务。\n- **事务里做远程调用**：拉长持锁时间，增加死锁风险，应只包必要 DB 操作。\n\n## 动手自测\n\n```python\nclass Order(Base):\n    __tablename__ = \"orders\"\n    id: Mapped[int] = mapped_column(primary_key=True)\n    user_id: Mapped[int] = mapped_column(ForeignKey(\"users.id\"))\n    user: Mapped[\"User\"] = relationship(back_populates=\"orders\")\nwith SessionLocal() as s:\n    u = s.get(User, 1)\n    print(u.orders)  # 自动 JOIN 加载\n```\n\n## 面试视角\n\n- **relationship 与 ForeignKey 的区别？**（答：FK 是数据库层的约束保证，relationship 是 ORM 层的对象导航便利，二者配合但不互相替代）\n- **SQLAlchemy 事务怎么保证原子性？**（答：Session 内的 flush/commit 包裹在 DB 事务中，异常 rollback 撤销未提交改动）" }
    ]
  },
  {
    id: 'py-c5', subtrack: 'python', position: 108,
    title: 'FastAPI 安全与认证',
    goal: '用 FastAPI Security 实现 OAuth2 密码流、JWT 签发校验与密码哈希，建立认证基线。',
    sections: [
      { id: 'py-c5-s1', title: 'OAuth2 密码流', direction: '用 OAuth2PasswordBearer 声明令牌依赖，定义登录端点。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\nOAuth2 密码流是**“用户拿账号密码换通行证”的约定**：在登录端点，客户端提交 `username/password`，服务端验身后发回 `access_token`；之后所有请求在 `Authorization: Bearer <token>` 头里带上这证。`OAuth2PasswordBearer` 是 FastAPI 提供的“查票员”——它声明“本系统令牌从哪取”，自动从请求里抽出令牌交给你的校验函数。\n\n## 核心知识点（锚定官方）\n\n- **声明方案**：`oauth2 = OAuth2PasswordBearer(tokenUrl=\"token\")`；路由依赖 `token: str = Depends(oauth2)` 取出令牌。[安全教程](https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/)\n- **登录端点**：`@app.post(\"/token\") def login(form: OAuth2PasswordRequestForm = Depends()): ...` 返回 `{\"access_token\": t, \"token_type\": \"bearer\"}`。[密码流](https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/)\n- **表单格式**：密码流用 `application/x-www-form-urlencoded`，`OAuth2PasswordRequestForm` 解析 `username/password/scopes`。\n- **依赖链**：`get_current_user(token=Depends(oauth2))` 验令牌并返回用户对象，路由再 `Depends(get_current_user)` 使用。\n\n## 常见坑\n\n- **tokenUrl 路径不一致**：前端拿令牌的地址须与 `tokenUrl` 完全一致（含前缀），否则 Swagger 授权失败。\n- **用 JSON body 而非表单**：密码流规范要求表单，用 JSON 会被 `OAuth2PasswordRequestForm` 解析为空。\n- **未设 token_type**：标准返回应带 `token_type: \"bearer\"`，部分前端据此判断。\n\n## 动手自测\n\n```python\nfrom fastapi.security import OAuth2PasswordBearer\nfrom fastapi import Depends\noauth2 = OAuth2PasswordBearer(tokenUrl=\"token\")\n@app.post(\"/token\")\ndef login(form: OAuth2PasswordRequestForm = Depends()):\n    # 校验 form.username / form.password\n    return {\"access_token\": make_token(form.username), \"token_type\": \"bearer\"}\n```\n\n## 面试视角\n\n- **OAuth2 密码流适合什么场景？**（答：自有第一方应用，用户信任客户端；第三方场景应走授权码流）\n- **OAuth2PasswordBearer 做了什么？**（答：声明令牌获取地址，自动从请求 `Authorization` 头抽取 Bearer 令牌并作为依赖注入）" },
      { id: 'py-c5-s2', title: 'JWT 签发与校验', direction: '用 JWT 库签发访问令牌，在依赖中验签并解析当前用户。',
        content: "> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方\n\n## 心智模型\n\nJWT 是**“服务端盖章的通行证”**：登录后用密钥签名，之后请求只验章不查库。FastAPI 里 `get_current_user` 依赖是“验票口”——拿到令牌、拆封验章、读出 `sub`（用户 ID），返回用户对象；后续 handler `Depends(get_current_user)` 就能直接用这个已认证用户，无需每个接口重写鉴权。\n\n## 核心知识点（锚定官方）\n\n- **签发**：`jwt.encode({\"sub\": str(uid), \"exp\": datetime.utcnow()+timedelta(hours=1)}, SECRET, algorithm=\"HS256\")`（PyJWT）或 `python-jose`。[JWT 安全教程](https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/)\n- **校验**：`jwt.decode(token, SECRET, algorithms=[\"HS256\"])`；捕获 `ExpiredSignatureError`/`JWTError` 返回 401。\n- **依赖组合**：`get_current_user(token: str = Depends(oauth2))` → 解析 → 返回用户；路由 `current_user: User = Depends(get_current_user)`。\n- **算法白名单**：decode 必须显式 `algorithms=[\"HS256\"]`，防 alg=none 绕过。\n\n## 常见坑\n\n- **SECRET 硬编码**：必须环境变量/密钥管理，泄露即可伪造任意用户令牌。\n- **用 utcnow/UTC 一致**：签发用 `datetime.utcnow()` 而校验按 UTC，混用本地时区会算错过期。\n- **sub 类型漂移**：JWT 数字 claim 解码为 int 或 str 取决于库，比较时统一类型。\n\n## 动手自测\n\n```python\nfrom jose import jwt  # python-jose\ntoken = jwt.encode({\"sub\": str(uid), \"exp\": datetime.utcnow()+timedelta(hours=1)},\n                   SECRET, algorithm=\"HS256\")\ndef get_current_user(tok: str = Depends(oauth2)):\n    payload = jwt.decode(tok, SECRET, algorithms=[\"HS256\"])\n    user = get_user(int(payload[\"sub\"]))\n    if not user: raise HTTPException(401)\n    return user\n```\n\n## 面试视角\n\n- **JWT 为什么要短时效 + 刷新令牌？**（答：访问令牌泄露窗口小，刷新令牌可服务端吊销，平衡安全与体验）\n- **alg=none 攻击如何防范？**（答：decode 时强制 `algorithms=[...]` 白名单，拒绝 none/非预期算法）" },
      { id: 'py-c5-s3', title: '密码哈希与登录', direction: '用 passlib/bcrypt 做密码哈希与比对，杜绝明文。',
        content: "> 时效 | 核验=2026-09-05 | 风险=高 | 来源=官方\n\n## 心智模型\n\npasslib 的 bcrypt 是**“带盐单向研磨”**：注册时把明文密码磨成不可逆密文（每次加盐不同，同密码密文也不同），存库的是粉末不是钥匙。登录时把输入密码用同一盐再磨一遍，比两杯粉末是否一致——一致即密码正确。明文存储等于把钥匙挂在门上，是严重安全事故。\n\n## 核心知识点（锚定官方）\n\n- **哈希**：`pwd = CryptContext(schemes=[\"bcrypt\"]); hashed = pwd.hash(\"secret\")`。[passlib](https://passlib.readthedocs.io/en/stable/)\n- **校验**：`pwd.verify(input, hashed)` 返回 bool；`pwd.needs_update(hashed)` 判断是否需升 cost 重哈希。\n- **注册流程**：接收密码 → `hash` → 存库；登录：`verify(输入, 存储hash)` → 失败 401。\n- **算法演进**：通过 `CryptContext` 多 schemes 平滑迁移旧哈希到新算法。\n\n## 常见坑\n\n- **明文比较 ==**：`input == stored` 比较密码是致命漏洞，必须 `verify` 哈希。\n- **依赖未安装 bcrypt**：`CryptContext(schemes=[\"bcrypt\"])` 需 `pip install bcrypt`，否则运行时报错。\n- **needs_update 忽略**：长期不升级哈希 cost，弱哈希持续暴露。\n\n## 动手自测\n\n```python\nfrom passlib.context import CryptContext\npwd = CryptContext(schemes=[\"bcrypt\"], deprecated=\"auto\")\nhashed = pwd.hash(\"secret\")\nif not pwd.verify(input_pwd, hashed):\n    raise HTTPException(401, \"bad credentials\")\n```\n\n## 面试视角\n\n- **为什么用 bcrypt 而非 md5/sha？**（答：md5/sha 设计快、易被 GPU 爆破；bcrypt 可调 cost 慢因子专门抗密码破解）\n- **needs_update 的作用？**（答：检测旧/弱哈希，登录成功时按新策略重哈希，实现无感算法升级）" },
      { id: 'py-c5-s4', title: '权限与作用域', direction: '用 OAuth2 scopes / 角色依赖实现细粒度授权。',
        content: "> 时效 | 核验=2026-09-05 | 风险=中 | 来源=官方\n\n## 心智模型\n\n作用域（scopes）是**“通行证上的权限标签”**：令牌签发时附带 `[\"read\", \"write\"]` 等范围，路由用 `Security(get_current_user, scopes=[\"write\"])` 要求令牌必须带对应标签才放行。角色（role）则是“用户身份徽章”——`get_current_active_user` 依赖里不仅验票，还查用户角色，非激活/无权限直接拒之门外。认证（你是谁）与授权（你能干啥）在此汇合。\n\n## 核心知识点（锚定官方）\n\n- **scopes 声明**：`oauth2 = OAuth2PasswordBearer(tokenUrl=\"token\", scopes={\"read\":\"Read\",\"write\":\"Write\"})`；登录时 `scopes=form.scopes` 写入令牌。[scopes 文档](https://fastapi.tiangolo.com/advanced/security/scopes/)\n- **依赖校验**：`def write_op(u: User = Security(get_current_user, scopes=[\"write\"]))`；缺 scope 自动 403。\n- **角色依赖**：`get_current_active_user(u = Depends(get_current_user))` 内 `if not u.is_active: raise 400`；组合出层级依赖。\n- **分层**：`authenticated` → `active` → `admin`，依赖层层叠加。\n\n## 常见坑\n\n- **只认证不授权**：验了令牌就放行所有接口，缺 scope/role 检查导致越权。\n- **scopes 拼写/大小写不一致**：令牌里的 scope 字符串与依赖要求必须精确匹配。\n- **依赖顺序错误**：`Security(..., scopes=...)` 必须基于已返回 user 的依赖，否则取不到用户上下文。\n\n## 动手自测\n\n```python\nfrom fastapi import Security\n@app.post(\"/items\", dependencies=[Security(get_current_user, scopes=[\"write\"])])\ndef create_item(item: Item, u: User = Depends(get_current_user)):\n    return item\n```\n\n## 面试视角\n\n- **认证（Authentication）与授权（Authorization）的区别？**（答：认证确认身份“你是谁”，授权确认权限“你能做什么”；JWT 携带 sub 是认证，scopes/role 是授权）\n- **scopes 相比角色（RBAC）的取舍？**（答：scopes 适合细粒度、跨服务的能力声明；RBAC 适合组织内角色层级，常结合使用）" }
    ]
  },
  ...BATCH3
]

function applySeed() {
  const raw = fs.readFileSync(SEED_PATH, 'utf-8')
  const content = JSON.parse(raw)
  const mod = content.modules.find((m) => m.id === 'backend')
  if (!mod) throw new Error('backend module not found')
  let added = 0
  for (const ch of CHAPTERS) {
    if (mod.chapters.some((c) => c.id === ch.id)) {
      console.log(`[seed] 跳过已存在 ${ch.id}`)
      continue
    }
    mod.chapters.push({
      id: ch.id, title: ch.title, goal: ch.goal, subtrack: ch.subtrack, sections: ch.sections
    })
    added++
  }
  if (added > 0) fs.writeFileSync(SEED_PATH, JSON.stringify(content))
  return added
}

function applyDb() {
  const db = new Database(DB_PATH)
  db.pragma('journal_mode = WAL')
  const insCh = db.prepare('INSERT OR IGNORE INTO chapters (id,module_id,title,goal,position,subtrack) VALUES (?,?,?,?,?,?)')
  const insSec = db.prepare('INSERT OR IGNORE INTO sections (id,chapter_id,title,direction,content,position) VALUES (?,?,?,?,?,?)')
  const tx = db.transaction(() => {
    for (const ch of CHAPTERS) {
      insCh.run(ch.id, 'backend', ch.title, ch.goal, ch.position, ch.subtrack)
      ch.sections.forEach((s, i) => insSec.run(s.id, ch.id, s.title, s.direction ?? null, s.content, i))
    }
  })
  tx()
  db.close()
}

if (DRY) {
  console.log('[dry-run] 将新增章节:')
  for (const ch of CHAPTERS) console.log(`  ${ch.id} [${ch.subtrack}] pos=${ch.position} | ${ch.title} (${ch.sections.length} 节)`)
  console.log('[dry-run] 未做任何修改')
} else {
  const added = applySeed()
  console.log(`[seed] 新增 ${added} 章`)
  applyDb()
  console.log(`[db] 已写入 ${CHAPTERS.length} 章（INSERT OR IGNORE，已存在则跳过）`)
  console.log('完成：go-c1..c8 (Go+Gin) + py-c1..c8 (Python+FastAPI)，共 ' + CHAPTERS.length + ' 章。')
}
