// M5 前端 VIP 实战卷
export const feSet = {
  id: 'exam-fe-vip-3',
  name: '前端 VIP · 架构与工程化实战卷',
  track: 'frontend',
  level: '高级',
  duration: 90,
  vip: 1,
  choices: [
    { id: 'm5-fe3-c1', tag: 'TypeScript', q: '以下关于 TypeScript 类型编程的说法，错误的是？',
      options: ['泛型可以把类型参数化，提升复用', 'keyof T 得到 T 所有键的联合类型', '条件类型 T extends U ? X : Y 可按类型分支', 'interface 可以被声明合并，但 type 别名不能交叉扩展'],
      answer: ['D'], explain: 'type 别名可用 & 交叉类型扩展（如 A & B），也能通过条件类型组合；并非“不能扩展”。A/B/C 均为正确描述。', multi: 0 },
    { id: 'm5-fe3-c2', tag: '渲染原理', q: '浏览器从接收 HTML 到首屏渲染，以下哪个阶段负责把 CSSOM 与 DOM 合成渲染树（Render Tree）？',
      options: ['解析 HTML 生成 DOM', '样式计算（Style）', '布局（Layout/Reflow）', '绘制（Paint）'],
      answer: ['B'], explain: '样式计算阶段把 CSSOM 与 DOM 规则匹配到元素，生成带样式的 Render Tree；Layout 才计算几何位置，Paint 负责像素绘制。', multi: 0 },
    { id: 'm5-fe3-c3', tag: '性能优化', q: '关于 Web Vitals 指标，下列说法正确的是？（多选）',
      options: ['LCP 衡量最大内容绘制，目标 < 2.5s', 'CLS 衡量布局偏移，目标 < 0.1', 'FID 已被 INP 取代，INP 衡量交互延迟', 'TTFB 属于 Web Vitals 核心三项之一'],
      answer: ['A', 'B', 'C'], explain: '核心三项为 LCP/INP/CLS；TTFB 是诊断指标不算核心三项。A/B/C 正确。', multi: 1 },
    { id: 'm5-fe3-c4', tag: '框架原理', q: 'Vue 3 的响应式系统中，effect 与依赖的收集发生在？',
      options: ['组件挂载时主动调用 track', 'getter 被访问时自动 track', 'setter 触发时 track', '编译阶段静态分析'],
      answer: ['B'], explain: 'Vue 3 在响应式对象的 getter 中用 track() 收集当前激活的 effect，setter 中用 trigger() 触发更新。', multi: 0 },
    { id: 'm5-fe3-c5', tag: '微前端', q: '微前端架构下，多个子应用共享同一个依赖（如 Vue）时，推荐哪种方案避免重复打包？',
      options: ['每个子应用独立打包 Vue', '使用 Module Federation 共享运行时依赖', '把所有子应用合并为单包', '用 iframe 隔离'],
      answer: ['B'], explain: 'Module Federation 可在构建期声明共享依赖，运行时只加载一份，避免重复与版本冲突；iframe 虽隔离但难通信、体积大。', multi: 0 },
    { id: 'm5-fe3-c6', tag: '工程化', q: '关于 Tree Shaking，下列说法正确的是？',
      options: ['它依赖 ESM 的静态结构分析', 'CommonJS 也能被完美 tree-shake', '必须开启 minify 才能生效', '只影响 CSS 不影 JS'],
      answer: ['A'], explain: 'Tree Shaking 依赖 ESM 的静态 import/export 分析；CommonJS 动态特性使其难以安全剔除。它属于打包优化，minify 是压缩，二者独立。', multi: 0 },
    { id: 'm5-fe3-c7', tag: '安全', q: '防范 XSS 的最佳组合策略是？（多选）',
      options: ['对用户输入做转义/编码', '设置 CSP 限制脚本来源', '把敏感 token 存 localStorage 并全局可读', '对富文本使用白名单 sanitizer'],
      answer: ['A', 'B', 'D'], explain: '转义、CSP、富文本白名单 sanitizer 共同构成纵深防御；把 token 放 localStorage 易被 XSS 窃取，应避免。', multi: 1 },
    { id: 'm5-fe3-c8', tag: '状态管理', q: '在大型前端应用中，为避免“全局状态滥用”，应优先考虑？',
      options: ['所有状态都放 Redux', '按状态作用域拆分：服务端缓存 / 全局 UI / 本地组件', '一律用 Context 不分层', '状态越多越好便于调试'],
      answer: ['B'], explain: '推荐按作用域分层：服务端数据用 SWR/Query 缓存，全局 UI 用轻量 store，本地状态用组件内。避免把所有状态塞进单一全局仓导致耦合。', multi: 0 },
    { id: 'm5-fe3-c9', tag: '构建工具', q: 'Vite 开发环境快于传统打包器的核心原因是？',
      options: ['Vite 用 Go 重写', 'Vite 利用浏览器原生 ESM，按需编译单个模块', 'Vite 不做任何转换', 'Vite 缓存了全部产物'],
      answer: ['B'], explain: 'Vite 开发期不打包，借助浏览器原生 ESM 按需请求并即时编译单文件，避免全量打包；生产仍用 Rollup。', multi: 0 },
    { id: 'm5-fe3-c10', tag: '可访问性', q: '提升 Web 可访问性（a11y）的关键措施不包括？',
      options: ['为图标按钮提供 aria-label', '保证颜色对比度达标', '所有交互元素可用键盘到达', '为保证美观关闭 prefers-reduced-motion'],
      answer: ['D'], explain: '应尊重 prefers-reduced-motion 而非关闭它；前三项均为 a11y 基本实践。', multi: 0 },
    { id: 'm5-fe3-c11', tag: 'HTTP缓存', q: 'CDN 上静态资源更新后客户端仍命中旧版本，最稳妥的发布策略是？',
      options: ['强制用户清缓存', '文件名带内容 hash + 长缓存', '只用 no-cache', '缩短 TTL 到 0'],
      answer: ['B'], explain: '内容 hash 文件名（如 app.a1b2.js）使内容变更即新 URL，可安全设置一年长缓存；老 URL 自然失效。', multi: 0 },
    { id: 'm5-fe3-c12', tag: '设计系统', q: 'Design Token 的主要价值是？',
      options: ['让设计师少画图', '把设计决策（颜色/间距/字号）沉淀为可跨平台复用的单一数据源', '替代 CSS 变量', '仅为美观'],
      answer: ['B'], explain: 'Design Token 把设计语义（如 color.primary）作为单一数据源，可编译到 CSS 变量、iOS/Android 等多端，保证一致性。', multi: 0 },
    { id: 'm5-fe3-c13', tag: '测试', q: '组件测试中应优先覆盖的是？',
      options: ['第三方库内部实现', '组件对外行为（交互/输出）而非内部细节', '所有私有方法', '渲染每一帧动画'],
      answer: ['B'], explain: '测试应关注组件可观察行为（用户交互、DOM 输出、事件），而非内部实现细节，降低脆弱性。', multi: 0 },
    { id: 'm5-fe3-c14', tag: 'Web Components', q: '关于 Custom Elements 与框架组件的区别，正确的是？',
      options: ['Custom Elements 是框架专属', 'Custom Elements 是浏览器原生标准，跨框架可用', '框架组件可被任意页面直接使用', '两者完全等价'],
      answer: ['B'], explain: 'Custom Elements 基于 Web 标准，可脱离框架在任意页面使用；框架组件依赖其运行时。', multi: 0 },
    { id: 'm5-fe3-c15', tag: '并发渲染', q: 'React 的并发特性（Concurrent Features）主要解决了？',
      options: ['打包体积过大', '可中断/可恢复的渲染，提升交互响应', '只能单线程', '无法做 SSR'],
      answer: ['B'], explain: '并发特性允许渲染被高优先级更新中断与恢复（如 startTransition），避免长任务阻塞输入。', multi: 0 }
  ],
  written: [
    { id: 'm5-fe3-w1', q: '请描述你如何为大型 Vue/React 应用设计一个可扩展的状态管理方案，需区分服务端缓存、全局 UI 状态与本地状态，并说明技术选型与理由。',
      points: ['按作用域分层：服务端数据用 Query/SWR 缓存', '全局 UI 状态用轻量 store（Pinia/Zustand）', '本地状态保留在组件内', '避免单一大 store 导致耦合', '说明跨层通信与持久化边界'],
      reference: '推荐把状态按来源与生命周期分层：①服务端数据（用户、列表）由 SWR/React Query 管理，自带缓存/重验/失效；②全局 UI 状态（主题、侧栏、登录态）用 Pinia/Zustand 等轻量仓库；③组件本地状态用 useState/ref。这样服务端状态不污染 UI store，重渲染更可控。跨层通过事件或选择器组合，持久化只针对需要的 UI 状态。' },
    { id: 'm5-fe3-w2', q: '首屏 LCP 为 4.8s，请给出一个系统化的优化路线图（至少 6 步），并说明如何验证收益。',
      points: ['打包分析定位大依赖', '路由懒加载与分包', '关键资源 preload/CDN/压缩', '图片优化与字体 font-display', 'SSR/骨架屏直出', '用 Lighthouse + RUM 闭环验证'],
      reference: '步骤：1) rollup-plugin-visualizer 找大包，按需引入/换轻量库；2) 动态 import 路由分包；3) 静态资源 CDN + gzip/brotli + preload 关键资源；4) 图片 WebP/响应式/懒加载，字体 font-display:swap；5) 架构级 SSR/SSG 或骨架屏；6) 用 Lighthouse 实验室数据与线上 RUM 验证 LCP 下降，形成闭环。' },
    { id: 'm5-fe3-w3', q: '微前端有哪些主流落地方案？请对比 qiankun 类（应用级隔离）与 Module Federation（模块级共享）的适用场景与 trade-off。',
      points: ['应用级：独立构建部署、JS 沙箱隔离', '模块级：运行时共享依赖、体积小', '隔离强度 vs 体积/性能', '团队技术栈是否统一'],
      reference: '应用级（qiankun/single-spa）各子应用独立构建、JS 沙箱 + CSS 隔离强，适合多团队异构技术栈，但运行时开销与通信成本较高；Module Federation 在构建期声明共享依赖，运行时只加载一份，体积小、性能好，适合同源技术栈的大仓/中台。选型看团队耦合度与隔离需求。' },
    { id: 'm5-fe3-w4', q: '如何在不牺牲开发体验的前提下，为前端项目建立一套可靠的依赖安全与 Supply Chain 防护？',
      points: ['锁定依赖版本（lockfile）', 'CI 中集成 npm audit/SCA', '最小权限与私有源', '子资源完整性 SRI', '定期更新与回滚预案'],
      reference: '措施：①提交 lockfile 保证可复现；②CI 跑 npm audit / SCA 扫描已知漏洞并阻断高危；③使用私有源+最小权限令牌；④对第三方 CDN 脚本加 SRI 与 CSP；⑤建立定期升级与紧急回滚流程。核心是“可复现 + 可审计 + 可阻断”。' },
    { id: 'm5-fe3-w5', q: '请手写一个支持取消的 delay（sleep）函数，并说明它在组件卸载时如何避免内存泄漏/竞态。',
      points: ['返回 Promise 且暴露 abort', '用 AbortController 或标志位', '组件卸载时调用取消', '避免 setState 已卸载组件'],
      reference: 'function cancellableDelay(ms){let id;const p=new Promise((res)=>{id=setTimeout(res,ms)});p.cancel=()=>clearTimeout(id);return p;} 在组件中用 ref 保存，卸载时 cancel；或用 AbortController 在 fetch 场景统一取消。关键是组件卸载后不再对已完成异步做 setState，防止泄漏与竞态。' }
  ]
}
