// M5 运维 VIP 卷 · 选择题
export const opChoices = [
  { id: 'm5-op3-c1', tag: 'Kubernetes', q: 'Kubernetes 中 Pod 的最小调度单位是？',
    options: ['Container', 'Pod', 'Node', 'Namespace'],
    answer: ['B'], explain: 'Pod 是 K8s 最小调度与部署单位，包含共享网络/存储的一个或多个容器。', multi: 0 },
  { id: 'm5-op3-c2', tag: 'Kubernetes', q: 'Service 的主要作用是？',
    options: ['给 Pod 固定 IP', '为一组动态 Pod 提供稳定访问入口与负载均衡', '替代 Ingress', '做持久化存储'],
    answer: ['B'], explain: 'Pod IP 会变，Service 通过 label selector 聚合后端并提供稳定 VIP 与负载均衡。', multi: 0 },
  { id: 'm5-op3-c3', tag: '可观测性', q: '可观测性的三大支柱是？',
    options: ['日志、指标、链路追踪', 'CPU、内存、磁盘', '监控、告警、值班', '蓝绿、金丝雀、滚动'],
    answer: ['A'], explain: 'Logs/Metrics/Traces 三支柱：指标看趋势、日志看事件、链路看请求流转。', multi: 0 },
  { id: 'm5-op3-c4', tag: 'SRE', q: 'SLO/SLI/Error Budget 的关系，正确的是？',
    options: ['SLI 是实际指标，SLO 是目标，Error Budget 是容许错误额度', 'Error Budget 越大越好无约束', 'SLO 必须等于 100%', 'SLI 是目标'],
    answer: ['A'], explain: 'SLI 度量实际表现（如成功率），SLO 是目标阈值，Error Budget = 1 - SLO 的容许错误，用尽则暂停发布专注稳定性。', multi: 0 },
  { id: 'm5-op3-c5', tag: 'CI/CD', q: '关于蓝绿部署与金丝雀发布，说法正确的是？',
    options: ['蓝绿是两套环境瞬时切换，回滚快', '金丝雀是先把小部分流量导新版本观察', '两者都是只部署一次', '金丝雀不能回滚'],
    answer: ['A', 'B'], explain: '蓝绿维护两套环境、流量整体切换，回滚快；金丝雀按比例逐步放量验证。两者都支持回滚。', multi: 1 },
  { id: 'm5-op3-c6', tag: '容器', q: 'Docker 镜像体积过大，最有效的优化是？',
    options: ['用更精简 base 镜像 + 多阶段构建', '把所有依赖装进一个层', '增大内存', '关闭缓存'],
    answer: ['A'], explain: '多阶段构建只在最终镜像保留运行所需，配合 alpine/distroless 显著减小体积、提升安全与启动速度。', multi: 0 },
  { id: 'm5-op3-c7', tag: '监控告警', q: '告警疲劳（Alert Fatigue）的应对不包括？',
    options: ['按严重程度分级路由', '为每条告警设明确 owner 与 actionable runbook', '无差别全量通知所有人', '合并/抑制重复告警'],
    answer: ['C'], explain: '无差别广播会淹没有效信号；应分级、路由到责任人、配 runbook、做抑制与降噪。', multi: 0 },
  { id: 'm5-op3-c8', tag: 'IaC', q: '基础设施即代码（IaC）的核心收益是？',
    options: ['环境可版本化、可复现、可审查', '手动操作更快', '不需要文档', '只能用于测试'],
    answer: ['A'], explain: 'IaC 把基础设施写成声明式代码，纳入版本管理，环境一致、可审计、可回滚。', multi: 0 },
  { id: 'm5-op3-c9', tag: '网络', q: 'K8s 中 Ingress 的职责是？',
    options: ['集群内 Service 间通信', '七层（HTTP）路由与 TLS 终止，对外暴露服务', '管理存储卷', '调度 Pod'],
    answer: ['B'], explain: 'Ingress 提供 HTTP 路由、虚拟主机、TLS 终止，是集群外部访问七层服务的主要入口。', multi: 0 },
  { id: 'm5-op3-c10', tag: '故障演练', q: '混沌工程（Chaos Engineering）的核心做法是？',
    options: ['在生产受控注入故障以验证系统韧性', '尽量不碰生产', '只做文档演练', '随机删除数据库'],
    answer: ['A'], explain: '混沌工程在可控范围主动向系统注入故障（杀节点、丢包），验证并提升真实韧性，而非盲目破坏。', multi: 0 },
  { id: 'm5-op3-c11', tag: '存储', q: '有状态应用（如数据库）在 K8s 中应使用？',
    options: ['普通 Pod 临时存储', 'StatefulSet + 持久卷（PVC/PV）', 'ConfigMap 存数据', 'EmptyDir 永久保存'],
    answer: ['B'], explain: 'StatefulSet 提供稳定网络标识与有序部署，配合 PVC/PV 实现持久化存储，适合数据库等有状态负载。', multi: 0 },
  { id: 'm5-op3-c12', tag: '安全', q: '容器安全加固措施不包括？',
    options: ['以非 root 用户运行', '只读根文件系统', '赋予容器 privileged 全集权限', '最小基础镜像 + 镜像扫描'],
    answer: ['C'], explain: 'privileged 会放开宿主权限，增大攻击面；应非 root、只读根、最小镜像、扫描漏洞。', multi: 0 },
  { id: 'm5-op3-c13', tag: '成本', q: '降低云成本的有效手段是？（多选）',
    options: ['资源右配（requests/limits 合理）', '闲置资源回收与定时启停', '长期预留实例/ Saving Plans', '盲目拉满所有规格'],
    answer: ['A', 'B', 'C'], explain: '右配、回收闲置、长周期预留均可降本；盲目高配反而浪费。', multi: 1 },
  { id: 'm5-op3-c14', tag: '日志', q: '集中式日志架构（如 ELK/Loki）相比散落本地日志的优势是？',
    options: ['统一检索、关联与留存', '更快的本地 IO', '不需要存储', '只能在单机能看'],
    answer: ['A'], explain: '集中式日志统一采集、索引、关联与长期留存，便于跨服务排障与审计。', multi: 0 },
  { id: 'm5-op3-c15', tag: '高可用', q: '提升系统可用性的关键手段是？（多选）',
    options: ['冗余与多副本', '消除单点（数据库/网关）', '自动故障转移', '依赖单一供应商不备份'],
    answer: ['A', 'B', 'C'], explain: '冗余、去单点、自动转移共同提升可用性；单供应商无备份反而增加风险。', multi: 1 }
]
